package se.nullable.sbtix

/**
 * A simplified helper for writing Nix expressions
 */
object NixWriter2 {
  private def fileName(path: String): String =
    path.takeWhile(ch => ch != '?' && ch != '#').split('/').lastOption.getOrElse("")

  private def chooseArtifactForKey(artifacts: Seq[NixArtifact]): NixArtifact =
    artifacts
      .sortBy { artifact =>
        val urlFileMatchesPath =
          fileName(artifact.url) == fileName(artifact.relativePath)
        // If no URL filename matches the offline path, keep the fallback deterministic.
        (if (urlFileMatchesPath) 0 else 1, artifact.url, artifact.sha256)
      }
      .head

  /**
   * Creates a Nix expression for the repository
   */
  def apply(
    repos: Set[NixRepo],
    artifacts: Set[NixArtifact],
    scalaVersion: String,
    sbtVersion: String
  ): String = {
    val builder = new StringBuilder

    builder.append("# This file was automatically generated by Sbtix. Do not edit manually.\n")
    builder.append("{\n")
    
    // Versioning section
    builder.append("  \"versioning\" = [{\n")
    builder.append(s"""      "scalaVersion" = "$scalaVersion";\n""")
    builder.append(s"""      "sbtVersion" = "$sbtVersion";\n""")
    builder.append("    }];\n")
    
    // Repositories section
    builder.append("  \"repos\" = {\n")
    val reposToWrite =
      if (repos.isEmpty) Seq(NixRepo("nix-public"))
      else repos.toSeq.sortBy(_.name)
    reposToWrite.foreach { repo =>
      builder.append(repo.toNix.replace("  ", "    "))
      builder.append("\n")
    }
    builder.append("  };\n\n")
    
    // Artifacts section
    builder.append("  \"artifacts\" = {\n")
    val sortedArtifacts =
      artifacts.toSeq
        .filterNot(_.url.startsWith("file:"))
        .groupBy(_.entryName)
        .values
        .map(chooseArtifactForKey)
        .toSeq
        .sortBy(a => (a.repoName, a.relativePath))
    if (sortedArtifacts.nonEmpty) {
      builder.append(sortedArtifacts.map(_.toNix).mkString("\n"))
      builder.append("\n")
    }
    builder.append("  };\n")
    builder.append("}")

    builder.toString
  }
}
