# This file was automatically generated by Sbtix. Do not edit manually.
{
  "versioning" = [{
      "scalaVersion" = "2.13.16";
      "sbtVersion" = "1.10.7";
    }];
  "repos" = {
    "nix-private-demo" = "";
    "nix-public" = "";
  };

  "artifacts" = {
    "nix-private-demo/private-org/private-name/1.2.3/private-name-1.2.3-sources.jar" = {
      url = "http://test:test@localhost:9877/plugin/src/sbt-test/artifacts/private-org/private-name/1.2.3/private-name-1.2.3-sources.jar";
      sha256 = "75E1D3470B31B36C8D497E37BF276D4A03F480CF22763D77456E78D8EF286FEC";
    };
    "nix-private-demo/private-org/private-name/1.2.3/private-name-1.2.3-tests.jar" = {
      url = "http://test:test@localhost:9877/plugin/src/sbt-test/artifacts/private-org/private-name/1.2.3/private-name-1.2.3-tests.jar";
      sha256 = "75E1D3470B31B36C8D497E37BF276D4A03F480CF22763D77456E78D8EF286FEC";
    };
    "nix-private-demo/private-org/private-name/1.2.3/private-name-1.2.3.jar" = {
      url = "http://test:test@localhost:9877/plugin/src/sbt-test/artifacts/private-org/private-name/1.2.3/private-name-1.2.3.jar";
      sha256 = "A5FD38B5D04D2A236B6C75C2C2EDFA40FE06F0B819596E37043197EC9671CF61";
    };
    "nix-private-demo/private-org/private-name/1.2.3/private-name-1.2.3.pom" = {
      url = "http://test:test@localhost:9877/plugin/src/sbt-test/artifacts/private-org/private-name/1.2.3/private-name-1.2.3.pom";
      sha256 = "DD05B8C06A7381DC81D942B293C2DC7F558A7E27DD1CEAE9825F41844DE8B7A6";
    };
    "nix-public/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.pom";
      sha256 = "19889DBDF1B254B2601A5EE645B8147A974644882297684C798AFE5D63D78DFE";
    };
    "nix-public/com/typesafe/config/1.3.2/config-1.3.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.3.2/config-1.3.2-sources.jar";
      sha256 = "65995ABD56D6AA99EE7F46E7CDAAAAC2968554B16B26D38BF67E13706A12CA82";
    };
    "nix-public/com/typesafe/config/1.3.2/config-1.3.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.3.2/config-1.3.2.jar";
      sha256 = "6563D1723F3300BF596F41E40BC03E54986108B5C45D0AC34EBC66D48C2E25A3";
    };
    "nix-public/com/typesafe/config/1.3.2/config-1.3.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.3.2/config-1.3.2.pom";
      sha256 = "07EE48EC393761693CB95E2D1778CCAF3AD680312E94EB27C0059B8E06C98DBA";
    };
    "nix-public/com/typesafe/slick/slick_2.13/3.3.3/slick-3.3.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/slick/slick_2.13/3.3.3/slick_2.13-3.3.3-sources.jar";
      sha256 = "AF7E00288D5992EEAA9D2A684C2BFEB825A532395023CD295E554100F1387380";
    };
    "nix-public/com/typesafe/slick/slick_2.13/3.3.3/slick-3.3.3.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/slick/slick_2.13/3.3.3/slick_2.13-3.3.3.jar";
      sha256 = "CBCCD09BFF7907946135A63E2D1F8D32E5630F3588A258C6B1E8EEDEA142BE68";
    };
    "nix-public/com/typesafe/slick/slick_2.13/3.3.3/slick-3.3.3.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/slick/slick_2.13/3.3.3/slick_2.13-3.3.3.pom";
      sha256 = "873D3EBC991BF1D06F69C503F33E01287FDB66BB584352DEBBF8914ADD0FB0A5";
    };
    "nix-public/com/typesafe/slick/slick_2.13/3.3.3/slick_2.13-3.3.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/slick/slick_2.13/3.3.3/slick_2.13-3.3.3-sources.jar";
      sha256 = "AF7E00288D5992EEAA9D2A684C2BFEB825A532395023CD295E554100F1387380";
    };
    "nix-public/com/typesafe/slick/slick_2.13/3.3.3/slick_2.13-3.3.3.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/slick/slick_2.13/3.3.3/slick_2.13-3.3.3.jar";
      sha256 = "CBCCD09BFF7907946135A63E2D1F8D32E5630F3588A258C6B1E8EEDEA142BE68";
    };
    "nix-public/com/typesafe/slick/slick_2.13/3.3.3/slick_2.13-3.3.3.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/slick/slick_2.13/3.3.3/slick_2.13-3.3.3.pom";
      sha256 = "873D3EBC991BF1D06F69C503F33E01287FDB66BB584352DEBBF8914ADD0FB0A5";
    };
    "nix-public/io/github/java-diff-utils/java-diff-utils-parent/4.15/java-diff-utils-parent-4.15.pom" = {
      url = "https://repo1.maven.org/maven2/io/github/java-diff-utils/java-diff-utils-parent/4.15/java-diff-utils-parent-4.15.pom";
      sha256 = "09E7D44A7CFA19BC6B23CAD14EC0A41F32AE0B597F0E26ACE91916FDC2BB5C82";
    };
    "nix-public/io/github/java-diff-utils/java-diff-utils/4.15/java-diff-utils-4.15-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/github/java-diff-utils/java-diff-utils/4.15/java-diff-utils-4.15-sources.jar";
      sha256 = "85E4ED33A7688BE204D36D48A244CF815C05B54C626C6297EC4CF75BE2AF922F";
    };
    "nix-public/io/github/java-diff-utils/java-diff-utils/4.15/java-diff-utils-4.15.jar" = {
      url = "https://repo1.maven.org/maven2/io/github/java-diff-utils/java-diff-utils/4.15/java-diff-utils-4.15.jar";
      sha256 = "964C69E3A23A892DB2778AE6806AA1D42F81230032BD8E4982DC8620582EE6B7";
    };
    "nix-public/io/github/java-diff-utils/java-diff-utils/4.15/java-diff-utils-4.15.pom" = {
      url = "https://repo1.maven.org/maven2/io/github/java-diff-utils/java-diff-utils/4.15/java-diff-utils-4.15.pom";
      sha256 = "1ADF2A60E862B71AA694A3E8E6A888AA353FAFF5059477EBBFDCABCD3A3FF92E";
    };
    "nix-public/net/java/dev/jna/jna/5.15.0/jna-5.15.0.pom" = {
      url = "https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.15.0/jna-5.15.0.pom";
      sha256 = "276602FF367A4C39155DAECC1E8CB54F4789E5D80DF90A3A8B6603F1DEB59E05";
    };
    "nix-public/org/fusesource/fusesource-pom/1.12/fusesource-pom-1.12.pom" = {
      url = "https://repo1.maven.org/maven2/org/fusesource/fusesource-pom/1.12/fusesource-pom-1.12.pom";
      sha256 = "C40D960DAADCEF7B01C1B1C6657AFBAC4FFFB5E53168F8FCB0B28B84E6FDCCA1";
    };
    "nix-public/org/fusesource/jansi/jansi/2.4.1/jansi-2.4.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/2.4.1/jansi-2.4.1.pom";
      sha256 = "3F98D979A4D3559F8779FBB004B34AE7516AFADF510E11DF7CC3CD073EB1BB3B";
    };
    "nix-public/org/jline/jline-builtins/3.27.1/jline-builtins-3.27.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-builtins/3.27.1/jline-builtins-3.27.1.pom";
      sha256 = "7771F3BF04A1592BB0420D2280FA7718C572591BD4CEEB3CF443CB83C68172AE";
    };
    "nix-public/org/jline/jline-native/3.27.1/jline-native-3.27.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-native/3.27.1/jline-native-3.27.1.pom";
      sha256 = "9FFE28AECC9F546EC9695F2D521F67459B4B36917148C08D16F4556B383D328F";
    };
    "nix-public/org/jline/jline-parent/3.27.1/jline-parent-3.27.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-parent/3.27.1/jline-parent-3.27.1.pom";
      sha256 = "E964FD076C20CE24DDB48DD737A08D6050347005E3E6EEC82FF5EB043D561581";
    };
    "nix-public/org/jline/jline-reader/3.27.1/jline-reader-3.27.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-reader/3.27.1/jline-reader-3.27.1.pom";
      sha256 = "1AE3547D6DF3045AE9339CBDA2571868263BE1B73C7673D17057A505CACF1F08";
    };
    "nix-public/org/jline/jline-style/3.27.1/jline-style-3.27.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-style/3.27.1/jline-style-3.27.1.pom";
      sha256 = "2FD933346D21AB2AB2D04BA360ED33F1B383203D3474CB24D34A6497D6741311";
    };
    "nix-public/org/jline/jline-terminal-jni/3.27.1/jline-terminal-jni-3.27.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-terminal-jni/3.27.1/jline-terminal-jni-3.27.1.pom";
      sha256 = "52448DE3CBF55F80701484CB4A23B58CB1B0D8FEAA86DBDDC321360724369757";
    };
    "nix-public/org/jline/jline-terminal/3.27.1/jline-terminal-3.27.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-terminal/3.27.1/jline-terminal-3.27.1.pom";
      sha256 = "8478E79AA22EA6AF79796443F8ED30FFFA5DC647EB3D2D1860BAC2E23F34D297";
    };
    "nix-public/org/jline/jline/3.27.1/jline-3.27.1-jdk8.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline/3.27.1/jline-3.27.1-jdk8.jar";
      sha256 = "9D165AFF3D714A455DE2E711DC90DF09FDB0A0969A1CD4D52AA72A44CB545DB0";
    };
    "nix-public/org/jline/jline/3.27.1/jline-3.27.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline/3.27.1/jline-3.27.1.pom";
      sha256 = "3F3559376D8F45DEB1A02C8BE7DBFE73C927374DBCAB0F08E977A1079828AD67";
    };
    "nix-public/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2-sources.jar";
      sha256 = "963A6480F46A64013D0F144BA41C6C6E63C4D34B655761717A436492886F3667";
    };
    "nix-public/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.jar";
      sha256 = "CC09AB0B140E0D0496C2165D4B32CE24F4D6446C0A26C5DC77B06BDF99EE8FAE";
    };
    "nix-public/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.pom";
      sha256 = "5B626A99E5734BA8D0C0C8C3FC6258AFA0624F4CE61AE1192247D03C57463DED";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.13/2.0.0/scala-collection-compat-2.0.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.13/2.0.0/scala-collection-compat_2.13-2.0.0-sources.jar";
      sha256 = "B7A7FC8740152744E5BA04AB4A915D4CCF3B6EB8BC8EEB9FF7579A977D58713B";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.13/2.0.0/scala-collection-compat-2.0.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.13/2.0.0/scala-collection-compat_2.13-2.0.0.jar";
      sha256 = "CF44B33A596491B1BFE25080DCE34DA7BF41E407F3E82F7A24A7C07746D9FCAF";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.13/2.0.0/scala-collection-compat-2.0.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.13/2.0.0/scala-collection-compat_2.13-2.0.0.pom";
      sha256 = "6513FA921C3592DF8EFC8C2A05985E8303F9C694A432CC0174616A2F789CE8B3";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.13/2.0.0/scala-collection-compat_2.13-2.0.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.13/2.0.0/scala-collection-compat_2.13-2.0.0-sources.jar";
      sha256 = "B7A7FC8740152744E5BA04AB4A915D4CCF3B6EB8BC8EEB9FF7579A977D58713B";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.13/2.0.0/scala-collection-compat_2.13-2.0.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.13/2.0.0/scala-collection-compat_2.13-2.0.0.jar";
      sha256 = "CF44B33A596491B1BFE25080DCE34DA7BF41E407F3E82F7A24A7C07746D9FCAF";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.13/2.0.0/scala-collection-compat_2.13-2.0.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.13/2.0.0/scala-collection-compat_2.13-2.0.0.pom";
      sha256 = "6513FA921C3592DF8EFC8C2A05985E8303F9C694A432CC0174616A2F789CE8B3";
    };
    "nix-public/org/scala-lang/scala-compiler/2.13.16/scala-compiler-2.13.16-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.16/scala-compiler-2.13.16-sources.jar";
      sha256 = "E922DC2F97D545FDC083F2FCF2915EB00C7647F3770B95489DE0BC9EF7B54A3E";
    };
    "nix-public/org/scala-lang/scala-compiler/2.13.16/scala-compiler-2.13.16.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.16/scala-compiler-2.13.16.jar";
      sha256 = "F59982714591E321BA9C087AF2C8666E2F5FB92B11A0CEF72C2C5E9B342152D3";
    };
    "nix-public/org/scala-lang/scala-compiler/2.13.16/scala-compiler-2.13.16.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.16/scala-compiler-2.13.16.pom";
      sha256 = "954B555B12C22D4EA59175517FDD9578E06E62EBA8727A2073A6596FA7EB06AB";
    };
    "nix-public/org/scala-lang/scala-library/2.12.16/scala-library-2.12.16.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.16/scala-library-2.12.16.pom";
      sha256 = "7252D3628EE8CD1A0B3425F9FA493E9CABFC5F74C13275362006CC92C3CCFD3A";
    };
    "nix-public/org/scala-lang/scala-library/2.13.0/scala-library-2.13.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.0/scala-library-2.13.0.pom";
      sha256 = "5C1271080F49D69BB56BE5030D07482CDAA3F5EC3E7716489B0FC3BD77EB6EBB";
    };
    "nix-public/org/scala-lang/scala-library/2.13.16/scala-library-2.13.16-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.16/scala-library-2.13.16-sources.jar";
      sha256 = "C02EDC324E7DB59C52115214A6EF36E2D78D0A50DFF635EDA4DCEE5502B1DEA5";
    };
    "nix-public/org/scala-lang/scala-library/2.13.16/scala-library-2.13.16.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.16/scala-library-2.13.16.jar";
      sha256 = "1EBB2B6F9E4EB4022497C19B1E1E825019C08514F962AAAC197145F88ED730F1";
    };
    "nix-public/org/scala-lang/scala-library/2.13.16/scala-library-2.13.16.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.16/scala-library-2.13.16.pom";
      sha256 = "B25B72BA96EB30934868D86D307298D24D3AC154D362E7A4EEB37BA51BA86853";
    };
    "nix-public/org/scala-lang/scala-reflect/2.13.16/scala-reflect-2.13.16-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.16/scala-reflect-2.13.16-sources.jar";
      sha256 = "11C15FBF9EE203E262049FDD54D8B8472E1601970FBA655678C237629815117E";
    };
    "nix-public/org/scala-lang/scala-reflect/2.13.16/scala-reflect-2.13.16.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.16/scala-reflect-2.13.16.jar";
      sha256 = "FB49CCD9CAC7464486AB993CDA20A3C1569D8EF26F052E897577AD2A4970FB1D";
    };
    "nix-public/org/scala-lang/scala-reflect/2.13.16/scala-reflect-2.13.16.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.16/scala-reflect-2.13.16.pom";
      sha256 = "66B1833F1EE675AB2AE5F6D55B38DDAD472246CDC092132B8C52D0CF94A31B60";
    };
    "nix-public/org/scala-lang/scala2-sbt-bridge/2.13.16/scala2-sbt-bridge-2.13.16-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala2-sbt-bridge/2.13.16/scala2-sbt-bridge-2.13.16-sources.jar";
      sha256 = "958DC58B891F3EE1C6D8AB22452438A1141CEB16C58386A397FFE4E7DA78AD45";
    };
    "nix-public/org/scala-lang/scala2-sbt-bridge/2.13.16/scala2-sbt-bridge-2.13.16.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala2-sbt-bridge/2.13.16/scala2-sbt-bridge-2.13.16.jar";
      sha256 = "776EF74D8BC1222F4B6E7B5DC5DD1F0ABFC97AB853CB4932292DEE0B32111906";
    };
    "nix-public/org/scala-lang/scala2-sbt-bridge/2.13.16/scala2-sbt-bridge-2.13.16.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala2-sbt-bridge/2.13.16/scala2-sbt-bridge-2.13.16.pom";
      sha256 = "1E514DDBA6DA57565A96CA770678F2831F649AD94D499D185C2D2C638A68E2A2";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-sources.jar";
      sha256 = "C4BC93180A4F0ACEEC3B057A2514ABE04A79F06C174BBED910A2AFB227B79366";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-tests.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-tests.jar";
      sha256 = "FB82F52621D9DDAFB135DFF968A75B5BC08C40BA4BE77B5AB8DEA8711A032D72";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar";
      sha256 = "18C4A0095D5C1DA6B817592E767BB23D29DD2F560AD74DF75FF3961DBDE25B79";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.pom";
      sha256 = "7CD9D7A0B5D93DFD461A148891B43509CF403A9C7F9FB49060D3554DF1C81E1E";
    };
    "nix-public/org/slf4j/slf4j-api/2.0.16/slf4j-api-2.0.16.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/2.0.16/slf4j-api-2.0.16.pom";
      sha256 = "B1A00F5B1C4DBE62B805D65D23911A6F77063889D7CB1E86FE8389D6190473F7";
    };
    "nix-public/org/slf4j/slf4j-bom/2.0.16/slf4j-bom-2.0.16.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-bom/2.0.16/slf4j-bom-2.0.16.pom";
      sha256 = "0566048EC825CDF28758620AF64D9E14AE38A9CD8748DD6FAFA6DF4A4194C279";
    };
    "nix-public/org/slf4j/slf4j-parent/1.7.25/slf4j-parent-1.7.25.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.7.25/slf4j-parent-1.7.25.pom";
      sha256 = "18F5C52120DB036E88D6136F8839C832D074BDDA95C756C6F429249D2DB54AC6";
    };
    "nix-public/org/slf4j/slf4j-parent/2.0.16/slf4j-parent-2.0.16.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/2.0.16/slf4j-parent-2.0.16.pom";
      sha256 = "09A0B4CC814D7274616C9B16D4C0FD9AAF1ECC813334DE5131E547271B1982E5";
    };
    "nix-public/org/slf4j/slf4j-simple/2.0.16/slf4j-simple-2.0.16.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-simple/2.0.16/slf4j-simple-2.0.16.pom";
      sha256 = "CF6C553148E8A77951CFDA131D209481981FD6E2C02A7B48DC6D6605523CDF1C";
    };
    "nix-public/org/sonatype/oss/oss-parent/7/oss-parent-7.pom" = {
      url = "https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/7/oss-parent-7.pom";
      sha256 = "B51F8867C92B6A722499557FC3A1FDEA77BDF9EF574722FE90CE436A29559454";
    };
  };
}