# This file was automatically generated by Sbtix. Do not edit manually.
{
  "versioning" = [{
      "scalaVersion" = "2.13.9";
      "sbtVersion" = "1.7.1";
    }];
  "repos" = {
    "nix-private-demo" = "";
    "nix-public" = "";
  };
  "artifacts" = {
    "nix-private-demo/private-org/private-name/1.2.3/private-name-1.2.3-sources.jar" = {
      url = "http://test:test@localhost:9877/plugin/src/sbt-test/artifacts/private-org/private-name/1.2.3/private-name-1.2.3-sources.jar";
      sha256 = "75E1D3470B31B36C8D497E37BF276D4A03F480CF22763D77456E78D8EF286FEC";
    };
    "nix-private-demo/private-org/private-name/1.2.3/private-name-1.2.3.jar" = {
      url = "http://test:test@localhost:9877/plugin/src/sbt-test/artifacts/private-org/private-name/1.2.3/private-name-1.2.3.jar";
      sha256 = "A5FD38B5D04D2A236B6C75C2C2EDFA40FE06F0B819596E37043197EC9671CF61";
    };
    "nix-private-demo/private-org/private-name/1.2.3/private-name-1.2.3.pom" = {
      url = "http://test:test@localhost:9877/plugin/src/sbt-test/artifacts/private-org/private-name/1.2.3/private-name-1.2.3.pom";
      sha256 = "DD05B8C06A7381DC81D942B293C2DC7F558A7E27DD1CEAE9825F41844DE8B7A6";
    };
    "nix-public/com/typesafe/config/1.3.2/config-1.3.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.3.2/config-1.3.2-javadoc.jar";
      sha256 = "57619C3DC0DC23DC74F0B1E14DEE7C87C5118B6700ECFE7400D2742D091C099F";
    };
    "nix-public/com/typesafe/config/1.3.2/config-1.3.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.3.2/config-1.3.2-sources.jar";
      sha256 = "65995ABD56D6AA99EE7F46E7CDAAAAC2968554B16B26D38BF67E13706A12CA82";
    };
    "nix-public/com/typesafe/config/1.3.2/config-1.3.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.3.2/config-1.3.2.jar";
      sha256 = "6563D1723F3300BF596F41E40BC03E54986108B5C45D0AC34EBC66D48C2E25A3";
    };
    "nix-public/com/typesafe/config/1.3.2/config-1.3.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.3.2/config-1.3.2.pom";
      sha256 = "07EE48EC393761693CB95E2D1778CCAF3AD680312E94EB27C0059B8E06C98DBA";
    };
    "nix-public/com/typesafe/slick/slick_2.13/3.3.3/slick_2.13-3.3.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/slick/slick_2.13/3.3.3/slick_2.13-3.3.3-javadoc.jar";
      sha256 = "3984D2F97BF253728468385AF937C3608FD5FE32C8FF101C4E1C625E69B83C5B";
    };
    "nix-public/com/typesafe/slick/slick_2.13/3.3.3/slick_2.13-3.3.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/slick/slick_2.13/3.3.3/slick_2.13-3.3.3-sources.jar";
      sha256 = "AF7E00288D5992EEAA9D2A684C2BFEB825A532395023CD295E554100F1387380";
    };
    "nix-public/com/typesafe/slick/slick_2.13/3.3.3/slick_2.13-3.3.3.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/slick/slick_2.13/3.3.3/slick_2.13-3.3.3.jar";
      sha256 = "CBCCD09BFF7907946135A63E2D1F8D32E5630F3588A258C6B1E8EEDEA142BE68";
    };
    "nix-public/com/typesafe/slick/slick_2.13/3.3.3/slick_2.13-3.3.3.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/slick/slick_2.13/3.3.3/slick_2.13-3.3.3.pom";
      sha256 = "873D3EBC991BF1D06F69C503F33E01287FDB66BB584352DEBBF8914ADD0FB0A5";
    };
    "nix-public/io/github/java-diff-utils/java-diff-utils-parent/4.12/java-diff-utils-parent-4.12.pom" = {
      url = "https://repo1.maven.org/maven2/io/github/java-diff-utils/java-diff-utils-parent/4.12/java-diff-utils-parent-4.12.pom";
      sha256 = "D811CF9F118CC2CAD130C9427AD55C174D4C0A6F1A00AC1AE1C9BCBEC5C44B19";
    };
    "nix-public/io/github/java-diff-utils/java-diff-utils/4.12/java-diff-utils-4.12-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/io/github/java-diff-utils/java-diff-utils/4.12/java-diff-utils-4.12-javadoc.jar";
      sha256 = "57D249164E7C551F5E76DBBE602296C0BD4D24ABD76391E7A502A63DB64EE493";
    };
    "nix-public/io/github/java-diff-utils/java-diff-utils/4.12/java-diff-utils-4.12-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/github/java-diff-utils/java-diff-utils/4.12/java-diff-utils-4.12-sources.jar";
      sha256 = "FA24217B6EAA115A05D4A8F0003FE913C62716CA2184D2E4F17DE4A7D42A8822";
    };
    "nix-public/io/github/java-diff-utils/java-diff-utils/4.12/java-diff-utils-4.12.jar" = {
      url = "https://repo1.maven.org/maven2/io/github/java-diff-utils/java-diff-utils/4.12/java-diff-utils-4.12.jar";
      sha256 = "9990A2039778F6B4CC94790141C2868864EACEE0620C6C459451121A901CD5B5";
    };
    "nix-public/io/github/java-diff-utils/java-diff-utils/4.12/java-diff-utils-4.12.pom" = {
      url = "https://repo1.maven.org/maven2/io/github/java-diff-utils/java-diff-utils/4.12/java-diff-utils-4.12.pom";
      sha256 = "C26E097EDC8EC6805D1319817D23D4E496CC1015CC55DC5202112D8F6A9165FC";
    };
    "nix-public/net/java/dev/jna/jna/5.9.0/jna-5.9.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.9.0/jna-5.9.0-javadoc.jar";
      sha256 = "9356351C626948BDF893F724331012112437E970B89B326ADEE5BC1264AF41C5";
    };
    "nix-public/net/java/dev/jna/jna/5.9.0/jna-5.9.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.9.0/jna-5.9.0-sources.jar";
      sha256 = "577EE7CA6F762E38C068AB2989B1E9FC687063B39432D9D4417A17C7F2210BA7";
    };
    "nix-public/net/java/dev/jna/jna/5.9.0/jna-5.9.0.jar" = {
      url = "https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.9.0/jna-5.9.0.jar";
      sha256 = "EAFCC780B445434D3C5AE7FA2FB6665DE1A7560D537D2C408A8E80CD14D27161";
    };
    "nix-public/net/java/dev/jna/jna/5.9.0/jna-5.9.0.pom" = {
      url = "https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.9.0/jna-5.9.0.pom";
      sha256 = "6BC8B8459150B59E9598F3DAD9AD245A1EF2150D082581017184EB163E592829";
    };
    "nix-public/org/jline/jline-parent/3.21.0/jline-parent-3.21.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-parent/3.21.0/jline-parent-3.21.0.pom";
      sha256 = "98D561914FF908EC21D8B46BEF89FB7AF824D416DFD32B1BA71FA5D4A4F4C7A0";
    };
    "nix-public/org/jline/jline/3.21.0/jline-3.21.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline/3.21.0/jline-3.21.0-javadoc.jar";
      sha256 = "15876EAF25FAE413E4E3493B533D99F2D50A877C553C5369A2E097C1C50431FE";
    };
    "nix-public/org/jline/jline/3.21.0/jline-3.21.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline/3.21.0/jline-3.21.0-sources.jar";
      sha256 = "9D1F5958A0CFF8F0B1729CD10B3BBE71D2587A0EC9537ECE87CCA45D21BA3DB3";
    };
    "nix-public/org/jline/jline/3.21.0/jline-3.21.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline/3.21.0/jline-3.21.0.jar";
      sha256 = "1E7D63A2BD1C26354CA1987E55469EA4327C4A3845C10D7A7790CA9729C49C02";
    };
    "nix-public/org/jline/jline/3.21.0/jline-3.21.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline/3.21.0/jline-3.21.0.pom";
      sha256 = "0F11A07911F2E0687E120794A67536328B61E866A953CC1EA75B796C0B926C73";
    };
    "nix-public/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2-javadoc.jar";
      sha256 = "D6FDA7686D9B8C7A4A2FDBB7C8E17036D07A090C2C701D6CB0AB58A1812A4003";
    };
    "nix-public/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2-sources.jar";
      sha256 = "963A6480F46A64013D0F144BA41C6C6E63C4D34B655761717A436492886F3667";
    };
    "nix-public/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.jar";
      sha256 = "CC09AB0B140E0D0496C2165D4B32CE24F4D6446C0A26C5DC77B06BDF99EE8FAE";
    };
    "nix-public/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.pom";
      sha256 = "5B626A99E5734BA8D0C0C8C3FC6258AFA0624F4CE61AE1192247D03C57463DED";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.13/2.0.0/scala-collection-compat_2.13-2.0.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.13/2.0.0/scala-collection-compat_2.13-2.0.0-javadoc.jar";
      sha256 = "B807F136E6FBF814E6AB44F431C6C8E8D94AAA99BAFD1D10EAD1863F56E8E8DA";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.13/2.0.0/scala-collection-compat_2.13-2.0.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.13/2.0.0/scala-collection-compat_2.13-2.0.0-sources.jar";
      sha256 = "B7A7FC8740152744E5BA04AB4A915D4CCF3B6EB8BC8EEB9FF7579A977D58713B";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.13/2.0.0/scala-collection-compat_2.13-2.0.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.13/2.0.0/scala-collection-compat_2.13-2.0.0.jar";
      sha256 = "CF44B33A596491B1BFE25080DCE34DA7BF41E407F3E82F7A24A7C07746D9FCAF";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.13/2.0.0/scala-collection-compat_2.13-2.0.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.13/2.0.0/scala-collection-compat_2.13-2.0.0.pom";
      sha256 = "6513FA921C3592DF8EFC8C2A05985E8303F9C694A432CC0174616A2F789CE8B3";
    };
    "nix-public/org/scala-lang/scala-compiler/2.13.9/scala-compiler-2.13.9-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.9/scala-compiler-2.13.9-javadoc.jar";
      sha256 = "64F873EDD659B9311D67717470ADE6D33BCE3DFCAA4FA02D3AF784239E6C667D";
    };
    "nix-public/org/scala-lang/scala-compiler/2.13.9/scala-compiler-2.13.9-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.9/scala-compiler-2.13.9-sources.jar";
      sha256 = "6834462EB069831F58A8C078920C0AC37D3795106DABDF31A7C7AD826E18970B";
    };
    "nix-public/org/scala-lang/scala-compiler/2.13.9/scala-compiler-2.13.9.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.9/scala-compiler-2.13.9.jar";
      sha256 = "7F8DAAA443A8C23F391F8A5E65532942065162E0BBE7451D290BDD100C419C9C";
    };
    "nix-public/org/scala-lang/scala-compiler/2.13.9/scala-compiler-2.13.9.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.9/scala-compiler-2.13.9.pom";
      sha256 = "B44798A67FACCAF349D104FE3BC670111C983E85BD19CA8300816A8389F61183";
    };
    "nix-public/org/scala-lang/scala-library/2.12.16/scala-library-2.12.16-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.16/scala-library-2.12.16-javadoc.jar";
      sha256 = "8B78618854A5E99E3584211F3058353BF8EBBC4F755BE608717B639AD4F8E007";
    };
    "nix-public/org/scala-lang/scala-library/2.12.16/scala-library-2.12.16-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.16/scala-library-2.12.16-sources.jar";
      sha256 = "82BA9D76BC6AB949809DF01C5B4F278D5F4C624653264A451895CCF20A9E4894";
    };
    "nix-public/org/scala-lang/scala-library/2.12.16/scala-library-2.12.16.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.16/scala-library-2.12.16.jar";
      sha256 = "55D371AA1568BB00A6ECD3F18946692BE61CB975F6CB6D717D884BB62A68C159";
    };
    "nix-public/org/scala-lang/scala-library/2.12.16/scala-library-2.12.16.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.16/scala-library-2.12.16.pom";
      sha256 = "7252D3628EE8CD1A0B3425F9FA493E9CABFC5F74C13275362006CC92C3CCFD3A";
    };
    "nix-public/org/scala-lang/scala-library/2.13.0/scala-library-2.13.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.0/scala-library-2.13.0-javadoc.jar";
      sha256 = "54C815B994BCD1CA1952735FA28DBD82D411622F25DB559786020DC9BB50CC43";
    };
    "nix-public/org/scala-lang/scala-library/2.13.0/scala-library-2.13.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.0/scala-library-2.13.0-sources.jar";
      sha256 = "4CD39B6E9EC0C5B28BF0B62A841E7AAF16D5728D4E014081A64E5ECA0BF6B722";
    };
    "nix-public/org/scala-lang/scala-library/2.13.0/scala-library-2.13.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.0/scala-library-2.13.0.jar";
      sha256 = "BD3B2FA8B922295CCF1537ABA1850D455F82003C10484DF509D29FF177CC1EDC";
    };
    "nix-public/org/scala-lang/scala-library/2.13.0/scala-library-2.13.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.0/scala-library-2.13.0.pom";
      sha256 = "5C1271080F49D69BB56BE5030D07482CDAA3F5EC3E7716489B0FC3BD77EB6EBB";
    };
    "nix-public/org/scala-lang/scala-library/2.13.9/scala-library-2.13.9-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.9/scala-library-2.13.9-javadoc.jar";
      sha256 = "60581383D9433042E0A0306DBF65E5E459C1FA33D16D14060BA01673927679D7";
    };
    "nix-public/org/scala-lang/scala-library/2.13.9/scala-library-2.13.9-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.9/scala-library-2.13.9-sources.jar";
      sha256 = "09F1E2A3BEE18A285C02779C48719A36F7E4005A2CCC4002982FF0620F92EE59";
    };
    "nix-public/org/scala-lang/scala-library/2.13.9/scala-library-2.13.9.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.9/scala-library-2.13.9.jar";
      sha256 = "317E0CD80AA8B0CE9E98D154053D9A0F5ACC63854B68CA5522D3E017C68DC8E5";
    };
    "nix-public/org/scala-lang/scala-library/2.13.9/scala-library-2.13.9.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.9/scala-library-2.13.9.pom";
      sha256 = "C8095F5869C5358FB177184866A7759C207BE76F4A38A1523F95AB52E8B0E6CE";
    };
    "nix-public/org/scala-lang/scala-reflect/2.13.9/scala-reflect-2.13.9-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.9/scala-reflect-2.13.9-javadoc.jar";
      sha256 = "5BB900F151B2849BF81DBB4D598DA10DE834412F2FC90D6B21FAA7B8C187CC6F";
    };
    "nix-public/org/scala-lang/scala-reflect/2.13.9/scala-reflect-2.13.9-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.9/scala-reflect-2.13.9-sources.jar";
      sha256 = "3B466DF0FAC42475954CABA7B025F0EC3733F318E72400EFB8CC82C31C7D1A8E";
    };
    "nix-public/org/scala-lang/scala-reflect/2.13.9/scala-reflect-2.13.9.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.9/scala-reflect-2.13.9.jar";
      sha256 = "23BAD48A23465B4C91E1FEB6773CA6361AC2E0053020B3E311C25A2AF1D476C6";
    };
    "nix-public/org/scala-lang/scala-reflect/2.13.9/scala-reflect-2.13.9.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.9/scala-reflect-2.13.9.pom";
      sha256 = "E28D8E3FD9CF4B4B7D10BAEDA99543DB414BFDBC4D51F269FA3ED674D5A8B6F4";
    };
    "nix-public/org/scala-sbt/compiler-bridge_2.13/1.7.1/compiler-bridge_2.13-1.7.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.13/1.7.1/compiler-bridge_2.13-1.7.1-javadoc.jar";
      sha256 = "34D269C9B037ED1F867D7B2E2BE466A2E04203206A22ED06D0B968114B584EE6";
    };
    "nix-public/org/scala-sbt/compiler-bridge_2.13/1.7.1/compiler-bridge_2.13-1.7.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.13/1.7.1/compiler-bridge_2.13-1.7.1-sources.jar";
      sha256 = "36113AA52D9834B98F9A7D79A86409A3DD08C4B7DE66D5836D9D25127159068E";
    };
    "nix-public/org/scala-sbt/compiler-bridge_2.13/1.7.1/compiler-bridge_2.13-1.7.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.13/1.7.1/compiler-bridge_2.13-1.7.1.jar";
      sha256 = "6F50CBA2630FC39F1FB3EFA186DF81076D31110719DA2337938915D88C7B4C65";
    };
    "nix-public/org/scala-sbt/compiler-bridge_2.13/1.7.1/compiler-bridge_2.13-1.7.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.13/1.7.1/compiler-bridge_2.13-1.7.1.pom";
      sha256 = "A1DF8099B4CE298B43362658838332B6E289287E3611F375E4D135D9659AC150";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.7.1/compiler-interface-1.7.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.7.1/compiler-interface-1.7.1-javadoc.jar";
      sha256 = "D1F22D41CB5E07B34F606408E13E4EC5F1923E92352BE1BE7A4F5701703F554B";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.7.1/compiler-interface-1.7.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.7.1/compiler-interface-1.7.1-sources.jar";
      sha256 = "AAD5B442CC1BAFEEE328AE08F9E0656A91F4A9BCD345D28D64FDB6A927474419";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.7.1/compiler-interface-1.7.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.7.1/compiler-interface-1.7.1.jar";
      sha256 = "E31993FA3C7701C6C0D0C4461DA3B24637D1B8DB55E4ED07ECE23022962F6080";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.7.1/compiler-interface-1.7.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.7.1/compiler-interface-1.7.1.pom";
      sha256 = "8D7E6B42C5C23BF97AEDC974FB34D70468D6D21FAFC201A95A77260B732E27CB";
    };
    "nix-public/org/scala-sbt/util-interface/1.7.0/util-interface-1.7.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.7.0/util-interface-1.7.0-javadoc.jar";
      sha256 = "68B7EA9E567BB555B569FD4C833284DC974BA00F207567C344BE50077E69E712";
    };
    "nix-public/org/scala-sbt/util-interface/1.7.0/util-interface-1.7.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.7.0/util-interface-1.7.0-sources.jar";
      sha256 = "0A4879E61956E7F7986EDAECE9D947A87BB5C0DAF8FBA345F930775C7A7C1A85";
    };
    "nix-public/org/scala-sbt/util-interface/1.7.0/util-interface-1.7.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.7.0/util-interface-1.7.0.jar";
      sha256 = "B990374326EBFE27AEAE4D5BDA9AB7BD373025348629CF8FD8750FF3E2663772";
    };
    "nix-public/org/scala-sbt/util-interface/1.7.0/util-interface-1.7.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.7.0/util-interface-1.7.0.pom";
      sha256 = "8C8C200219072F9DFE98F376EE55A2F2B89CFFF33CBF2C0D4E1F6E31CF9E5180";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-javadoc.jar";
      sha256 = "8DC4B97B764D6C5B732479936C6CA28DFE9480C8A9B67E4B26CF95C8C64D77BD";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-sources.jar";
      sha256 = "C4BC93180A4F0ACEEC3B057A2514ABE04A79F06C174BBED910A2AFB227B79366";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-tests.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-tests.jar";
      sha256 = "FB82F52621D9DDAFB135DFF968A75B5BC08C40BA4BE77B5AB8DEA8711A032D72";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar";
      sha256 = "18C4A0095D5C1DA6B817592E767BB23D29DD2F560AD74DF75FF3961DBDE25B79";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.pom";
      sha256 = "7CD9D7A0B5D93DFD461A148891B43509CF403A9C7F9FB49060D3554DF1C81E1E";
    };
    "nix-public/org/slf4j/slf4j-parent/1.7.25/slf4j-parent-1.7.25.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.7.25/slf4j-parent-1.7.25.pom";
      sha256 = "18F5C52120DB036E88D6136F8839C832D074BDDA95C756C6F429249D2DB54AC6";
    };
    "nix-public/org/sonatype/oss/oss-parent/9/oss-parent-9.pom" = {
      url = "https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom";
      sha256 = "FB40265F982548212FF82E362E59732B2187EC6F0D80182885C14EF1F982827A";
    };
  };
}
