# This file was automatically generated by Sbtix. Do not edit manually.
{
  "versioning" = [{
      "scalaVersion" = "2.12.20";
      "sbtVersion" = "1.10.7";
    }];
  "repos" = {
    "nix-artima-maven" = "[organization]/[module]/[revision]/[artifact]-[revision](-[classifier]).[ext]";
    "nix-public" = "";
    "nix-sbt-plugin-releases" = "[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]";
  };

  "artifacts" = {
    "nix-public/com/github/eldis/tool-launcher/0.2.2/tool-launcher-0.2.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/eldis/tool-launcher/0.2.2/tool-launcher-0.2.2-sources.jar";
      sha256 = "BB242A115302FDD8A9DB37D702C470D7105CFB477E0DBBF35A0E607A5F581D61";
    };
    "nix-public/com/github/eldis/tool-launcher/0.2.2/tool-launcher-0.2.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/eldis/tool-launcher/0.2.2/tool-launcher-0.2.2.jar";
      sha256 = "4301389ED6EFFB3D8363F0B479B90A9CB787D8E265EB12E74CDB69D1AFD601DD";
    };
    "nix-public/com/github/eldis/tool-launcher/0.2.2/tool-launcher-0.2.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/github/eldis/tool-launcher/0.2.2/tool-launcher-0.2.2.pom";
      sha256 = "C0791A83C22AD1B5D2ED09B90DD8F1C23165D1621CF4D7980C37E5831B9EBF46";
    };
    "nix-public/com/github/sbt/sbt-native-packager_2.12_1.0/1.11.0/sbt-native-packager-1.11.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/sbt/sbt-native-packager_2.12_1.0/1.11.0/sbt-native-packager_2.12_1.0-1.11.0-sources.jar";
      sha256 = "AF8DBF59A1421DCAC1F817EF38674FB9F8CE56061E6B413D7FA48E7BC78909D3";
    };
    "nix-public/com/github/sbt/sbt-native-packager_2.12_1.0/1.11.0/sbt-native-packager-1.11.0.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/sbt/sbt-native-packager_2.12_1.0/1.11.0/sbt-native-packager_2.12_1.0-1.11.0.jar";
      sha256 = "D8D418EC61A77E70A8339469343A34BDEBD74FAE12764FF06DB0E680EC549D8E";
    };
    "nix-public/com/github/sbt/sbt-native-packager_2.12_1.0/1.11.0/sbt-native-packager-1.11.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/github/sbt/sbt-native-packager_2.12_1.0/1.11.0/sbt-native-packager_2.12_1.0-1.11.0.pom";
      sha256 = "4A1CF1278FB47C173A087F3CD939C9131E172543972832169DB36F60A80CBD0A";
    };
    "nix-public/com/github/sbt/sbt-native-packager_2.12_1.0/1.11.0/sbt-native-packager_2.12_1.0-1.11.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/sbt/sbt-native-packager_2.12_1.0/1.11.0/sbt-native-packager_2.12_1.0-1.11.0-sources.jar";
      sha256 = "AF8DBF59A1421DCAC1F817EF38674FB9F8CE56061E6B413D7FA48E7BC78909D3";
    };
    "nix-public/com/github/sbt/sbt-native-packager_2.12_1.0/1.11.0/sbt-native-packager_2.12_1.0-1.11.0.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/sbt/sbt-native-packager_2.12_1.0/1.11.0/sbt-native-packager_2.12_1.0-1.11.0.jar";
      sha256 = "D8D418EC61A77E70A8339469343A34BDEBD74FAE12764FF06DB0E680EC549D8E";
    };
    "nix-public/com/github/sbt/sbt-native-packager_2.12_1.0/1.11.0/sbt-native-packager_2.12_1.0-1.11.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/github/sbt/sbt-native-packager_2.12_1.0/1.11.0/sbt-native-packager_2.12_1.0-1.11.0.pom";
      sha256 = "4A1CF1278FB47C173A087F3CD939C9131E172543972832169DB36F60A80CBD0A";
    };
    "nix-public/com/swoval/file-tree-views/2.1.12/file-tree-views-2.1.12-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/swoval/file-tree-views/2.1.12/file-tree-views-2.1.12-sources.jar";
      sha256 = "9CB6411980A3A2D5AE372568B3D201CA47A850227EF7F87A8CB5AD51E2F1F8D5";
    };
    "nix-public/com/swoval/file-tree-views/2.1.12/file-tree-views-2.1.12.jar" = {
      url = "https://repo1.maven.org/maven2/com/swoval/file-tree-views/2.1.12/file-tree-views-2.1.12.jar";
      sha256 = "FD7373889B7A92CF3E97DB36C920BA272AEC158A9387B3259FCA9F2DFAEDA914";
    };
    "nix-public/com/swoval/file-tree-views/2.1.12/file-tree-views-2.1.12.pom" = {
      url = "https://repo1.maven.org/maven2/com/swoval/file-tree-views/2.1.12/file-tree-views-2.1.12.pom";
      sha256 = "EDD270DC776D1D85DD300E415CFF9E0609757D7AFEB223A6B187BAD5B0ABE746";
    };
    "nix-public/commons-codec/commons-codec/1.17.1/commons-codec-1.17.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.17.1/commons-codec-1.17.1-sources.jar";
      sha256 = "2283AFF7F425DFF23EBDB7A8FC0F03AE21B4CED7A43AACBA47CEDAE126DC5D4A";
    };
    "nix-public/commons-codec/commons-codec/1.17.1/commons-codec-1.17.1-tests.jar" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.17.1/commons-codec-1.17.1-tests.jar";
      sha256 = "26640223A63A514D3099AA94DC1CE3140A52AE32E0FA4932D40788732C437933";
    };
    "nix-public/commons-codec/commons-codec/1.17.1/commons-codec-1.17.1.jar" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.17.1/commons-codec-1.17.1.jar";
      sha256 = "F9F6CB103F2DDC3C99A9D80ADA2AE7BF0685111FD6BFFCCB72033D1DA4E6FF23";
    };
    "nix-public/commons-codec/commons-codec/1.17.1/commons-codec-1.17.1.pom" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.17.1/commons-codec-1.17.1.pom";
      sha256 = "7FA0DB4D8150DAF932958B8AEA89EE24ABB4D18E2316A5DE535278FC131512A0";
    };
    "nix-public/commons-io/commons-io/2.16.1/commons-io-2.16.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/commons-io/commons-io/2.16.1/commons-io-2.16.1-sources.jar";
      sha256 = "FCFE84E39FB44E38A0EA0AB0815B53ADEA6FFF89C7B72535BC42495F400CB9A1";
    };
    "nix-public/commons-io/commons-io/2.16.1/commons-io-2.16.1-tests.jar" = {
      url = "https://repo1.maven.org/maven2/commons-io/commons-io/2.16.1/commons-io-2.16.1-tests.jar";
      sha256 = "12B99F1989D29DBBC3638FF9EEE855963F6B04262D4150C0FE49981FDBB37E14";
    };
    "nix-public/commons-io/commons-io/2.16.1/commons-io-2.16.1.jar" = {
      url = "https://repo1.maven.org/maven2/commons-io/commons-io/2.16.1/commons-io-2.16.1.jar";
      sha256 = "F41F7BAACD716896447ACE9758621F62C1C6B0A91D89ACEE488DA26FC477C84F";
    };
    "nix-public/commons-io/commons-io/2.16.1/commons-io-2.16.1.pom" = {
      url = "https://repo1.maven.org/maven2/commons-io/commons-io/2.16.1/commons-io-2.16.1.pom";
      sha256 = "5777D292251C7895C04A4C57015683EC3B353A12486C9B3E7178E9B0B3C38FFF";
    };
    "nix-public/org/apache/ant/ant-launcher/1.10.15/ant-launcher-1.10.15-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/ant/ant-launcher/1.10.15/ant-launcher-1.10.15-sources.jar";
      sha256 = "AB774B88172F80BEB0E11E697ADBAB13E8436B4C959BEF51D5DBA44F1D192D72";
    };
    "nix-public/org/apache/ant/ant-launcher/1.10.15/ant-launcher-1.10.15.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/ant/ant-launcher/1.10.15/ant-launcher-1.10.15.jar";
      sha256 = "5C8551990307A032336D98DDAED549A39A689F07D4D4C6B950601BF22B3D6A1B";
    };
    "nix-public/org/apache/ant/ant-launcher/1.10.15/ant-launcher-1.10.15.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/ant/ant-launcher/1.10.15/ant-launcher-1.10.15.pom";
      sha256 = "79AF842A2979DC5FE0022BC073C498810EEAD83BC6283EEDF34DC4DFE30DAC95";
    };
    "nix-public/org/apache/ant/ant-parent/1.10.15/ant-parent-1.10.15.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/ant/ant-parent/1.10.15/ant-parent-1.10.15.pom";
      sha256 = "49884F1873C5107CC237F4285C4477479BB0804BF0737394801B08D75E2BBEB0";
    };
    "nix-public/org/apache/ant/ant/1.10.15/ant-1.10.15-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/ant/ant/1.10.15/ant-1.10.15-sources.jar";
      sha256 = "817EBF06C0A01D5D59CAE996815B154B7B7172D40D75304F39AB107E8133C0D6";
    };
    "nix-public/org/apache/ant/ant/1.10.15/ant-1.10.15.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/ant/ant/1.10.15/ant-1.10.15.jar";
      sha256 = "763ACDA4A69588C9EA8817A952851FF0C2FC4BFFA1D081C2565DC407F29D5794";
    };
    "nix-public/org/apache/ant/ant/1.10.15/ant-1.10.15.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/ant/ant/1.10.15/ant-1.10.15.pom";
      sha256 = "4780E61E87816EEE1F21D184EC997B65F93DB5F4B9042C178ADB29E23E7425D6";
    };
    "nix-public/org/apache/apache/31/apache-31.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/apache/31/apache-31.pom";
      sha256 = "555D0C9EAA69C042AFF924927B9381E8F8174136D355EEAD445224452E6291CC";
    };
    "nix-public/org/apache/apache/32/apache-32.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/apache/32/apache-32.pom";
      sha256 = "CFD872C0EC27F53AE68F43DBC0FECDED8ADD773079A53AFBD390E407B42CE72F";
    };
    "nix-public/org/apache/apache/33/apache-33.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/apache/33/apache-33.pom";
      sha256 = "D78BD8524C5F8380A190A6525686629A95DFE512DF21111383A6D8C0923A4415";
    };
    "nix-public/org/apache/commons/commons-compress/1.27.1/commons-compress-1.27.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.27.1/commons-compress-1.27.1-sources.jar";
      sha256 = "90839CE19B8AFB8EE50DB75C84AA7555EBC054BA1BD43FDB2202CBF094C77F81";
    };
    "nix-public/org/apache/commons/commons-compress/1.27.1/commons-compress-1.27.1-tests.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.27.1/commons-compress-1.27.1-tests.jar";
      sha256 = "B610A355E3FA06C83CB0928256B567A24208D73AD5C9F00F0DD102142B938954";
    };
    "nix-public/org/apache/commons/commons-compress/1.27.1/commons-compress-1.27.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.27.1/commons-compress-1.27.1.jar";
      sha256 = "293D80F54B536B74095DCD7EA3CF0A29BBFC3402519281332495F4420D370D16";
    };
    "nix-public/org/apache/commons/commons-compress/1.27.1/commons-compress-1.27.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.27.1/commons-compress-1.27.1.pom";
      sha256 = "DF8CC1A8387D4CE842363B7209FDC6D35DF9763839FD3FCAB558A0F83F9D841C";
    };
    "nix-public/org/apache/commons/commons-lang3/3.16.0/commons-lang3-3.16.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.16.0/commons-lang3-3.16.0-sources.jar";
      sha256 = "268058F1CE33558DA48F07B5F5DAE4AE6433357BF07E1BBD0F1D864ADDA1269C";
    };
    "nix-public/org/apache/commons/commons-lang3/3.16.0/commons-lang3-3.16.0-tests.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.16.0/commons-lang3-3.16.0-tests.jar";
      sha256 = "57AAD0690B04F53C45A319FA8D935AB0EEA29F91683BB8536E4C3A417D8FAD36";
    };
    "nix-public/org/apache/commons/commons-lang3/3.16.0/commons-lang3-3.16.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.16.0/commons-lang3-3.16.0.jar";
      sha256 = "08709DD74D602B705CE4017D26544210056A4BA583D5B20C09373406FE7A00F8";
    };
    "nix-public/org/apache/commons/commons-lang3/3.16.0/commons-lang3-3.16.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.16.0/commons-lang3-3.16.0.pom";
      sha256 = "E280383956C2E72C1DEB3A307B3B75F05EE43649B7D43F0215F7B6C7B15EEA2C";
    };
    "nix-public/org/apache/commons/commons-parent/69/commons-parent-69.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-parent/69/commons-parent-69.pom";
      sha256 = "D50DA9C39BDCA823D618D1B4A03B73F196497FCB8616FD0DA727C8623592A9BB";
    };
    "nix-public/org/apache/commons/commons-parent/71/commons-parent-71.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-parent/71/commons-parent-71.pom";
      sha256 = "95B7BE70F316AE4CA22F6FBDD08DE2182E87CD874A650DE7C3D3386A747A82A3";
    };
    "nix-public/org/apache/commons/commons-parent/72/commons-parent-72.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-parent/72/commons-parent-72.pom";
      sha256 = "4345DEBFC767B1AEAC68ABDD72FC67D18B521D4B390372A11B63FF0C586B2320";
    };
    "nix-public/org/junit/junit-bom/5.10.2/junit-bom-5.10.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/junit/junit-bom/5.10.2/junit-bom-5.10.2.pom";
      sha256 = "169DD904A4B0F6520CFFE658CC62292BFE9F3C14A989FA92120724CDE43A9968";
    };
    "nix-public/org/junit/junit-bom/5.11.0-M2/junit-bom-5.11.0-M2.pom" = {
      url = "https://repo1.maven.org/maven2/org/junit/junit-bom/5.11.0-M2/junit-bom-5.11.0-M2.pom";
      sha256 = "4A3FFC4A4EDCFEC2CB5D619922706A9407161798571939F854DFDA73E4E17CC8";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators-1.1.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2-sources.jar";
      sha256 = "8FBE3FA9E748F24AA6D6868C0C2BE30D41A02D20428ED5429BB57A897CB756E3";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators-1.1.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2.jar";
      sha256 = "24985EB43E295A9DD77905ADA307A850CA25ACF819CDB579C093FC6987B0DBC2";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators-1.1.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2.pom";
      sha256 = "A5500678F39B9B8C962A8FEE98359E9E2F2A4E5D434F3501762B30188642A2F5";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2-sources.jar";
      sha256 = "8FBE3FA9E748F24AA6D6868C0C2BE30D41A02D20428ED5429BB57A897CB756E3";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2.jar";
      sha256 = "24985EB43E295A9DD77905ADA307A850CA25ACF819CDB579C093FC6987B0DBC2";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2.pom";
      sha256 = "A5500678F39B9B8C962A8FEE98359E9E2F2A4E5D434F3501762B30188642A2F5";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.2.0/scala-xml-2.2.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.2.0/scala-xml_2.12-2.2.0-sources.jar";
      sha256 = "975A70A8CC0EFF1AD1A495A60B60B51A973607CF362EFB00F0C1E4565B77FF7C";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.2.0/scala-xml-2.2.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.2.0/scala-xml_2.12-2.2.0.jar";
      sha256 = "FD92F78B7ACFEA72999ACEBA5B377A000F42F9296D3D98224C9B1C471815582F";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.2.0/scala-xml-2.2.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.2.0/scala-xml_2.12-2.2.0.pom";
      sha256 = "81B0510AB4A86724912246E0E18F3988A7086BDE716D819CA7F937474BAC34AC";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.2.0/scala-xml_2.12-2.2.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.2.0/scala-xml_2.12-2.2.0-sources.jar";
      sha256 = "975A70A8CC0EFF1AD1A495A60B60B51A973607CF362EFB00F0C1E4565B77FF7C";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.2.0/scala-xml_2.12-2.2.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.2.0/scala-xml_2.12-2.2.0.jar";
      sha256 = "FD92F78B7ACFEA72999ACEBA5B377A000F42F9296D3D98224C9B1C471815582F";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.2.0/scala-xml_2.12-2.2.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.2.0/scala-xml_2.12-2.2.0.pom";
      sha256 = "81B0510AB4A86724912246E0E18F3988A7086BDE716D819CA7F937474BAC34AC";
    };
    "nix-public/org/scala-lang/scala-library/2.12.18/scala-library-2.12.18-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.18/scala-library-2.12.18-sources.jar";
      sha256 = "A34DB9AB4B38C57F998E8F671B33762E2D6C3E39B8ABF6FB8660A417447FA449";
    };
    "nix-public/org/scala-lang/scala-library/2.12.18/scala-library-2.12.18.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.18/scala-library-2.12.18.jar";
      sha256 = "E51E6636C003359E106BEA4AD99DEF70E613C290190C8C84F10F9560DD5B00AE";
    };
    "nix-public/org/scala-lang/scala-library/2.12.18/scala-library-2.12.18.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.18/scala-library-2.12.18.pom";
      sha256 = "C7BCAE55EB71211DCB3305FD5EAFF1ADD551C53A8B6173C1C02D800C6EACF097";
    };
    "nix-public/org/scala-lang/scala-library/2.12.20/scala-library-2.12.20-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.20/scala-library-2.12.20-sources.jar";
      sha256 = "C64CC0D241CC7515240D55AAC05213C8C518940A1CCF229C90B8F43BCF3C38EE";
    };
    "nix-public/org/scala-lang/scala-library/2.12.20/scala-library-2.12.20.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.20/scala-library-2.12.20.jar";
      sha256 = "4D8A8F984CCE31A329A24F10B0BF336F042CB62AEB435290A1B20243154CFCCB";
    };
    "nix-public/org/scala-lang/scala-library/2.12.20/scala-library-2.12.20.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.20/scala-library-2.12.20.pom";
      sha256 = "94C315B4C51A4C8D0A33F177E160DDAD63B68595FEB3997FA25791C5A14A03C9";
    };
    "nix-public/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8-sources.jar";
      sha256 = "11482BCB49B2E47BAEE89C3B1AE10C6A40B89E2FBB0DA2A423E062F444E13492";
    };
    "nix-public/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.jar";
      sha256 = "321FB55685635C931EBA4BC0D7668349DA3F2C09AEE2DE93A70566066FF25C28";
    };
    "nix-public/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.pom";
      sha256 = "22E81EE9D5349BA0E897ADB5C7FCEC25656C9E0B7B86C3E93E9A7AF360481C0D";
    };
    "nix-public/org/scala-sbt/io_2.12/1.10.4/io-1.10.4-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/io_2.12/1.10.4/io_2.12-1.10.4-sources.jar";
      sha256 = "CC0D78158318ED92A2AC65A0C391EB2BED2A1063421B40297984905B6C47887F";
    };
    "nix-public/org/scala-sbt/io_2.12/1.10.4/io-1.10.4.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/io_2.12/1.10.4/io_2.12-1.10.4.jar";
      sha256 = "1F5928762A88EE222A6DA8D0C165FA389C8BC32516C967EA36C47E244141093C";
    };
    "nix-public/org/scala-sbt/io_2.12/1.10.4/io-1.10.4.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/io_2.12/1.10.4/io_2.12-1.10.4.pom";
      sha256 = "FCDCD693367D79A1C727B54591CCB0592EEF81D88754537A39342FECB280C001";
    };
    "nix-public/org/scala-sbt/io_2.12/1.10.4/io_2.12-1.10.4-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/io_2.12/1.10.4/io_2.12-1.10.4-sources.jar";
      sha256 = "CC0D78158318ED92A2AC65A0C391EB2BED2A1063421B40297984905B6C47887F";
    };
    "nix-public/org/scala-sbt/io_2.12/1.10.4/io_2.12-1.10.4.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/io_2.12/1.10.4/io_2.12-1.10.4.jar";
      sha256 = "1F5928762A88EE222A6DA8D0C165FA389C8BC32516C967EA36C47E244141093C";
    };
    "nix-public/org/scala-sbt/io_2.12/1.10.4/io_2.12-1.10.4.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/io_2.12/1.10.4/io_2.12-1.10.4.pom";
      sha256 = "FCDCD693367D79A1C727B54591CCB0592EEF81D88754537A39342FECB280C001";
    };
  };
}