# This file was automatically generated by Sbtix. Do not edit manually.
{
  "versioning" = [{
      "scalaVersion" = "2.13.18";
      "sbtVersion" = "1.12.11";
    }];
  "repos" = {
    "nix-artima-maven" = "[organization]/[module]/[revision]/[artifact]-[revision](-[classifier]).[ext]";
    "nix-public" = "";
    "nix-sbt-plugin-releases" = "[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]";
    "nix-typesafe-alt-ivy-releases" = "[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]";
  };

  "artifacts" = {
    "nix-public/com/eed3si9n/jarjar/jarjar/1.13.1/jarjar-1.13.1.jar" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/jarjar/jarjar/1.13.1/jarjar-1.13.1.jar";
      sha256 = "6B783297547E86DFCD89AD2308105B13302D6CA5601AB8D9BCC04BE004396A13";
    };
    "nix-public/com/eed3si9n/jarjar/jarjar/1.13.1/jarjar-1.13.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/jarjar/jarjar/1.13.1/jarjar-1.13.1.pom";
      sha256 = "AD735848F8DF9CCF2A5781C13784BA47E49587A8E4344C21757B189D46A19211";
    };
    "nix-public/com/eed3si9n/jarjarabrams/jarjar-abrams-core_2.12/1.13.1/jarjar-abrams-core-1.13.1.jar" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/jarjarabrams/jarjar-abrams-core_2.12/1.13.1/jarjar-abrams-core_2.12-1.13.1.jar";
      sha256 = "70F2E75A455B358C1368EA66940646EE2560783951421E7DE66223B8682A812B";
    };
    "nix-public/com/eed3si9n/jarjarabrams/jarjar-abrams-core_2.12/1.13.1/jarjar-abrams-core-1.13.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/jarjarabrams/jarjar-abrams-core_2.12/1.13.1/jarjar-abrams-core_2.12-1.13.1.pom";
      sha256 = "EA44DD1924FE54ABF0C3CC92532A39E1D4542BCC937A9CD24641CA5C3AB0250E";
    };
    "nix-public/com/eed3si9n/jarjarabrams/jarjar-abrams-core_2.12/1.13.1/jarjar-abrams-core_2.12-1.13.1.jar" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/jarjarabrams/jarjar-abrams-core_2.12/1.13.1/jarjar-abrams-core_2.12-1.13.1.jar";
      sha256 = "70F2E75A455B358C1368EA66940646EE2560783951421E7DE66223B8682A812B";
    };
    "nix-public/com/eed3si9n/jarjarabrams/jarjar-abrams-core_2.12/1.13.1/jarjar-abrams-core_2.12-1.13.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/jarjarabrams/jarjar-abrams-core_2.12/1.13.1/jarjar-abrams-core_2.12-1.13.1.pom";
      sha256 = "EA44DD1924FE54ABF0C3CC92532A39E1D4542BCC937A9CD24641CA5C3AB0250E";
    };
    "nix-public/com/eed3si9n/sbt-assembly_2.12_1.0/2.1.5/sbt-assembly-2.1.5.jar" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/sbt-assembly_2.12_1.0/2.1.5/sbt-assembly_2.12_1.0-2.1.5.jar";
      sha256 = "D4A88B3383DAAE4EA256261A73CD7F463A9BC33629EA713FAFAAF6977824ED71";
    };
    "nix-public/com/eed3si9n/sbt-assembly_2.12_1.0/2.1.5/sbt-assembly-2.1.5.pom" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/sbt-assembly_2.12_1.0/2.1.5/sbt-assembly_2.12_1.0-2.1.5.pom";
      sha256 = "77D23AA7BCB2967B53A9427CB8677BADEC912084409D6E0ABC94A9D21887A90C";
    };
    "nix-public/com/eed3si9n/sbt-assembly_2.12_1.0/2.1.5/sbt-assembly_2.12_1.0-2.1.5.jar" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/sbt-assembly_2.12_1.0/2.1.5/sbt-assembly_2.12_1.0-2.1.5.jar";
      sha256 = "D4A88B3383DAAE4EA256261A73CD7F463A9BC33629EA713FAFAAF6977824ED71";
    };
    "nix-public/com/eed3si9n/sbt-assembly_2.12_1.0/2.1.5/sbt-assembly_2.12_1.0-2.1.5.pom" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/sbt-assembly_2.12_1.0/2.1.5/sbt-assembly_2.12_1.0-2.1.5.pom";
      sha256 = "77D23AA7BCB2967B53A9427CB8677BADEC912084409D6E0ABC94A9D21887A90C";
    };
    "nix-public/com/github/eldis/tool-launcher/0.2.2/tool-launcher-0.2.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/eldis/tool-launcher/0.2.2/tool-launcher-0.2.2-sources.jar";
      sha256 = "BB242A115302FDD8A9DB37D702C470D7105CFB477E0DBBF35A0E607A5F581D61";
    };
    "nix-public/com/github/eldis/tool-launcher/0.2.2/tool-launcher-0.2.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/eldis/tool-launcher/0.2.2/tool-launcher-0.2.2.jar";
      sha256 = "4301389ED6EFFB3D8363F0B479B90A9CB787D8E265EB12E74CDB69D1AFD601DD";
    };
    "nix-public/com/github/eldis/tool-launcher/0.2.2/tool-launcher-0.2.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/github/eldis/tool-launcher/0.2.2/tool-launcher-0.2.2.pom";
      sha256 = "C0791A83C22AD1B5D2ED09B90DD8F1C23165D1621CF4D7980C37E5831B9EBF46";
    };
    "nix-public/com/github/luben/zstd-jni/1.5.6-3/zstd-jni-1.5.6-3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/luben/zstd-jni/1.5.6-3/zstd-jni-1.5.6-3-sources.jar";
      sha256 = "7136C42F56D17C8B2C7BE16FE7744C2C36B85C0C274750EFE5050E283D9BD31F";
    };
    "nix-public/com/github/luben/zstd-jni/1.5.6-3/zstd-jni-1.5.6-3.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/luben/zstd-jni/1.5.6-3/zstd-jni-1.5.6-3.jar";
      sha256 = "F72EDE1B39258FAF81277DC58DE30C71CBAE4253732558D2CE10B53D8B5763D5";
    };
    "nix-public/com/github/luben/zstd-jni/1.5.6-3/zstd-jni-1.5.6-3.pom" = {
      url = "https://repo1.maven.org/maven2/com/github/luben/zstd-jni/1.5.6-3/zstd-jni-1.5.6-3.pom";
      sha256 = "DFD2FA7B1D23939216902F844FA5E86A79CDFB9209760E4C04242B5A58D49490";
    };
    "nix-public/com/github/luben/zstd-jni/1.5.7-4/zstd-jni-1.5.7-4.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/luben/zstd-jni/1.5.7-4/zstd-jni-1.5.7-4.jar";
      sha256 = "E7F064BF1EAB83FA785CF587F657F09649E3B0AF6F27CAA5382416953B5A35F8";
    };
    "nix-public/com/github/luben/zstd-jni/1.5.7-4/zstd-jni-1.5.7-4.pom" = {
      url = "https://repo1.maven.org/maven2/com/github/luben/zstd-jni/1.5.7-4/zstd-jni-1.5.7-4.pom";
      sha256 = "6D60134C7644852574CCA4CAA37573206B21FF21439FD3203C42785D071166B9";
    };
    "nix-public/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5.2/jsoniter-scala-core-2.13.5.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5.2/jsoniter-scala-core_2.12-2.13.5.2-sources.jar";
      sha256 = "E99CB5EAC8FCE727E68AD7EBEBBF2FB247AF6EBF8FB7B0D530943FEA06776E35";
    };
    "nix-public/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5.2/jsoniter-scala-core-2.13.5.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5.2/jsoniter-scala-core_2.12-2.13.5.2.jar";
      sha256 = "8E2737C4B3D3B80FA4F2024F16351CC1018997249B8345AC8A98826BA158EEB3";
    };
    "nix-public/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5.2/jsoniter-scala-core-2.13.5.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5.2/jsoniter-scala-core_2.12-2.13.5.2.pom";
      sha256 = "7CB5513032999F0A2A8061AD2A5C0F3C1DD341272D0A8ACC4696C700A82F5F21";
    };
    "nix-public/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5.2/jsoniter-scala-core_2.12-2.13.5.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5.2/jsoniter-scala-core_2.12-2.13.5.2-sources.jar";
      sha256 = "E99CB5EAC8FCE727E68AD7EBEBBF2FB247AF6EBF8FB7B0D530943FEA06776E35";
    };
    "nix-public/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5.2/jsoniter-scala-core_2.12-2.13.5.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5.2/jsoniter-scala-core_2.12-2.13.5.2.jar";
      sha256 = "8E2737C4B3D3B80FA4F2024F16351CC1018997249B8345AC8A98826BA158EEB3";
    };
    "nix-public/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5.2/jsoniter-scala-core_2.12-2.13.5.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5.2/jsoniter-scala-core_2.12-2.13.5.2.pom";
      sha256 = "7CB5513032999F0A2A8061AD2A5C0F3C1DD341272D0A8ACC4696C700A82F5F21";
    };
    "nix-public/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5/jsoniter-scala-core-2.13.5.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5/jsoniter-scala-core_2.12-2.13.5.jar";
      sha256 = "6B7A8149F1D8EB379B236CE0A593F8EEDCCA341BF1D2E1A42FF2AD5D445AA4A3";
    };
    "nix-public/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5/jsoniter-scala-core-2.13.5.pom" = {
      url = "https://repo1.maven.org/maven2/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5/jsoniter-scala-core_2.12-2.13.5.pom";
      sha256 = "237F6A260F8B26591DF661679BD5FFA0CCC2634F8F78A5170FBB1BF523AB8E2D";
    };
    "nix-public/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5/jsoniter-scala-core_2.12-2.13.5.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5/jsoniter-scala-core_2.12-2.13.5.jar";
      sha256 = "6B7A8149F1D8EB379B236CE0A593F8EEDCCA341BF1D2E1A42FF2AD5D445AA4A3";
    };
    "nix-public/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5/jsoniter-scala-core_2.12-2.13.5.pom" = {
      url = "https://repo1.maven.org/maven2/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5/jsoniter-scala-core_2.12-2.13.5.pom";
      sha256 = "237F6A260F8B26591DF661679BD5FFA0CCC2634F8F78A5170FBB1BF523AB8E2D";
    };
    "nix-public/com/github/sbt/sbt-native-packager_2.12_1.0/1.11.7/sbt-native-packager-1.11.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/sbt/sbt-native-packager_2.12_1.0/1.11.7/sbt-native-packager_2.12_1.0-1.11.7-sources.jar";
      sha256 = "87E653640899835517E4CA344FB5D8ED0B660908C92661D37F6FEEAF1820A455";
    };
    "nix-public/com/github/sbt/sbt-native-packager_2.12_1.0/1.11.7/sbt-native-packager-1.11.7.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/sbt/sbt-native-packager_2.12_1.0/1.11.7/sbt-native-packager_2.12_1.0-1.11.7.jar";
      sha256 = "8DAA827BC975B185C00D3A05945A0D4CF9EC9C0E358712B2E856000615C94DF1";
    };
    "nix-public/com/github/sbt/sbt-native-packager_2.12_1.0/1.11.7/sbt-native-packager-1.11.7.pom" = {
      url = "https://repo1.maven.org/maven2/com/github/sbt/sbt-native-packager_2.12_1.0/1.11.7/sbt-native-packager_2.12_1.0-1.11.7.pom";
      sha256 = "264650C40CAC81B3B907AF3D3C54C4434061BDFD4FA81DF792D79805B041F8A8";
    };
    "nix-public/com/github/sbt/sbt-native-packager_2.12_1.0/1.11.7/sbt-native-packager_2.12_1.0-1.11.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/sbt/sbt-native-packager_2.12_1.0/1.11.7/sbt-native-packager_2.12_1.0-1.11.7-sources.jar";
      sha256 = "87E653640899835517E4CA344FB5D8ED0B660908C92661D37F6FEEAF1820A455";
    };
    "nix-public/com/github/sbt/sbt-native-packager_2.12_1.0/1.11.7/sbt-native-packager_2.12_1.0-1.11.7.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/sbt/sbt-native-packager_2.12_1.0/1.11.7/sbt-native-packager_2.12_1.0-1.11.7.jar";
      sha256 = "8DAA827BC975B185C00D3A05945A0D4CF9EC9C0E358712B2E856000615C94DF1";
    };
    "nix-public/com/github/sbt/sbt-native-packager_2.12_1.0/1.11.7/sbt-native-packager_2.12_1.0-1.11.7.pom" = {
      url = "https://repo1.maven.org/maven2/com/github/sbt/sbt-native-packager_2.12_1.0/1.11.7/sbt-native-packager_2.12_1.0-1.11.7.pom";
      sha256 = "264650C40CAC81B3B907AF3D3C54C4434061BDFD4FA81DF792D79805B041F8A8";
    };
    "nix-public/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar";
      sha256 = "766AD2A0783F2687962C8AD74CEECC38A28B9F72A2D085EE438B7813E928D0C7";
    };
    "nix-public/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.pom";
      sha256 = "19889DBDF1B254B2601A5EE645B8147A974644882297684C798AFE5D63D78DFE";
    };
    "nix-public/com/lihaoyi/acyclic_2.12.20/0.3.19/acyclic_2.12.20-0.3.19.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/acyclic_2.12.20/0.3.19/acyclic_2.12.20-0.3.19.jar";
      sha256 = "AA42BDBE79C1B59BD1F714D29C53319102CD45D59C4F371D0FF18A8474D0BB67";
    };
    "nix-public/com/lihaoyi/acyclic_2.12.20/0.3.19/acyclic_2.12.20-0.3.19.pom" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/acyclic_2.12.20/0.3.19/acyclic_2.12.20-0.3.19.pom";
      sha256 = "C054921910D0BD8B3BF4103CCC900FE40BD9EF4A1242F1AEB3589B957F57E992";
    };
    "nix-public/com/lihaoyi/geny_2.12/1.1.1/geny-1.1.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/geny_2.12/1.1.1/geny_2.12-1.1.1-sources.jar";
      sha256 = "7AE0B4DD7A503ED9592FD120C9FFF824CDE5B073B1639EB97A5A2EC9E811C47B";
    };
    "nix-public/com/lihaoyi/geny_2.12/1.1.1/geny-1.1.1.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/geny_2.12/1.1.1/geny_2.12-1.1.1.jar";
      sha256 = "2CB8C592106778BD4DB849E90BAEB5EAF2A78605444FA3187FD6F595BAD381D2";
    };
    "nix-public/com/lihaoyi/geny_2.12/1.1.1/geny-1.1.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/geny_2.12/1.1.1/geny_2.12-1.1.1.pom";
      sha256 = "5400D8F61DE8ABB8365712070AB4EF796A5C76830CDC9E8D01D5B3CA0C37DA29";
    };
    "nix-public/com/lihaoyi/geny_2.12/1.1.1/geny_2.12-1.1.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/geny_2.12/1.1.1/geny_2.12-1.1.1-sources.jar";
      sha256 = "7AE0B4DD7A503ED9592FD120C9FFF824CDE5B073B1639EB97A5A2EC9E811C47B";
    };
    "nix-public/com/lihaoyi/geny_2.12/1.1.1/geny_2.12-1.1.1.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/geny_2.12/1.1.1/geny_2.12-1.1.1.jar";
      sha256 = "2CB8C592106778BD4DB849E90BAEB5EAF2A78605444FA3187FD6F595BAD381D2";
    };
    "nix-public/com/lihaoyi/geny_2.12/1.1.1/geny_2.12-1.1.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/geny_2.12/1.1.1/geny_2.12-1.1.1.pom";
      sha256 = "5400D8F61DE8ABB8365712070AB4EF796A5C76830CDC9E8D01D5B3CA0C37DA29";
    };
    "nix-public/com/lihaoyi/ujson_2.12/4.4.3/ujson-4.4.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/ujson_2.12/4.4.3/ujson_2.12-4.4.3-sources.jar";
      sha256 = "2816E69BA945E9191F1AC4886C526908FFFBB938F22207BB05579FAE13EB2CA6";
    };
    "nix-public/com/lihaoyi/ujson_2.12/4.4.3/ujson-4.4.3.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/ujson_2.12/4.4.3/ujson_2.12-4.4.3.jar";
      sha256 = "B016C390D5014EA048734C31056A55338C08F31B913136B9457AD4D501FD648A";
    };
    "nix-public/com/lihaoyi/ujson_2.12/4.4.3/ujson-4.4.3.pom" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/ujson_2.12/4.4.3/ujson_2.12-4.4.3.pom";
      sha256 = "2D83F14378CE692EFEC24DBFB7804B194E1F9D69819EE8A970C17EBE232EB849";
    };
    "nix-public/com/lihaoyi/ujson_2.12/4.4.3/ujson_2.12-4.4.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/ujson_2.12/4.4.3/ujson_2.12-4.4.3-sources.jar";
      sha256 = "2816E69BA945E9191F1AC4886C526908FFFBB938F22207BB05579FAE13EB2CA6";
    };
    "nix-public/com/lihaoyi/ujson_2.12/4.4.3/ujson_2.12-4.4.3.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/ujson_2.12/4.4.3/ujson_2.12-4.4.3.jar";
      sha256 = "B016C390D5014EA048734C31056A55338C08F31B913136B9457AD4D501FD648A";
    };
    "nix-public/com/lihaoyi/ujson_2.12/4.4.3/ujson_2.12-4.4.3.pom" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/ujson_2.12/4.4.3/ujson_2.12-4.4.3.pom";
      sha256 = "2D83F14378CE692EFEC24DBFB7804B194E1F9D69819EE8A970C17EBE232EB849";
    };
    "nix-public/com/lihaoyi/upack_2.12/4.4.3/upack-4.4.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upack_2.12/4.4.3/upack_2.12-4.4.3-sources.jar";
      sha256 = "B402CA36C6609C11B0DE4AE1C4570026C261DCD816289607109AF27C00777640";
    };
    "nix-public/com/lihaoyi/upack_2.12/4.4.3/upack-4.4.3.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upack_2.12/4.4.3/upack_2.12-4.4.3.jar";
      sha256 = "356A271D2400C6242BE7E0A55C45ABAC7DCF780F31C133709182359E5FAB72D2";
    };
    "nix-public/com/lihaoyi/upack_2.12/4.4.3/upack-4.4.3.pom" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upack_2.12/4.4.3/upack_2.12-4.4.3.pom";
      sha256 = "828026D3CB73290A3D211A791656AE081757826304D295903EB37B50380CA838";
    };
    "nix-public/com/lihaoyi/upack_2.12/4.4.3/upack_2.12-4.4.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upack_2.12/4.4.3/upack_2.12-4.4.3-sources.jar";
      sha256 = "B402CA36C6609C11B0DE4AE1C4570026C261DCD816289607109AF27C00777640";
    };
    "nix-public/com/lihaoyi/upack_2.12/4.4.3/upack_2.12-4.4.3.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upack_2.12/4.4.3/upack_2.12-4.4.3.jar";
      sha256 = "356A271D2400C6242BE7E0A55C45ABAC7DCF780F31C133709182359E5FAB72D2";
    };
    "nix-public/com/lihaoyi/upack_2.12/4.4.3/upack_2.12-4.4.3.pom" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upack_2.12/4.4.3/upack_2.12-4.4.3.pom";
      sha256 = "828026D3CB73290A3D211A791656AE081757826304D295903EB37B50380CA838";
    };
    "nix-public/com/lihaoyi/upickle-core_2.12/4.4.3/upickle-core-4.4.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle-core_2.12/4.4.3/upickle-core_2.12-4.4.3-sources.jar";
      sha256 = "8BC91D11E6CB01087ABBFCC9E2861245BCD37454FD4865466D1B1D4BBDCA9890";
    };
    "nix-public/com/lihaoyi/upickle-core_2.12/4.4.3/upickle-core-4.4.3.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle-core_2.12/4.4.3/upickle-core_2.12-4.4.3.jar";
      sha256 = "29F932329EBC82DD69352653D9A1D77B04749EE525DED76B5460E0B62047C947";
    };
    "nix-public/com/lihaoyi/upickle-core_2.12/4.4.3/upickle-core-4.4.3.pom" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle-core_2.12/4.4.3/upickle-core_2.12-4.4.3.pom";
      sha256 = "6D887DBB512953D4850370EF7E9F9E6464D8096343FACA93D19E4CEDC7701DB1";
    };
    "nix-public/com/lihaoyi/upickle-core_2.12/4.4.3/upickle-core_2.12-4.4.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle-core_2.12/4.4.3/upickle-core_2.12-4.4.3-sources.jar";
      sha256 = "8BC91D11E6CB01087ABBFCC9E2861245BCD37454FD4865466D1B1D4BBDCA9890";
    };
    "nix-public/com/lihaoyi/upickle-core_2.12/4.4.3/upickle-core_2.12-4.4.3.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle-core_2.12/4.4.3/upickle-core_2.12-4.4.3.jar";
      sha256 = "29F932329EBC82DD69352653D9A1D77B04749EE525DED76B5460E0B62047C947";
    };
    "nix-public/com/lihaoyi/upickle-core_2.12/4.4.3/upickle-core_2.12-4.4.3.pom" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle-core_2.12/4.4.3/upickle-core_2.12-4.4.3.pom";
      sha256 = "6D887DBB512953D4850370EF7E9F9E6464D8096343FACA93D19E4CEDC7701DB1";
    };
    "nix-public/com/lihaoyi/upickle-implicits_2.12/4.4.3/upickle-implicits-4.4.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle-implicits_2.12/4.4.3/upickle-implicits_2.12-4.4.3-sources.jar";
      sha256 = "98148DFB52FD5A5573B14A673B78DCB036B89FAFDC93F5B43CF52938FB5AA362";
    };
    "nix-public/com/lihaoyi/upickle-implicits_2.12/4.4.3/upickle-implicits-4.4.3.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle-implicits_2.12/4.4.3/upickle-implicits_2.12-4.4.3.jar";
      sha256 = "DB7A8694D1A22F605135BAF049EBB03E47EDC2695A73BA6596E8F5576E52BB6D";
    };
    "nix-public/com/lihaoyi/upickle-implicits_2.12/4.4.3/upickle-implicits-4.4.3.pom" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle-implicits_2.12/4.4.3/upickle-implicits_2.12-4.4.3.pom";
      sha256 = "DA2E11A928F77EE3A7815A9FB0E213AE6ECA448005170E2664CAB227D662543A";
    };
    "nix-public/com/lihaoyi/upickle-implicits_2.12/4.4.3/upickle-implicits_2.12-4.4.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle-implicits_2.12/4.4.3/upickle-implicits_2.12-4.4.3-sources.jar";
      sha256 = "98148DFB52FD5A5573B14A673B78DCB036B89FAFDC93F5B43CF52938FB5AA362";
    };
    "nix-public/com/lihaoyi/upickle-implicits_2.12/4.4.3/upickle-implicits_2.12-4.4.3.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle-implicits_2.12/4.4.3/upickle-implicits_2.12-4.4.3.jar";
      sha256 = "DB7A8694D1A22F605135BAF049EBB03E47EDC2695A73BA6596E8F5576E52BB6D";
    };
    "nix-public/com/lihaoyi/upickle-implicits_2.12/4.4.3/upickle-implicits_2.12-4.4.3.pom" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle-implicits_2.12/4.4.3/upickle-implicits_2.12-4.4.3.pom";
      sha256 = "DA2E11A928F77EE3A7815A9FB0E213AE6ECA448005170E2664CAB227D662543A";
    };
    "nix-public/com/lihaoyi/upickle_2.12/4.4.3/upickle-4.4.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle_2.12/4.4.3/upickle_2.12-4.4.3-sources.jar";
      sha256 = "5282F99CF21D4915FE761E2DF29584CD8C00B2E819321A86FBAE5D93063DC49A";
    };
    "nix-public/com/lihaoyi/upickle_2.12/4.4.3/upickle-4.4.3.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle_2.12/4.4.3/upickle_2.12-4.4.3.jar";
      sha256 = "7BF6A2D29096107A490346A807765F420FE946CB658708E0E0B0BB1BFECAFDED";
    };
    "nix-public/com/lihaoyi/upickle_2.12/4.4.3/upickle-4.4.3.pom" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle_2.12/4.4.3/upickle_2.12-4.4.3.pom";
      sha256 = "72CA49D9F65D4ACF17E594BE63BF61CA6E58FF0D9EFE48D5F2CBD297B2D1650B";
    };
    "nix-public/com/lihaoyi/upickle_2.12/4.4.3/upickle_2.12-4.4.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle_2.12/4.4.3/upickle_2.12-4.4.3-sources.jar";
      sha256 = "5282F99CF21D4915FE761E2DF29584CD8C00B2E819321A86FBAE5D93063DC49A";
    };
    "nix-public/com/lihaoyi/upickle_2.12/4.4.3/upickle_2.12-4.4.3.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle_2.12/4.4.3/upickle_2.12-4.4.3.jar";
      sha256 = "7BF6A2D29096107A490346A807765F420FE946CB658708E0E0B0BB1BFECAFDED";
    };
    "nix-public/com/lihaoyi/upickle_2.12/4.4.3/upickle_2.12-4.4.3.pom" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle_2.12/4.4.3/upickle_2.12-4.4.3.pom";
      sha256 = "72CA49D9F65D4ACF17E594BE63BF61CA6E58FF0D9EFE48D5F2CBD297B2D1650B";
    };
    "nix-public/com/swoval/file-tree-views/2.1.12/file-tree-views-2.1.12.jar" = {
      url = "https://repo1.maven.org/maven2/com/swoval/file-tree-views/2.1.12/file-tree-views-2.1.12.jar";
      sha256 = "FD7373889B7A92CF3E97DB36C920BA272AEC158A9387B3259FCA9F2DFAEDA914";
    };
    "nix-public/com/swoval/file-tree-views/2.1.12/file-tree-views-2.1.12.pom" = {
      url = "https://repo1.maven.org/maven2/com/swoval/file-tree-views/2.1.12/file-tree-views-2.1.12.pom";
      sha256 = "EDD270DC776D1D85DD300E415CFF9E0609757D7AFEB223A6B187BAD5B0ABE746";
    };
    "nix-public/commons-codec/commons-codec/1.17.0/commons-codec-1.17.0.jar" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.17.0/commons-codec-1.17.0.jar";
      sha256 = "F700DE80AC270D0344FDEA7468201D8B9C805E5C648331C3619F2EE067CCFC59";
    };
    "nix-public/commons-codec/commons-codec/1.17.0/commons-codec-1.17.0.pom" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.17.0/commons-codec-1.17.0.pom";
      sha256 = "C01C4CDA5E408F41ED1D83E4A0A170CF53801B6338ABA49F0F904786BC1214FC";
    };
    "nix-public/commons-codec/commons-codec/1.19.0/commons-codec-1.19.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.19.0/commons-codec-1.19.0-sources.jar";
      sha256 = "B0462142585D45FC15BC8091B7B02F1E3A85C83595068659548C82CAC9CDC7A2";
    };
    "nix-public/commons-codec/commons-codec/1.19.0/commons-codec-1.19.0-tests.jar" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.19.0/commons-codec-1.19.0-tests.jar";
      sha256 = "DF1AAFE64F7F9CA6F7B341CC6BA4F111F536C8F8EA685E49FE85A8B4DC742C61";
    };
    "nix-public/commons-codec/commons-codec/1.19.0/commons-codec-1.19.0.jar" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.19.0/commons-codec-1.19.0.jar";
      sha256 = "5C3881E4F556855E9C532927EE0C9DFDE94CC66760D5805C031A59887070AF5F";
    };
    "nix-public/commons-codec/commons-codec/1.19.0/commons-codec-1.19.0.pom" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.19.0/commons-codec-1.19.0.pom";
      sha256 = "E0F3269FA23DE0C83130C5659F5F9514CC5422C0BCDF45F2EAE004A78B9FCA34";
    };
    "nix-public/commons-io/commons-io/2.16.1/commons-io-2.16.1.jar" = {
      url = "https://repo1.maven.org/maven2/commons-io/commons-io/2.16.1/commons-io-2.16.1.jar";
      sha256 = "F41F7BAACD716896447ACE9758621F62C1C6B0A91D89ACEE488DA26FC477C84F";
    };
    "nix-public/commons-io/commons-io/2.16.1/commons-io-2.16.1.pom" = {
      url = "https://repo1.maven.org/maven2/commons-io/commons-io/2.16.1/commons-io-2.16.1.pom";
      sha256 = "5777D292251C7895C04A4C57015683EC3B353A12486C9B3E7178E9B0B3C38FFF";
    };
    "nix-public/commons-io/commons-io/2.20.0/commons-io-2.20.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/commons-io/commons-io/2.20.0/commons-io-2.20.0-sources.jar";
      sha256 = "7A87277538CCE40DA6389A7163A4D9458BC7A9C39937A329881B91D144BE8E0D";
    };
    "nix-public/commons-io/commons-io/2.20.0/commons-io-2.20.0-tests.jar" = {
      url = "https://repo1.maven.org/maven2/commons-io/commons-io/2.20.0/commons-io-2.20.0-tests.jar";
      sha256 = "AF4D6981B47D041110EE3041D28F037EC11976F12CEFD3815A3F0F21C19335C7";
    };
    "nix-public/commons-io/commons-io/2.20.0/commons-io-2.20.0.jar" = {
      url = "https://repo1.maven.org/maven2/commons-io/commons-io/2.20.0/commons-io-2.20.0.jar";
      sha256 = "DF90BBA0FE3CB586B7F164E78FE8F8F4DA3F2DD5C27FA645F888100CCC25DD72";
    };
    "nix-public/commons-io/commons-io/2.20.0/commons-io-2.20.0.pom" = {
      url = "https://repo1.maven.org/maven2/commons-io/commons-io/2.20.0/commons-io-2.20.0.pom";
      sha256 = "BDBDF81072C190EE9A8B181A5C58F5BD917A750FB13A256DEBBF53F5DBD33A2A";
    };
    "nix-public/commons-logging/commons-logging-api/1.1/commons-logging-api-1.1.jar" = {
      url = "https://repo1.maven.org/maven2/commons-logging/commons-logging-api/1.1/commons-logging-api-1.1.jar";
      sha256 = "33A4DD47BB4764E4EB3692D86386D17A0D9827F4F4BB0F70121EFAB6BC03BA35";
    };
    "nix-public/commons-logging/commons-logging-api/1.1/commons-logging-api-1.1.pom" = {
      url = "https://repo1.maven.org/maven2/commons-logging/commons-logging-api/1.1/commons-logging-api-1.1.pom";
      sha256 = "69B8BE61AA746C7D02ACB1B11EB3B57CB22B246780ED71D79764195CBBE3D99D";
    };
    "nix-public/io/airlift/airbase/112/airbase-112.pom" = {
      url = "https://repo1.maven.org/maven2/io/airlift/airbase/112/airbase-112.pom";
      sha256 = "18CCD104CBD97EB44BD57B68C047AB7FF81FBC800987F82D815C68AC4C2304CE";
    };
    "nix-public/io/airlift/aircompressor/0.27/aircompressor-0.27-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/airlift/aircompressor/0.27/aircompressor-0.27-sources.jar";
      sha256 = "7F5952D138E9CFF1445A961B90228680B5714145038648E02E4433490E5F078D";
    };
    "nix-public/io/airlift/aircompressor/0.27/aircompressor-0.27-tests.jar" = {
      url = "https://repo1.maven.org/maven2/io/airlift/aircompressor/0.27/aircompressor-0.27-tests.jar";
      sha256 = "4E252565719C07327EB2C5AB38D2BF2FC7A2A24CA880566154DC250A866C5763";
    };
    "nix-public/io/airlift/aircompressor/0.27/aircompressor-0.27.jar" = {
      url = "https://repo1.maven.org/maven2/io/airlift/aircompressor/0.27/aircompressor-0.27.jar";
      sha256 = "FDBEF3137A28F63BB0CB93487803080EDE746A4EC3D421E36C6F0C305C35E5E4";
    };
    "nix-public/io/airlift/aircompressor/0.27/aircompressor-0.27.pom" = {
      url = "https://repo1.maven.org/maven2/io/airlift/aircompressor/0.27/aircompressor-0.27.pom";
      sha256 = "5AACDA89BE38563BDF3BFAC79333616C0802CA617070DEA66BA649507C994441";
    };
    "nix-public/io/get-coursier/cache-util/2.1.24/cache-util-2.1.24-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/cache-util/2.1.24/cache-util-2.1.24-sources.jar";
      sha256 = "46F152A3ECD09199A541E5E9A6A67DBD3080DC20E69CE7CE11BFA5AC477EFCAE";
    };
    "nix-public/io/get-coursier/cache-util/2.1.24/cache-util-2.1.24.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/cache-util/2.1.24/cache-util-2.1.24.jar";
      sha256 = "447741AFB13B90E7F650ED89F230BF0E9D76874F80EF516E2AA3963BA56EDF84";
    };
    "nix-public/io/get-coursier/cache-util/2.1.24/cache-util-2.1.24.pom" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/cache-util/2.1.24/cache-util-2.1.24.pom";
      sha256 = "C58D75C3DE6AA7F1ABCE757524370D43665F9E07E89F2141DB21AABC9F83845E";
    };
    "nix-public/io/get-coursier/coursier-cache_2.12/2.1.24/coursier-cache-2.1.24-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-cache_2.12/2.1.24/coursier-cache_2.12-2.1.24-sources.jar";
      sha256 = "C48ACB00717DD2D385FB792599D5FAC9C0BCEC803BCD1862641F237A8FF46360";
    };
    "nix-public/io/get-coursier/coursier-cache_2.12/2.1.24/coursier-cache-2.1.24.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-cache_2.12/2.1.24/coursier-cache_2.12-2.1.24.jar";
      sha256 = "FDA852B40E62241FA61E2C56332A83B1D7A11E677FE0EBB9E9EF33A189D310FE";
    };
    "nix-public/io/get-coursier/coursier-cache_2.12/2.1.24/coursier-cache-2.1.24.pom" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-cache_2.12/2.1.24/coursier-cache_2.12-2.1.24.pom";
      sha256 = "A5359DD19A1C5081F949CCBB532BBEFF28944F5C5BBF93DD1CF8CC4E116384A9";
    };
    "nix-public/io/get-coursier/coursier-cache_2.12/2.1.24/coursier-cache_2.12-2.1.24-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-cache_2.12/2.1.24/coursier-cache_2.12-2.1.24-sources.jar";
      sha256 = "C48ACB00717DD2D385FB792599D5FAC9C0BCEC803BCD1862641F237A8FF46360";
    };
    "nix-public/io/get-coursier/coursier-cache_2.12/2.1.24/coursier-cache_2.12-2.1.24.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-cache_2.12/2.1.24/coursier-cache_2.12-2.1.24.jar";
      sha256 = "FDA852B40E62241FA61E2C56332A83B1D7A11E677FE0EBB9E9EF33A189D310FE";
    };
    "nix-public/io/get-coursier/coursier-cache_2.12/2.1.24/coursier-cache_2.12-2.1.24.pom" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-cache_2.12/2.1.24/coursier-cache_2.12-2.1.24.pom";
      sha256 = "A5359DD19A1C5081F949CCBB532BBEFF28944F5C5BBF93DD1CF8CC4E116384A9";
    };
    "nix-public/io/get-coursier/coursier-core_2.12/2.1.24/coursier-core-2.1.24-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-core_2.12/2.1.24/coursier-core_2.12-2.1.24-sources.jar";
      sha256 = "FA4A88EDF9CC756D4F785BCF8C406D69F1CEB409D3EE6D1A7D5F4C8930986816";
    };
    "nix-public/io/get-coursier/coursier-core_2.12/2.1.24/coursier-core-2.1.24.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-core_2.12/2.1.24/coursier-core_2.12-2.1.24.jar";
      sha256 = "85BA2F54DB0B79A5D8BE519EB4F5B45B1065924D8DBCF4F19FDA98BF93417D2A";
    };
    "nix-public/io/get-coursier/coursier-core_2.12/2.1.24/coursier-core-2.1.24.pom" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-core_2.12/2.1.24/coursier-core_2.12-2.1.24.pom";
      sha256 = "8D3D38BE8202E34465E3C01BDC08467C3FD6B394C4C35C5D9205AC0777CDD87E";
    };
    "nix-public/io/get-coursier/coursier-core_2.12/2.1.24/coursier-core_2.12-2.1.24-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-core_2.12/2.1.24/coursier-core_2.12-2.1.24-sources.jar";
      sha256 = "FA4A88EDF9CC756D4F785BCF8C406D69F1CEB409D3EE6D1A7D5F4C8930986816";
    };
    "nix-public/io/get-coursier/coursier-core_2.12/2.1.24/coursier-core_2.12-2.1.24.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-core_2.12/2.1.24/coursier-core_2.12-2.1.24.jar";
      sha256 = "85BA2F54DB0B79A5D8BE519EB4F5B45B1065924D8DBCF4F19FDA98BF93417D2A";
    };
    "nix-public/io/get-coursier/coursier-core_2.12/2.1.24/coursier-core_2.12-2.1.24.pom" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-core_2.12/2.1.24/coursier-core_2.12-2.1.24.pom";
      sha256 = "8D3D38BE8202E34465E3C01BDC08467C3FD6B394C4C35C5D9205AC0777CDD87E";
    };
    "nix-public/io/get-coursier/coursier-proxy-setup/2.1.24/coursier-proxy-setup-2.1.24-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-proxy-setup/2.1.24/coursier-proxy-setup-2.1.24-sources.jar";
      sha256 = "A5B50CCD284C23708C9FD788D1B611F68697E098D0B26B8F4AE85482492801DA";
    };
    "nix-public/io/get-coursier/coursier-proxy-setup/2.1.24/coursier-proxy-setup-2.1.24.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-proxy-setup/2.1.24/coursier-proxy-setup-2.1.24.jar";
      sha256 = "BD7DFA4325FEC5E2E4CB671BB42953E970A2F9141526D93AAEA678A07DA3CE5B";
    };
    "nix-public/io/get-coursier/coursier-proxy-setup/2.1.24/coursier-proxy-setup-2.1.24.pom" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-proxy-setup/2.1.24/coursier-proxy-setup-2.1.24.pom";
      sha256 = "E9F1B2344F6644BCCE799B5378067CD83AC5E471BBB4730B5875AC6B03E0A4AD";
    };
    "nix-public/io/get-coursier/coursier-sbt-maven-repository_2.12/2.1.24/coursier-sbt-maven-repository-2.1.24-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-sbt-maven-repository_2.12/2.1.24/coursier-sbt-maven-repository_2.12-2.1.24-sources.jar";
      sha256 = "974B3D52E91876A04592A3D7401447D4B81E462104AD38D42B55D436844D18A9";
    };
    "nix-public/io/get-coursier/coursier-sbt-maven-repository_2.12/2.1.24/coursier-sbt-maven-repository-2.1.24.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-sbt-maven-repository_2.12/2.1.24/coursier-sbt-maven-repository_2.12-2.1.24.jar";
      sha256 = "1713701912FF4EF9C76EFBA2FC86ACBFA2438C2A02487CDC66711747E87FAA58";
    };
    "nix-public/io/get-coursier/coursier-sbt-maven-repository_2.12/2.1.24/coursier-sbt-maven-repository-2.1.24.pom" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-sbt-maven-repository_2.12/2.1.24/coursier-sbt-maven-repository_2.12-2.1.24.pom";
      sha256 = "C492D5F4BD8EA29DA5F5A51EDD8C4796A4BE6EC5D14907F8DF3E517C00E4C564";
    };
    "nix-public/io/get-coursier/coursier-sbt-maven-repository_2.12/2.1.24/coursier-sbt-maven-repository_2.12-2.1.24-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-sbt-maven-repository_2.12/2.1.24/coursier-sbt-maven-repository_2.12-2.1.24-sources.jar";
      sha256 = "974B3D52E91876A04592A3D7401447D4B81E462104AD38D42B55D436844D18A9";
    };
    "nix-public/io/get-coursier/coursier-sbt-maven-repository_2.12/2.1.24/coursier-sbt-maven-repository_2.12-2.1.24.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-sbt-maven-repository_2.12/2.1.24/coursier-sbt-maven-repository_2.12-2.1.24.jar";
      sha256 = "1713701912FF4EF9C76EFBA2FC86ACBFA2438C2A02487CDC66711747E87FAA58";
    };
    "nix-public/io/get-coursier/coursier-sbt-maven-repository_2.12/2.1.24/coursier-sbt-maven-repository_2.12-2.1.24.pom" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-sbt-maven-repository_2.12/2.1.24/coursier-sbt-maven-repository_2.12-2.1.24.pom";
      sha256 = "C492D5F4BD8EA29DA5F5A51EDD8C4796A4BE6EC5D14907F8DF3E517C00E4C564";
    };
    "nix-public/io/get-coursier/coursier-util_2.12/2.1.24/coursier-util-2.1.24-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-util_2.12/2.1.24/coursier-util_2.12-2.1.24-sources.jar";
      sha256 = "9410C64FDF5553347DF8574FD99F0EFFACD391D1567415E1368BF18A41E132AD";
    };
    "nix-public/io/get-coursier/coursier-util_2.12/2.1.24/coursier-util-2.1.24.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-util_2.12/2.1.24/coursier-util_2.12-2.1.24.jar";
      sha256 = "30D02902DBF7D1AC6CB2822974226732B1CEB957D87F22B3AD14108495BDFCB1";
    };
    "nix-public/io/get-coursier/coursier-util_2.12/2.1.24/coursier-util-2.1.24.pom" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-util_2.12/2.1.24/coursier-util_2.12-2.1.24.pom";
      sha256 = "A5EE542FBC25A0D3DC28E31594087F0F63CA8B6CCFF57A7C7DDC9168B7539967";
    };
    "nix-public/io/get-coursier/coursier-util_2.12/2.1.24/coursier-util_2.12-2.1.24-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-util_2.12/2.1.24/coursier-util_2.12-2.1.24-sources.jar";
      sha256 = "9410C64FDF5553347DF8574FD99F0EFFACD391D1567415E1368BF18A41E132AD";
    };
    "nix-public/io/get-coursier/coursier-util_2.12/2.1.24/coursier-util_2.12-2.1.24.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-util_2.12/2.1.24/coursier-util_2.12-2.1.24.jar";
      sha256 = "30D02902DBF7D1AC6CB2822974226732B1CEB957D87F22B3AD14108495BDFCB1";
    };
    "nix-public/io/get-coursier/coursier-util_2.12/2.1.24/coursier-util_2.12-2.1.24.pom" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-util_2.12/2.1.24/coursier-util_2.12-2.1.24.pom";
      sha256 = "A5EE542FBC25A0D3DC28E31594087F0F63CA8B6CCFF57A7C7DDC9168B7539967";
    };
    "nix-public/io/get-coursier/coursier_2.12/2.1.24/coursier-2.1.24-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier_2.12/2.1.24/coursier_2.12-2.1.24-sources.jar";
      sha256 = "D561C39815E06C8851C9BDF517403F0BDDA67B05A6D48451974D20C939BF171F";
    };
    "nix-public/io/get-coursier/coursier_2.12/2.1.24/coursier-2.1.24.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier_2.12/2.1.24/coursier_2.12-2.1.24.jar";
      sha256 = "F5A93B3C4374452CB36E60C304830F381EDA216EDF8855EB31C7E0FC33AB4197";
    };
    "nix-public/io/get-coursier/coursier_2.12/2.1.24/coursier-2.1.24.pom" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier_2.12/2.1.24/coursier_2.12-2.1.24.pom";
      sha256 = "5ACEF40230D2D121FD6B98941444EE03BD01A984F9CA608CECCD9DEB39DF372D";
    };
    "nix-public/io/get-coursier/coursier_2.12/2.1.24/coursier_2.12-2.1.24-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier_2.12/2.1.24/coursier_2.12-2.1.24-sources.jar";
      sha256 = "D561C39815E06C8851C9BDF517403F0BDDA67B05A6D48451974D20C939BF171F";
    };
    "nix-public/io/get-coursier/coursier_2.12/2.1.24/coursier_2.12-2.1.24.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier_2.12/2.1.24/coursier_2.12-2.1.24.jar";
      sha256 = "F5A93B3C4374452CB36E60C304830F381EDA216EDF8855EB31C7E0FC33AB4197";
    };
    "nix-public/io/get-coursier/coursier_2.12/2.1.24/coursier_2.12-2.1.24.pom" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier_2.12/2.1.24/coursier_2.12-2.1.24.pom";
      sha256 = "5ACEF40230D2D121FD6B98941444EE03BD01A984F9CA608CECCD9DEB39DF372D";
    };
    "nix-public/io/get-coursier/dependency_2.12/0.3.2/dependency-0.3.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/dependency_2.12/0.3.2/dependency_2.12-0.3.2-sources.jar";
      sha256 = "10AC0FC9FEE555BE20023D2458E02E1ABE150A9F122A3E0D500E553DC819C95D";
    };
    "nix-public/io/get-coursier/dependency_2.12/0.3.2/dependency-0.3.2.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/dependency_2.12/0.3.2/dependency_2.12-0.3.2.jar";
      sha256 = "5192587C13DEE48917304611902D45B2ABDD8F7811CCAF4D74B45C18746D266E";
    };
    "nix-public/io/get-coursier/dependency_2.12/0.3.2/dependency-0.3.2.pom" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/dependency_2.12/0.3.2/dependency_2.12-0.3.2.pom";
      sha256 = "0886A37BB039A0C93B1EEDE44BAB390D0AC72F38E5507F1C1DA8E20AE6764151";
    };
    "nix-public/io/get-coursier/dependency_2.12/0.3.2/dependency_2.12-0.3.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/dependency_2.12/0.3.2/dependency_2.12-0.3.2-sources.jar";
      sha256 = "10AC0FC9FEE555BE20023D2458E02E1ABE150A9F122A3E0D500E553DC819C95D";
    };
    "nix-public/io/get-coursier/dependency_2.12/0.3.2/dependency_2.12-0.3.2.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/dependency_2.12/0.3.2/dependency_2.12-0.3.2.jar";
      sha256 = "5192587C13DEE48917304611902D45B2ABDD8F7811CCAF4D74B45C18746D266E";
    };
    "nix-public/io/get-coursier/dependency_2.12/0.3.2/dependency_2.12-0.3.2.pom" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/dependency_2.12/0.3.2/dependency_2.12-0.3.2.pom";
      sha256 = "0886A37BB039A0C93B1EEDE44BAB390D0AC72F38E5507F1C1DA8E20AE6764151";
    };
    "nix-public/io/get-coursier/jniutils/windows-jni-utils/0.3.3/windows-jni-utils-0.3.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/jniutils/windows-jni-utils/0.3.3/windows-jni-utils-0.3.3-sources.jar";
      sha256 = "D533760CEF440EB3A8A47CFE6815E1F9A161CB1F01A5A61DBF8B2A30489C8583";
    };
    "nix-public/io/get-coursier/jniutils/windows-jni-utils/0.3.3/windows-jni-utils-0.3.3.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/jniutils/windows-jni-utils/0.3.3/windows-jni-utils-0.3.3.jar";
      sha256 = "AB68EFCF162355E20007B238D8108B7FFEC0C06B467EE44CBB44EC3F8AC3A7E6";
    };
    "nix-public/io/get-coursier/jniutils/windows-jni-utils/0.3.3/windows-jni-utils-0.3.3.pom" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/jniutils/windows-jni-utils/0.3.3/windows-jni-utils-0.3.3.pom";
      sha256 = "AD53900F92683F3714BE442ECB464421A5F8FA2890C1A91B1FBE3E0ECD62914B";
    };
    "nix-public/io/github/alexarchambault/concurrent-reference-hash-map/1.1.0/concurrent-reference-hash-map-1.1.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/github/alexarchambault/concurrent-reference-hash-map/1.1.0/concurrent-reference-hash-map-1.1.0-sources.jar";
      sha256 = "931213419BA6C90769C7BA73F85973EC79EF55BB6A99BA3093E87A427AC0D2AC";
    };
    "nix-public/io/github/alexarchambault/concurrent-reference-hash-map/1.1.0/concurrent-reference-hash-map-1.1.0.jar" = {
      url = "https://repo1.maven.org/maven2/io/github/alexarchambault/concurrent-reference-hash-map/1.1.0/concurrent-reference-hash-map-1.1.0.jar";
      sha256 = "552707982209AFB9FEFFDCCB2E73CC4681A1353E34A47DF1BF643D1D2E0A2F61";
    };
    "nix-public/io/github/alexarchambault/concurrent-reference-hash-map/1.1.0/concurrent-reference-hash-map-1.1.0.pom" = {
      url = "https://repo1.maven.org/maven2/io/github/alexarchambault/concurrent-reference-hash-map/1.1.0/concurrent-reference-hash-map-1.1.0.pom";
      sha256 = "21096686F9964694DB1B8F16F471C3B9B8FB278E390950FAC683760C4A6F0816";
    };
    "nix-public/io/github/alexarchambault/is-terminal/0.1.1/is-terminal-0.1.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/github/alexarchambault/is-terminal/0.1.1/is-terminal-0.1.1-sources.jar";
      sha256 = "A2D6525537B7DC6552C541F4C0BA485B05079D01DB85D59DDD1B69A40F159CE4";
    };
    "nix-public/io/github/alexarchambault/is-terminal/0.1.1/is-terminal-0.1.1.jar" = {
      url = "https://repo1.maven.org/maven2/io/github/alexarchambault/is-terminal/0.1.1/is-terminal-0.1.1.jar";
      sha256 = "73735B053B01FF47B53D28AB2D9B23FD86447F6FB6463DD462258067AD6AD3FA";
    };
    "nix-public/io/github/alexarchambault/is-terminal/0.1.1/is-terminal-0.1.1.pom" = {
      url = "https://repo1.maven.org/maven2/io/github/alexarchambault/is-terminal/0.1.1/is-terminal-0.1.1.pom";
      sha256 = "6B666C221711D8289CF2FB4F443FE728EC531348175DA529056D7FCECBEE6122";
    };
    "nix-public/io/github/alexarchambault/windows-ansi/windows-ansi/0.0.6/windows-ansi-0.0.6-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/github/alexarchambault/windows-ansi/windows-ansi/0.0.6/windows-ansi-0.0.6-sources.jar";
      sha256 = "121FA106CB26F398D36BAF6D56CB145ADC2052923BF73AEC7A36C1035278194F";
    };
    "nix-public/io/github/alexarchambault/windows-ansi/windows-ansi/0.0.6/windows-ansi-0.0.6.jar" = {
      url = "https://repo1.maven.org/maven2/io/github/alexarchambault/windows-ansi/windows-ansi/0.0.6/windows-ansi-0.0.6.jar";
      sha256 = "077DBDBB977C94FC8B1FB82113CFB0AA5304D4E307C4E0688F69A9895F0DA482";
    };
    "nix-public/io/github/alexarchambault/windows-ansi/windows-ansi/0.0.6/windows-ansi-0.0.6.pom" = {
      url = "https://repo1.maven.org/maven2/io/github/alexarchambault/windows-ansi/windows-ansi/0.0.6/windows-ansi-0.0.6.pom";
      sha256 = "FE05E4478202C3DADD72E1FC0B66AA342462688D2E66114B4DD356BB0F011D5E";
    };
    "nix-public/io/spray/spray-json_2.12/1.3.6/spray-json-1.3.6-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/spray/spray-json_2.12/1.3.6/spray-json_2.12-1.3.6-sources.jar";
      sha256 = "B8B3B7F1E9362A1FB57FB5E7A43C299E94F09DDF7803AA514660573B2E524E30";
    };
    "nix-public/io/spray/spray-json_2.12/1.3.6/spray-json-1.3.6.jar" = {
      url = "https://repo1.maven.org/maven2/io/spray/spray-json_2.12/1.3.6/spray-json_2.12-1.3.6.jar";
      sha256 = "92E142B7B3EB7814C07027827C324D8DFB29846D5900A29DE842306722E12A91";
    };
    "nix-public/io/spray/spray-json_2.12/1.3.6/spray-json-1.3.6.pom" = {
      url = "https://repo1.maven.org/maven2/io/spray/spray-json_2.12/1.3.6/spray-json_2.12-1.3.6.pom";
      sha256 = "587437CF8CC04C6C6333E848E93447F010EB2CC9A9FFB11074A32E096164E4B7";
    };
    "nix-public/io/spray/spray-json_2.12/1.3.6/spray-json_2.12-1.3.6-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/spray/spray-json_2.12/1.3.6/spray-json_2.12-1.3.6-sources.jar";
      sha256 = "B8B3B7F1E9362A1FB57FB5E7A43C299E94F09DDF7803AA514660573B2E524E30";
    };
    "nix-public/io/spray/spray-json_2.12/1.3.6/spray-json_2.12-1.3.6.jar" = {
      url = "https://repo1.maven.org/maven2/io/spray/spray-json_2.12/1.3.6/spray-json_2.12-1.3.6.jar";
      sha256 = "92E142B7B3EB7814C07027827C324D8DFB29846D5900A29DE842306722E12A91";
    };
    "nix-public/io/spray/spray-json_2.12/1.3.6/spray-json_2.12-1.3.6.pom" = {
      url = "https://repo1.maven.org/maven2/io/spray/spray-json_2.12/1.3.6/spray-json_2.12-1.3.6.pom";
      sha256 = "587437CF8CC04C6C6333E848E93447F010EB2CC9A9FFB11074A32E096164E4B7";
    };
    "nix-public/javax/inject/javax.inject/1/javax.inject-1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/javax/inject/javax.inject/1/javax.inject-1-sources.jar";
      sha256 = "C4B87EE2911C139C3DAF498A781967F1EB2E75BC1A8529A2E7B328A15D0E433E";
    };
    "nix-public/javax/inject/javax.inject/1/javax.inject-1.jar" = {
      url = "https://repo1.maven.org/maven2/javax/inject/javax.inject/1/javax.inject-1.jar";
      sha256 = "91C77044A50C481636C32D916FD89C9118A72195390452C81065080F957DE7FF";
    };
    "nix-public/javax/inject/javax.inject/1/javax.inject-1.pom" = {
      url = "https://repo1.maven.org/maven2/javax/inject/javax.inject/1/javax.inject-1.pom";
      sha256 = "943E12B100627804638FA285805A0AB788A680266531E650921EBFE4621A8BFA";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6-sources.jar" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6-sources.jar";
      sha256 = "319A840705E1E46ABE579DD3D079B508558791E0236BC78DA01911748E06AF93";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6-tests.jar" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6-tests.jar";
      sha256 = "AE143A7DC135371F446A44775E8D5337D97151D5FEEC8CA8575F3A718DDF35F3";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6.jar" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6.jar";
      sha256 = "97D1ACAAC82409BE42E622D7A54D3AE9D08517E8AEFDEA3D2BA9791150C2F02D";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6.pom" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6.pom";
      sha256 = "1DF7B6F08DFB81A268D6B93B659A6A9E389C5D8C32BDF0754238BA6483A4E982";
    };
    "nix-public/log4j/log4j/1.2.12/log4j-1.2.12.jar" = {
      url = "https://repo1.maven.org/maven2/log4j/log4j/1.2.12/log4j-1.2.12.jar";
      sha256 = "DC67378CF428C06408E7959E83BDC1518DD22CCD313E7C28A986612D65C276C7";
    };
    "nix-public/log4j/log4j/1.2.12/log4j-1.2.12.pom" = {
      url = "https://repo1.maven.org/maven2/log4j/log4j/1.2.12/log4j-1.2.12.pom";
      sha256 = "CB54DEDC5D8C4510148DFA792701CBAC1A84C383A84F48F5A32E6D7E460BBB72";
    };
    "nix-public/net/bzzt/reproducible-builds-jvm-stripper/0.10/reproducible-builds-jvm-stripper-0.10-sources.jar" = {
      url = "https://repo1.maven.org/maven2/net/bzzt/reproducible-builds-jvm-stripper/0.10/reproducible-builds-jvm-stripper-0.10-sources.jar";
      sha256 = "16156780C2B817071FCB9A9AC32D6F5EBA756DCAEEA03FB85812E2073F6119A8";
    };
    "nix-public/net/bzzt/reproducible-builds-jvm-stripper/0.10/reproducible-builds-jvm-stripper-0.10.jar" = {
      url = "https://repo1.maven.org/maven2/net/bzzt/reproducible-builds-jvm-stripper/0.10/reproducible-builds-jvm-stripper-0.10.jar";
      sha256 = "6FF3B2EA22275A6907A975EBFE05753DA3FEE88F537AC68581E1E37EA1261295";
    };
    "nix-public/net/bzzt/reproducible-builds-jvm-stripper/0.10/reproducible-builds-jvm-stripper-0.10.pom" = {
      url = "https://repo1.maven.org/maven2/net/bzzt/reproducible-builds-jvm-stripper/0.10/reproducible-builds-jvm-stripper-0.10.pom";
      sha256 = "168151BEAC0489B955E345E9D594B526C2050470643074705BB49059B71A8206";
    };
    "nix-public/net/bzzt/sbt-reproducible-builds_2.12_1.0/0.32/sbt-reproducible-builds-0.32-sources.jar" = {
      url = "https://repo1.maven.org/maven2/net/bzzt/sbt-reproducible-builds_2.12_1.0/0.32/sbt-reproducible-builds_2.12_1.0-0.32-sources.jar";
      sha256 = "5E3DCE3FD6C7839E8BEB19175E71743F9ABD2EFA90209CC497725260324C8B1E";
    };
    "nix-public/net/bzzt/sbt-reproducible-builds_2.12_1.0/0.32/sbt-reproducible-builds-0.32.jar" = {
      url = "https://repo1.maven.org/maven2/net/bzzt/sbt-reproducible-builds_2.12_1.0/0.32/sbt-reproducible-builds_2.12_1.0-0.32.jar";
      sha256 = "EC95C0578CC15B9FB8D64BABCDE84FB938CDC67C5F1D07162FCFE171CE36CC7E";
    };
    "nix-public/net/bzzt/sbt-reproducible-builds_2.12_1.0/0.32/sbt-reproducible-builds-0.32.pom" = {
      url = "https://repo1.maven.org/maven2/net/bzzt/sbt-reproducible-builds_2.12_1.0/0.32/sbt-reproducible-builds_2.12_1.0-0.32.pom";
      sha256 = "6C7FFCA1123F9257CBDC8F6240B17A28F3AE86453459775F9051145A7C02CBD7";
    };
    "nix-public/net/bzzt/sbt-reproducible-builds_2.12_1.0/0.32/sbt-reproducible-builds_2.12_1.0-0.32-sources.jar" = {
      url = "https://repo1.maven.org/maven2/net/bzzt/sbt-reproducible-builds_2.12_1.0/0.32/sbt-reproducible-builds_2.12_1.0-0.32-sources.jar";
      sha256 = "5E3DCE3FD6C7839E8BEB19175E71743F9ABD2EFA90209CC497725260324C8B1E";
    };
    "nix-public/net/bzzt/sbt-reproducible-builds_2.12_1.0/0.32/sbt-reproducible-builds_2.12_1.0-0.32.jar" = {
      url = "https://repo1.maven.org/maven2/net/bzzt/sbt-reproducible-builds_2.12_1.0/0.32/sbt-reproducible-builds_2.12_1.0-0.32.jar";
      sha256 = "EC95C0578CC15B9FB8D64BABCDE84FB938CDC67C5F1D07162FCFE171CE36CC7E";
    };
    "nix-public/net/bzzt/sbt-reproducible-builds_2.12_1.0/0.32/sbt-reproducible-builds_2.12_1.0-0.32.pom" = {
      url = "https://repo1.maven.org/maven2/net/bzzt/sbt-reproducible-builds_2.12_1.0/0.32/sbt-reproducible-builds_2.12_1.0-0.32.pom";
      sha256 = "6C7FFCA1123F9257CBDC8F6240B17A28F3AE86453459775F9051145A7C02CBD7";
    };
    "nix-public/org/apache/ant/ant-launcher/1.10.15/ant-launcher-1.10.15-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/ant/ant-launcher/1.10.15/ant-launcher-1.10.15-sources.jar";
      sha256 = "AB774B88172F80BEB0E11E697ADBAB13E8436B4C959BEF51D5DBA44F1D192D72";
    };
    "nix-public/org/apache/ant/ant-launcher/1.10.15/ant-launcher-1.10.15.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/ant/ant-launcher/1.10.15/ant-launcher-1.10.15.jar";
      sha256 = "5C8551990307A032336D98DDAED549A39A689F07D4D4C6B950601BF22B3D6A1B";
    };
    "nix-public/org/apache/ant/ant-launcher/1.10.15/ant-launcher-1.10.15.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/ant/ant-launcher/1.10.15/ant-launcher-1.10.15.pom";
      sha256 = "79AF842A2979DC5FE0022BC073C498810EEAD83BC6283EEDF34DC4DFE30DAC95";
    };
    "nix-public/org/apache/ant/ant-parent/1.10.15/ant-parent-1.10.15.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/ant/ant-parent/1.10.15/ant-parent-1.10.15.pom";
      sha256 = "49884F1873C5107CC237F4285C4477479BB0804BF0737394801B08D75E2BBEB0";
    };
    "nix-public/org/apache/ant/ant/1.10.15/ant-1.10.15-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/ant/ant/1.10.15/ant-1.10.15-sources.jar";
      sha256 = "817EBF06C0A01D5D59CAE996815B154B7B7172D40D75304F39AB107E8133C0D6";
    };
    "nix-public/org/apache/ant/ant/1.10.15/ant-1.10.15.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/ant/ant/1.10.15/ant-1.10.15.jar";
      sha256 = "763ACDA4A69588C9EA8817A952851FF0C2FC4BFFA1D081C2565DC407F29D5794";
    };
    "nix-public/org/apache/ant/ant/1.10.15/ant-1.10.15.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/ant/ant/1.10.15/ant-1.10.15.pom";
      sha256 = "4780E61E87816EEE1F21D184EC997B65F93DB5F4B9042C178ADB29E23E7425D6";
    };
    "nix-public/org/apache/apache/19/apache-19.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/apache/19/apache-19.pom";
      sha256 = "91F7A33096EA69BAC2CBAF6D01FEB934CAC002C48D8C8CFA9C240B40F1EC21DF";
    };
    "nix-public/org/apache/apache/21/apache-21.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/apache/21/apache-21.pom";
      sha256 = "AF10C108DA014F17CAFAC7B52B2B4B5A3A1C18265FA2AF97A325D9143537B380";
    };
    "nix-public/org/apache/apache/30/apache-30.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/apache/30/apache-30.pom";
      sha256 = "63DD4A393A9C0DFCB314EFE83871A41D243BC8D200CBC7F2D197F30DA78239D8";
    };
    "nix-public/org/apache/apache/31/apache-31.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/apache/31/apache-31.pom";
      sha256 = "555D0C9EAA69C042AFF924927B9381E8F8174136D355EEAD445224452E6291CC";
    };
    "nix-public/org/apache/apache/35/apache-35.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/apache/35/apache-35.pom";
      sha256 = "EA297DCD114136E8B8E8B630230D52A76C2FC69F6C5DB25D672B1857000728B8";
    };
    "nix-public/org/apache/apache/6/apache-6.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/apache/6/apache-6.pom";
      sha256 = "12EDB5096E13F40C362D0BD40902589FA9586505123FA26799CE50B116FA5BB3";
    };
    "nix-public/org/apache/commons/commons-compress/1.25.0/commons-compress-1.25.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.25.0/commons-compress-1.25.0.jar";
      sha256 = "D0EC8014EBBB0749F471803122B21796AFDDF2E98E194E4374622E5FBAF69F49";
    };
    "nix-public/org/apache/commons/commons-compress/1.25.0/commons-compress-1.25.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.25.0/commons-compress-1.25.0.pom";
      sha256 = "BA5CDA496643A906FCB77B1F13C5C7DE817133C977A417E8A835FE28A6518ECE";
    };
    "nix-public/org/apache/commons/commons-compress/1.26.2/commons-compress-1.26.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.26.2/commons-compress-1.26.2.jar";
      sha256 = "9168A03141D8FC7EDA21A2360D83CC0412BCBB1D6204D992BD48C2573CB3C6B8";
    };
    "nix-public/org/apache/commons/commons-compress/1.26.2/commons-compress-1.26.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.26.2/commons-compress-1.26.2.pom";
      sha256 = "1428719895CD0A913AEE33E2424B9A804B10F1197E5D35A9CE99CF2A1174CB0E";
    };
    "nix-public/org/apache/commons/commons-compress/1.28.0/commons-compress-1.28.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.28.0/commons-compress-1.28.0-sources.jar";
      sha256 = "6DE9DE4559F12BBA6D41789C72F6A2A424514F2D2A3F7F49E2A3C52414DB9632";
    };
    "nix-public/org/apache/commons/commons-compress/1.28.0/commons-compress-1.28.0-tests.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.28.0/commons-compress-1.28.0-tests.jar";
      sha256 = "9FB3745275A3C327E2F0861D9D7F85D51838EE8C3041FEF2309B98C840472697";
    };
    "nix-public/org/apache/commons/commons-compress/1.28.0/commons-compress-1.28.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.28.0/commons-compress-1.28.0.jar";
      sha256 = "E1522945218456F3649A39BC4AFD70CE4BD466221519DBA7D378F2141A4642CA";
    };
    "nix-public/org/apache/commons/commons-compress/1.28.0/commons-compress-1.28.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.28.0/commons-compress-1.28.0.pom";
      sha256 = "033F4C78D632DA88D0EB8EAD974FC14A264392CEBF12AB6C68D6CEA7ADF0C64A";
    };
    "nix-public/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0.jar";
      sha256 = "7B96BF3EE68949ABB5BC465559AC270E0551596FA34523FDDF890EC418DDE13C";
    };
    "nix-public/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0.pom";
      sha256 = "110438863BAD37C28F906BF87016E38C7A8C758BA321E09D11DC5A2363A8E79E";
    };
    "nix-public/org/apache/commons/commons-lang3/3.18.0/commons-lang3-3.18.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.18.0/commons-lang3-3.18.0-sources.jar";
      sha256 = "B15732A13E40DF7F07C30F2CB8572874798E8DDE581F1398943D2AD3765BAFAA";
    };
    "nix-public/org/apache/commons/commons-lang3/3.18.0/commons-lang3-3.18.0-tests.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.18.0/commons-lang3-3.18.0-tests.jar";
      sha256 = "DB270729E3EA61246E04B5B070546457D2BDA4E570F3C8B70D07E76211C57F73";
    };
    "nix-public/org/apache/commons/commons-lang3/3.18.0/commons-lang3-3.18.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.18.0/commons-lang3-3.18.0.jar";
      sha256 = "4EEEAE8D20C078ABB64B015EC158ADD383AC581571CDDC45C68F0C9AE0230720";
    };
    "nix-public/org/apache/commons/commons-lang3/3.18.0/commons-lang3-3.18.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.18.0/commons-lang3-3.18.0.pom";
      sha256 = "AA254B373B6F6D46BC9DCA86331B072A8AB86EB25EA9921FD439618392E98A16";
    };
    "nix-public/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar";
      sha256 = "DAC807F65B07698FF39B1B07BFEF3D87AE3FD46D91BBF8A2BC02B2A831616F68";
    };
    "nix-public/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.pom";
      sha256 = "EC8E09F75411685205BD0D9D7872CC3622E67C76DF44A0A227B278BEA04458D5";
    };
    "nix-public/org/apache/commons/commons-parent/47/commons-parent-47.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-parent/47/commons-parent-47.pom";
      sha256 = "8A8ECB570553BF9F1FFAE211A8D4CA9EE630C17AFE59293368FBA7BD9B42FCB7";
    };
    "nix-public/org/apache/commons/commons-parent/64/commons-parent-64.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-parent/64/commons-parent-64.pom";
      sha256 = "6F19638994E8357B4ED734696F992057EFAAFA1235673998133299798E2CCDDB";
    };
    "nix-public/org/apache/commons/commons-parent/69/commons-parent-69.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-parent/69/commons-parent-69.pom";
      sha256 = "D50DA9C39BDCA823D618D1B4A03B73F196497FCB8616FD0DA727C8623592A9BB";
    };
    "nix-public/org/apache/commons/commons-parent/85/commons-parent-85.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-parent/85/commons-parent-85.pom";
      sha256 = "D189FF2C0027E96BB65D31E6F227ED2AF966169B36AF1E973DD5BA08926DC7B5";
    };
    "nix-public/org/apache/geronimo/genesis/genesis-default-flava/2.0/genesis-default-flava-2.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/geronimo/genesis/genesis-default-flava/2.0/genesis-default-flava-2.0.pom";
      sha256 = "08E6E146F4E245266DFF9DD800B12875DD2367D3F67A34AB660A126C811215F8";
    };
    "nix-public/org/apache/geronimo/genesis/genesis-java5-flava/2.0/genesis-java5-flava-2.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/geronimo/genesis/genesis-java5-flava/2.0/genesis-java5-flava-2.0.pom";
      sha256 = "E7C5358BBBBC27DAA5B327F63BC12650A75DDC9F9AC6D4BFA12789BE1F2C29DB";
    };
    "nix-public/org/apache/geronimo/genesis/genesis/2.0/genesis-2.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/geronimo/genesis/genesis/2.0/genesis-2.0.pom";
      sha256 = "B9ED2F9DD434631158D77308EE5648622C229CCECE1722C5E377A4296923DAE6";
    };
    "nix-public/org/apache/maven/maven-parent/33/maven-parent-33.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/maven/maven-parent/33/maven-parent-33.pom";
      sha256 = "3856E3FCD169502D5F12FE2452604EBF6C7C025F15656BFA558EA99ED29D73EA";
    };
    "nix-public/org/apache/maven/maven-plugin-api/3.6.0/maven-plugin-api-3.6.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/maven/maven-plugin-api/3.6.0/maven-plugin-api-3.6.0.jar";
      sha256 = "0062A08B463314A1B5F8EB1A56207EFB830FBDF547C42A3191EB146C4DB39B1A";
    };
    "nix-public/org/apache/maven/maven-plugin-api/3.6.0/maven-plugin-api-3.6.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/maven/maven-plugin-api/3.6.0/maven-plugin-api-3.6.0.pom";
      sha256 = "A276142112C24C121328A3D3C5C9925061D3C53B366636EA222A9828D29A2BB0";
    };
    "nix-public/org/apache/maven/maven/3.6.0/maven-3.6.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/maven/maven/3.6.0/maven-3.6.0.pom";
      sha256 = "EAA752A40E678961DFAE2D3E74EBDCD0A59BDF2931E1A8595A5E708729536A7D";
    };
    "nix-public/org/apache/xbean/xbean-reflect/3.7/xbean-reflect-3.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/xbean/xbean-reflect/3.7/xbean-reflect-3.7-sources.jar";
      sha256 = "ED59780DB1EE258D806C6DA541D74EF23FB9B05A5C96CC7F28E6FB203D2D4F9E";
    };
    "nix-public/org/apache/xbean/xbean-reflect/3.7/xbean-reflect-3.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/xbean/xbean-reflect/3.7/xbean-reflect-3.7.jar";
      sha256 = "104E5E9BB5A669F86722F32281960700F7EC8E3209EF51B23EB9B6D23D1629CB";
    };
    "nix-public/org/apache/xbean/xbean-reflect/3.7/xbean-reflect-3.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/xbean/xbean-reflect/3.7/xbean-reflect-3.7.pom";
      sha256 = "9795C15322C5D19AF336EEBD9E164FA7D5897C4B004A7D66E21635A173E748A9";
    };
    "nix-public/org/apache/xbean/xbean/3.7/xbean-3.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/xbean/xbean/3.7/xbean-3.7.pom";
      sha256 = "EA717132DE8404B62FC9097A1F3215C705D525D457BE9A5F12653ADC68C33AB7";
    };
    "nix-public/org/codehaus/plexus/plexus-archiver/4.10.0/plexus-archiver-4.10.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-archiver/4.10.0/plexus-archiver-4.10.0-sources.jar";
      sha256 = "8559ED68292E11228D36155C0932AE3F54D743F7A19AD5CE51E253A52D6499C8";
    };
    "nix-public/org/codehaus/plexus/plexus-archiver/4.10.0/plexus-archiver-4.10.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-archiver/4.10.0/plexus-archiver-4.10.0.jar";
      sha256 = "4C07814FF4A39199999AE82BBA1E38AA4F25637467FCAC6A66ED63A76535799A";
    };
    "nix-public/org/codehaus/plexus/plexus-archiver/4.10.0/plexus-archiver-4.10.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-archiver/4.10.0/plexus-archiver-4.10.0.pom";
      sha256 = "93CA001FD33DA53D38B74F6DAF19E71BC9736ED6143091FF9003CD4C05ACE6C9";
    };
    "nix-public/org/codehaus/plexus/plexus-classworlds/2.6.0/plexus-classworlds-2.6.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-classworlds/2.6.0/plexus-classworlds-2.6.0-sources.jar";
      sha256 = "A9DC469D6D1AD442D6661E677614BD102B5FCF30A27D55533EF05AF7807CAB89";
    };
    "nix-public/org/codehaus/plexus/plexus-classworlds/2.6.0/plexus-classworlds-2.6.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-classworlds/2.6.0/plexus-classworlds-2.6.0.jar";
      sha256 = "52F77C5EC49F787C9C417EBED5D6EFD9922F44A202F217376E4F94C0D74F3549";
    };
    "nix-public/org/codehaus/plexus/plexus-classworlds/2.6.0/plexus-classworlds-2.6.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-classworlds/2.6.0/plexus-classworlds-2.6.0.pom";
      sha256 = "469A6C59F92EFFA62C0797CE7D52D2C03CF8EE1034B923C360DD78A9F505A7BA";
    };
    "nix-public/org/codehaus/plexus/plexus-container-default/2.1.1/plexus-container-default-2.1.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-container-default/2.1.1/plexus-container-default-2.1.1-sources.jar";
      sha256 = "9356606244FB5E6E19F5DB845D8C09BD62DD74AC8444251740968B6241DFAE8F";
    };
    "nix-public/org/codehaus/plexus/plexus-container-default/2.1.1/plexus-container-default-2.1.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-container-default/2.1.1/plexus-container-default-2.1.1.jar";
      sha256 = "8B65840E41CA669A1A69EC1DAEDB3426304E560B24172CC93BB02E8C199E1CE7";
    };
    "nix-public/org/codehaus/plexus/plexus-container-default/2.1.1/plexus-container-default-2.1.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-container-default/2.1.1/plexus-container-default-2.1.1.pom";
      sha256 = "0F5C6E592459262FC34942C2F4DF370230EC2765DD4B707F54C269FDF5C5A7E3";
    };
    "nix-public/org/codehaus/plexus/plexus-containers/2.1.1/plexus-containers-2.1.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-containers/2.1.1/plexus-containers-2.1.1.pom";
      sha256 = "C129AE94BC6DE8BA2596FCDAD4B3FCFE4F67640A4CB6D76A5540182214AA833C";
    };
    "nix-public/org/codehaus/plexus/plexus-io/3.5.0/plexus-io-3.5.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-io/3.5.0/plexus-io-3.5.0-sources.jar";
      sha256 = "C2505097B5F1493A65B83252176008C887FAFA502198DE04293DC9276C50EFAA";
    };
    "nix-public/org/codehaus/plexus/plexus-io/3.5.0/plexus-io-3.5.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-io/3.5.0/plexus-io-3.5.0.jar";
      sha256 = "965ED28912CF1AE4C628112C4009E0C19819BC44ED5DB8AF54EE5EDA21036A3E";
    };
    "nix-public/org/codehaus/plexus/plexus-io/3.5.0/plexus-io-3.5.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-io/3.5.0/plexus-io-3.5.0.pom";
      sha256 = "F5B86CD223A0BF4BA649DE19E7E8E4E1F14344FF636F8B0024C89C46D28CC9D8";
    };
    "nix-public/org/codehaus/plexus/plexus-utils/3.4.2/plexus-utils-3.4.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-utils/3.4.2/plexus-utils-3.4.2.jar";
      sha256 = "F957F13604EA1686DE805801862F339DBBB6EAB9A66F9CC7E4A5C5B27E4FCECC";
    };
    "nix-public/org/codehaus/plexus/plexus-utils/3.4.2/plexus-utils-3.4.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-utils/3.4.2/plexus-utils-3.4.2.pom";
      sha256 = "0515626F5ABAA0BDB5AD87D291953EAE358B97E2D10D6ECAB84ACA0D486063BF";
    };
    "nix-public/org/codehaus/plexus/plexus-utils/4.0.1/plexus-utils-4.0.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-utils/4.0.1/plexus-utils-4.0.1-sources.jar";
      sha256 = "AFE1A6B22D68B06ECD0CFCD1B2F881762C1FA4912ACE3F1B002A38EE62765331";
    };
    "nix-public/org/codehaus/plexus/plexus-utils/4.0.1/plexus-utils-4.0.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-utils/4.0.1/plexus-utils-4.0.1.jar";
      sha256 = "96B9CC44439191D2D0635974E2D44E768736B4FB2ABCB65F94CD95E41912FA8B";
    };
    "nix-public/org/codehaus/plexus/plexus-utils/4.0.1/plexus-utils-4.0.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-utils/4.0.1/plexus-utils-4.0.1.pom";
      sha256 = "BC4235A95CD1EBAE42644C81EBBA9C1D4C52565F81E96AB204B6E56E3E378CC1";
    };
    "nix-public/org/codehaus/plexus/plexus/17/plexus-17.pom" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus/17/plexus-17.pom";
      sha256 = "91526EE66327C7F50FBB25BD41BFCB916E284414B868E31D50A23004BD7DEEA7";
    };
    "nix-public/org/codehaus/plexus/plexus/18/plexus-18.pom" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus/18/plexus-18.pom";
      sha256 = "B43EE89C8890B9E5BC48D079FCB4C44F082B5139253356DC455806A33C3DD8FD";
    };
    "nix-public/org/codehaus/plexus/plexus/5.1/plexus-5.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus/5.1/plexus-5.1.pom";
      sha256 = "A343E44FF5796AED0EA60BE11454C935CE20AB1C5F164ACC8DA574482DCBC7E9";
    };
    "nix-public/org/codehaus/plexus/plexus/6.5/plexus-6.5.pom" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus/6.5/plexus-6.5.pom";
      sha256 = "737FF2200498DD54C920712404CAA4426D38639D05014FF3EF1B3E7C5BD91397";
    };
    "nix-public/org/codehaus/plexus/plexus/8/plexus-8.pom" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus/8/plexus-8.pom";
      sha256 = "FFA349DB04E7ABF65885BDC5A2062F4197C0FF9D3F1F4E2AA5720B77233F742C";
    };
    "nix-public/org/fusesource/fusesource-pom/1.12/fusesource-pom-1.12.pom" = {
      url = "https://repo1.maven.org/maven2/org/fusesource/fusesource-pom/1.12/fusesource-pom-1.12.pom";
      sha256 = "C40D960DAADCEF7B01C1B1C6657AFBAC4FFFB5E53168F8FCB0B28B84E6FDCCA1";
    };
    "nix-public/org/fusesource/jansi/jansi/2.4.1/jansi-2.4.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/2.4.1/jansi-2.4.1-sources.jar";
      sha256 = "F707511567A13EBF8C51164133770EB5A8E023E1D391BFBC6E7A0591C71729B8";
    };
    "nix-public/org/fusesource/jansi/jansi/2.4.1/jansi-2.4.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/2.4.1/jansi-2.4.1.jar";
      sha256 = "2E5E775A9DC58FFA6BBD6AA6F099D62F8B62DCDEB4C3C3BBBE5CF2301BC2DCC1";
    };
    "nix-public/org/fusesource/jansi/jansi/2.4.1/jansi-2.4.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/2.4.1/jansi-2.4.1.pom";
      sha256 = "3F98D979A4D3559F8779FBB004B34AE7516AFADF510E11DF7CC3CD073EB1BB3B";
    };
    "nix-public/org/junit/junit-bom/5.10.0/junit-bom-5.10.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/junit/junit-bom/5.10.0/junit-bom-5.10.0.pom";
      sha256 = "E006DD8894F9FC7B75FC32BB12FE5ED8BE65667D5B454F99E2E0B8C5BB8D30B3";
    };
    "nix-public/org/junit/junit-bom/5.10.2/junit-bom-5.10.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/junit/junit-bom/5.10.2/junit-bom-5.10.2.pom";
      sha256 = "169DD904A4B0F6520CFFE658CC62292BFE9F3C14A989FA92120724CDE43A9968";
    };
    "nix-public/org/junit/junit-bom/5.13.1/junit-bom-5.13.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/junit/junit-bom/5.13.1/junit-bom-5.13.1.pom";
      sha256 = "FA68451EA830572ED43FFE51D75B6A05F7A5E665A602A51F49D6BE02063A65F3";
    };
    "nix-public/org/junit/junit-bom/5.8.0-M1/junit-bom-5.8.0-M1.pom" = {
      url = "https://repo1.maven.org/maven2/org/junit/junit-bom/5.8.0-M1/junit-bom-5.8.0-M1.pom";
      sha256 = "77144432FFC68BD98A790AB1069619D91032CFC0E4E13C08163AA03DA36FD6E2";
    };
    "nix-public/org/ow2/asm/asm-commons/9.6/asm-commons-9.6.jar" = {
      url = "https://repo1.maven.org/maven2/org/ow2/asm/asm-commons/9.6/asm-commons-9.6.jar";
      sha256 = "7AEFD0D5C0901701C69F7513FEDA765FB6BE33AF2CE7AA17C5781FC87657C511";
    };
    "nix-public/org/ow2/asm/asm-commons/9.6/asm-commons-9.6.pom" = {
      url = "https://repo1.maven.org/maven2/org/ow2/asm/asm-commons/9.6/asm-commons-9.6.pom";
      sha256 = "A98AE4895334BAF8FF86BD66516210DBD9A03F1A6E15E47DDA82AFCF6B53D77C";
    };
    "nix-public/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.jar" = {
      url = "https://repo1.maven.org/maven2/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.jar";
      sha256 = "C43ECF17B539C777E15DA7B5B86553B377E2D39A683DE6285567D5283888E7EF";
    };
    "nix-public/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.pom" = {
      url = "https://repo1.maven.org/maven2/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.pom";
      sha256 = "1BCB481D7FC16B955BB60CA07C8CFA2424BCEE78BDC405BBA31C7D6F5DC2D113";
    };
    "nix-public/org/ow2/asm/asm/9.6/asm-9.6.jar" = {
      url = "https://repo1.maven.org/maven2/org/ow2/asm/asm/9.6/asm-9.6.jar";
      sha256 = "3C6FAC2424DB3D4A853B669F4E3D1D9C3C552235E19A319673F887083C2303A1";
    };
    "nix-public/org/ow2/asm/asm/9.6/asm-9.6.pom" = {
      url = "https://repo1.maven.org/maven2/org/ow2/asm/asm/9.6/asm-9.6.pom";
      sha256 = "92EEE24BC3C843E4881D46C1DD6505471EE3142FACFB466B428CFEA5A56C6B60";
    };
    "nix-public/org/ow2/asm/asm/9.8/asm-9.8.jar" = {
      url = "https://repo1.maven.org/maven2/org/ow2/asm/asm/9.8/asm-9.8.jar";
      sha256 = "876EAB6A83DAECAD5CA67EB9FCABB063C97B5AEB8CF1FCA7A989ECDE17522051";
    };
    "nix-public/org/ow2/asm/asm/9.8/asm-9.8.pom" = {
      url = "https://repo1.maven.org/maven2/org/ow2/asm/asm/9.8/asm-9.8.pom";
      sha256 = "C1367C3BB383D7619E7F797E38DF7513885F2EEF04AE7B5908F68222657B5BAA";
    };
    "nix-public/org/ow2/ow2/1.5.1/ow2-1.5.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/ow2/ow2/1.5.1/ow2-1.5.1.pom";
      sha256 = "321DDBB7EE6FE4F53DEA6B4CD6DB74154D6BFA42391C1F763B361B9F485ACF05";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.12/2.11.0/scala-collection-compat-2.11.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.12/2.11.0/scala-collection-compat_2.12-2.11.0.jar";
      sha256 = "7BF170604A148A342C7D1B1C7D181DD41E9C60B7B459DD49B2BCF12BE69EA675";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.12/2.11.0/scala-collection-compat-2.11.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.12/2.11.0/scala-collection-compat_2.12-2.11.0.pom";
      sha256 = "FFCFEE77D98AF426C1B0481D0093CA626C045625764E31EA916E03C527635387";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.12/2.11.0/scala-collection-compat_2.12-2.11.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.12/2.11.0/scala-collection-compat_2.12-2.11.0.jar";
      sha256 = "7BF170604A148A342C7D1B1C7D181DD41E9C60B7B459DD49B2BCF12BE69EA675";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.12/2.11.0/scala-collection-compat_2.12-2.11.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.12/2.11.0/scala-collection-compat_2.12-2.11.0.pom";
      sha256 = "FFCFEE77D98AF426C1B0481D0093CA626C045625764E31EA916E03C527635387";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.12/2.12.0/scala-collection-compat-2.12.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.12/2.12.0/scala-collection-compat_2.12-2.12.0-sources.jar";
      sha256 = "96A9B593330C8B0FE82D2E269BD8E6B46DD9EBA5532F0C06D01DAB2F87665E87";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.12/2.12.0/scala-collection-compat-2.12.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.12/2.12.0/scala-collection-compat_2.12-2.12.0.jar";
      sha256 = "1619C5E4399E1E4793667970AAE232652DB0549E795C90ABF91E44C55EC37CB3";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.12/2.12.0/scala-collection-compat-2.12.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.12/2.12.0/scala-collection-compat_2.12-2.12.0.pom";
      sha256 = "02C3511378C3A0568F4B1B150A385637AF86BCF5F8CAB642F28B71622BF9ED4B";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.12/2.12.0/scala-collection-compat_2.12-2.12.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.12/2.12.0/scala-collection-compat_2.12-2.12.0-sources.jar";
      sha256 = "96A9B593330C8B0FE82D2E269BD8E6B46DD9EBA5532F0C06D01DAB2F87665E87";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.12/2.12.0/scala-collection-compat_2.12-2.12.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.12/2.12.0/scala-collection-compat_2.12-2.12.0.jar";
      sha256 = "1619C5E4399E1E4793667970AAE232652DB0549E795C90ABF91E44C55EC37CB3";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.12/2.12.0/scala-collection-compat_2.12-2.12.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.12/2.12.0/scala-collection-compat_2.12-2.12.0.pom";
      sha256 = "02C3511378C3A0568F4B1B150A385637AF86BCF5F8CAB642F28B71622BF9ED4B";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators-1.1.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2-sources.jar";
      sha256 = "8FBE3FA9E748F24AA6D6868C0C2BE30D41A02D20428ED5429BB57A897CB756E3";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators-1.1.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2.jar";
      sha256 = "24985EB43E295A9DD77905ADA307A850CA25ACF819CDB579C093FC6987B0DBC2";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators-1.1.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2.pom";
      sha256 = "A5500678F39B9B8C962A8FEE98359E9E2F2A4E5D434F3501762B30188642A2F5";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2-sources.jar";
      sha256 = "8FBE3FA9E748F24AA6D6868C0C2BE30D41A02D20428ED5429BB57A897CB756E3";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2.jar";
      sha256 = "24985EB43E295A9DD77905ADA307A850CA25ACF819CDB579C093FC6987B0DBC2";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2.pom";
      sha256 = "A5500678F39B9B8C962A8FEE98359E9E2F2A4E5D434F3501762B30188642A2F5";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.2.0/scala-xml-2.2.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.2.0/scala-xml_2.12-2.2.0.jar";
      sha256 = "FD92F78B7ACFEA72999ACEBA5B377A000F42F9296D3D98224C9B1C471815582F";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.2.0/scala-xml-2.2.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.2.0/scala-xml_2.12-2.2.0.pom";
      sha256 = "81B0510AB4A86724912246E0E18F3988A7086BDE716D819CA7F937474BAC34AC";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.2.0/scala-xml_2.12-2.2.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.2.0/scala-xml_2.12-2.2.0.jar";
      sha256 = "FD92F78B7ACFEA72999ACEBA5B377A000F42F9296D3D98224C9B1C471815582F";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.2.0/scala-xml_2.12-2.2.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.2.0/scala-xml_2.12-2.2.0.pom";
      sha256 = "81B0510AB4A86724912246E0E18F3988A7086BDE716D819CA7F937474BAC34AC";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml-2.3.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0-sources.jar";
      sha256 = "BB93B2FDCD36EBD3E7E6E6DE961CD2A4EAD3815C9565C7BE5CAD860CF3D8C81C";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml-2.3.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0.jar";
      sha256 = "4932C56A2D5AAE77AE8D7AC6BED1F21D48268FDBAC8B4E5F3CA5196AD10FD93E";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml-2.3.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0.pom";
      sha256 = "45BC645F881F34E6338B478007C6DD93D17389A4F4138616AE7EFA854BAAAA46";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0-sources.jar";
      sha256 = "BB93B2FDCD36EBD3E7E6E6DE961CD2A4EAD3815C9565C7BE5CAD860CF3D8C81C";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0.jar";
      sha256 = "4932C56A2D5AAE77AE8D7AC6BED1F21D48268FDBAC8B4E5F3CA5196AD10FD93E";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0.pom";
      sha256 = "45BC645F881F34E6338B478007C6DD93D17389A4F4138616AE7EFA854BAAAA46";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.20/scala-compiler-2.12.20.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.20/scala-compiler-2.12.20.jar";
      sha256 = "C88676D75C69721B717EA6C441ECE04FFF262ABAB9D210A2936ABC2BE3731FA2";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.20/scala-compiler-2.12.20.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.20/scala-compiler-2.12.20.pom";
      sha256 = "D04B837110423B145973F9A6516AB6AFD9C09C50543B8C7C63AC6C90AD4CCAA3";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.21/scala-compiler-2.12.21.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.21/scala-compiler-2.12.21.pom";
      sha256 = "4253340C4791B50E487EBEBC35832E412279A6A6743D92948904166147FBEAEA";
    };
    "nix-public/org/scala-lang/scala-library/2.12.15/scala-library-2.12.15.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.15/scala-library-2.12.15.jar";
      sha256 = "E518BB640E2175DE5CB1F8E326679B8D975376221F1B547757DE429BBF4563F0";
    };
    "nix-public/org/scala-lang/scala-library/2.12.15/scala-library-2.12.15.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.15/scala-library-2.12.15.pom";
      sha256 = "4F3AAE4C7F93BBE5AFCDBED7B6AB560CEC3AA3B465095F318534E11597901E89";
    };
    "nix-public/org/scala-lang/scala-library/2.12.17/scala-library-2.12.17.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.17/scala-library-2.12.17.jar";
      sha256 = "7EEFDE7E3CC1937F78DC13B9E6C00746F602CFF6F5621D62DF2C24D922619FE0";
    };
    "nix-public/org/scala-lang/scala-library/2.12.17/scala-library-2.12.17.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.17/scala-library-2.12.17.pom";
      sha256 = "0DEDE34FD83E05FE15D226000D209D57249BB9D280B00C8735E783FCCEECDBB5";
    };
    "nix-public/org/scala-lang/scala-library/2.12.18/scala-library-2.12.18.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.18/scala-library-2.12.18.jar";
      sha256 = "E51E6636C003359E106BEA4AD99DEF70E613C290190C8C84F10F9560DD5B00AE";
    };
    "nix-public/org/scala-lang/scala-library/2.12.18/scala-library-2.12.18.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.18/scala-library-2.12.18.pom";
      sha256 = "C7BCAE55EB71211DCB3305FD5EAFF1ADD551C53A8B6173C1C02D800C6EACF097";
    };
    "nix-public/org/scala-lang/scala-library/2.12.19/scala-library-2.12.19.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.19/scala-library-2.12.19.jar";
      sha256 = "81E32F8E31236EF84C21287F1FBAA916FC6525B2E63220D4A0F2396E91871D50";
    };
    "nix-public/org/scala-lang/scala-library/2.12.19/scala-library-2.12.19.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.19/scala-library-2.12.19.pom";
      sha256 = "C5646BBD1A8EE70A49DB017312ECDC1AF2B5602EC0106C43F8B8A9714CFACB54";
    };
    "nix-public/org/scala-lang/scala-library/2.12.20/scala-library-2.12.20.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.20/scala-library-2.12.20.jar";
      sha256 = "4D8A8F984CCE31A329A24F10B0BF336F042CB62AEB435290A1B20243154CFCCB";
    };
    "nix-public/org/scala-lang/scala-library/2.12.20/scala-library-2.12.20.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.20/scala-library-2.12.20.pom";
      sha256 = "94C315B4C51A4C8D0A33F177E160DDAD63B68595FEB3997FA25791C5A14A03C9";
    };
    "nix-public/org/scala-lang/scala-library/2.12.21/scala-library-2.12.21.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.21/scala-library-2.12.21.jar";
      sha256 = "E2F4040C95CC4DD1CFEAAE38BDDE596E4B36933632451EFA7D8564C6A359510C";
    };
    "nix-public/org/scala-lang/scala-library/2.12.21/scala-library-2.12.21.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.21/scala-library-2.12.21.pom";
      sha256 = "F0CB22ADB1668EDE4B19E273096E9D97CD35F9864C7F28B5A2E5C21E08CA6847";
    };
    "nix-public/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.jar";
      sha256 = "321FB55685635C931EBA4BC0D7668349DA3F2C09AEE2DE93A70566066FF25C28";
    };
    "nix-public/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.pom";
      sha256 = "22E81EE9D5349BA0E897ADB5C7FCEC25656C9E0B7B86C3E93E9A7AF360481C0D";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.18/scala-reflect-2.12.18.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.18/scala-reflect-2.12.18.pom";
      sha256 = "8D662CC9AC08302359B7A962622C58E79A44011F43DE0ED131D289FCA6F86EBD";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.20/scala-reflect-2.12.20.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.20/scala-reflect-2.12.20.jar";
      sha256 = "5F1914CDC7A70580EA6038D929EBB25736ECF2234F677E2D47F8A4B2BC81E1FB";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.20/scala-reflect-2.12.20.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.20/scala-reflect-2.12.20.pom";
      sha256 = "6151C44B5EC49F7E9555450D6ACE47E994129B511119CF364045E18864AF8E96";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.21/scala-reflect-2.12.21.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.21/scala-reflect-2.12.21.jar";
      sha256 = "8B91A08BA69A0564689793E732F06768D0914EC9E90FA8C3D1B55C5BF4600C14";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.21/scala-reflect-2.12.21.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.21/scala-reflect-2.12.21.pom";
      sha256 = "66DC35AA4123EFD8A550B963D82FDFA2BAD17878D627647E39967ACB4B7B4167";
    };
    "nix-public/org/scala-sbt/io_2.12/1.10.5/io-1.10.5.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/io_2.12/1.10.5/io_2.12-1.10.5.jar";
      sha256 = "BF14838437830C41335068F51CBE4BE4CEAA062C795073E3971889A82DF9DA0B";
    };
    "nix-public/org/scala-sbt/io_2.12/1.10.5/io-1.10.5.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/io_2.12/1.10.5/io_2.12-1.10.5.pom";
      sha256 = "5188CA1797EEC2703ABECCDBC0B9CBF13EB9C8D3FBB7F1A6EA1A4DABFB6DC311";
    };
    "nix-public/org/scala-sbt/io_2.12/1.10.5/io_2.12-1.10.5.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/io_2.12/1.10.5/io_2.12-1.10.5.jar";
      sha256 = "BF14838437830C41335068F51CBE4BE4CEAA062C795073E3971889A82DF9DA0B";
    };
    "nix-public/org/scala-sbt/io_2.12/1.10.5/io_2.12-1.10.5.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/io_2.12/1.10.5/io_2.12-1.10.5.pom";
      sha256 = "5188CA1797EEC2703ABECCDBC0B9CBF13EB9C8D3FBB7F1A6EA1A4DABFB6DC311";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36-sources.jar";
      sha256 = "15BC04357A3725B7A5153F132DB71379F95E83B7B8590A86CC6D4AD77BFC150A";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36-tests.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36-tests.jar";
      sha256 = "EF8E69388790DE8D61DB8C6283A85A26AB4659BEA608B6AF576EE89F2AF91879";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.jar";
      sha256 = "D3EF575E3E4979678DC01BF1DCCE51021493B4D11FB7F1BE8AD982877C16A1C0";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.pom";
      sha256 = "FB046A9C229437928BB11C2D27C8B5D773EB8A25E60CBD253D985210DEDC2684";
    };
    "nix-public/org/slf4j/slf4j-parent/1.7.36/slf4j-parent-1.7.36.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.7.36/slf4j-parent-1.7.36.pom";
      sha256 = "BB388D37FBCDD3CDE64C3CEDE21838693218DC451F04040C5DF360A78ED7E812";
    };
    "nix-public/org/sonatype/oss/oss-parent/7/oss-parent-7.pom" = {
      url = "https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/7/oss-parent-7.pom";
      sha256 = "B51F8867C92B6A722499557FC3A1FDEA77BDF9EF574722FE90CE436A29559454";
    };
    "nix-public/org/sonatype/oss/oss-parent/9/oss-parent-9.pom" = {
      url = "https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom";
      sha256 = "FB40265F982548212FF82E362E59732B2187EC6F0D80182885C14EF1F982827A";
    };
    "nix-public/org/tukaani/xz/1.10/xz-1.10.jar" = {
      url = "https://repo1.maven.org/maven2/org/tukaani/xz/1.10/xz-1.10.jar";
      sha256 = "95C63C1A55B22DD6453890A419CC1A640F790BBF7D8AE82DB1E30AEFEFB08888";
    };
    "nix-public/org/tukaani/xz/1.10/xz-1.10.pom" = {
      url = "https://repo1.maven.org/maven2/org/tukaani/xz/1.10/xz-1.10.pom";
      sha256 = "EF608B83C3BB6C8E3E6B3BEAA38842BA15963B46495E4AF91B0746C8B750F3B9";
    };
    "nix-public/org/tukaani/xz/1.9/xz-1.9-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/tukaani/xz/1.9/xz-1.9-sources.jar";
      sha256 = "5BEFA47F06B90E752F035191DDE7F2DEB59F36000F1CA6CC77D2362A82B6F462";
    };
    "nix-public/org/tukaani/xz/1.9/xz-1.9.jar" = {
      url = "https://repo1.maven.org/maven2/org/tukaani/xz/1.9/xz-1.9.jar";
      sha256 = "211B306CFC44F8F96DF3A0A3DDAF75BA8C5289EED77D60D72F889BB855F535E5";
    };
    "nix-public/org/tukaani/xz/1.9/xz-1.9.pom" = {
      url = "https://repo1.maven.org/maven2/org/tukaani/xz/1.9/xz-1.9.pom";
      sha256 = "093BE1B03331BCE2932D6825C37E98272D7621E6A9E9FB93289A002518B8DD5A";
    };
    "nix-public/org/virtuslab/scala-cli/config_2.12/1.1.3/config-1.1.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/virtuslab/scala-cli/config_2.12/1.1.3/config_2.12-1.1.3-sources.jar";
      sha256 = "E68CA512545BDC259E2F101E92A65D080C87D99176D0F8A151954A7074BB7E23";
    };
    "nix-public/org/virtuslab/scala-cli/config_2.12/1.1.3/config-1.1.3.jar" = {
      url = "https://repo1.maven.org/maven2/org/virtuslab/scala-cli/config_2.12/1.1.3/config_2.12-1.1.3.jar";
      sha256 = "D7B41D6AAC1052FF9D7E7F90E756AFB7DD3A562C78C78FAF4BA9D75232DD9454";
    };
    "nix-public/org/virtuslab/scala-cli/config_2.12/1.1.3/config-1.1.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/virtuslab/scala-cli/config_2.12/1.1.3/config_2.12-1.1.3.pom";
      sha256 = "2521AE10399C0FD88F2467B13E65229AEE8A17AA4AD03B9344CB1608D6680280";
    };
    "nix-public/org/virtuslab/scala-cli/config_2.12/1.1.3/config_2.12-1.1.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/virtuslab/scala-cli/config_2.12/1.1.3/config_2.12-1.1.3-sources.jar";
      sha256 = "E68CA512545BDC259E2F101E92A65D080C87D99176D0F8A151954A7074BB7E23";
    };
    "nix-public/org/virtuslab/scala-cli/config_2.12/1.1.3/config_2.12-1.1.3.jar" = {
      url = "https://repo1.maven.org/maven2/org/virtuslab/scala-cli/config_2.12/1.1.3/config_2.12-1.1.3.jar";
      sha256 = "D7B41D6AAC1052FF9D7E7F90E756AFB7DD3A562C78C78FAF4BA9D75232DD9454";
    };
    "nix-public/org/virtuslab/scala-cli/config_2.12/1.1.3/config_2.12-1.1.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/virtuslab/scala-cli/config_2.12/1.1.3/config_2.12-1.1.3.pom";
      sha256 = "2521AE10399C0FD88F2467B13E65229AEE8A17AA4AD03B9344CB1608D6680280";
    };
    "nix-public/org/virtuslab/scala-cli/specification-level_2.12/1.1.3/specification-level-1.1.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/virtuslab/scala-cli/specification-level_2.12/1.1.3/specification-level_2.12-1.1.3-sources.jar";
      sha256 = "50138A16137ADD84B1E145E9F89F2BAFE32955DF99A09FD360CA16FC14CA86E1";
    };
    "nix-public/org/virtuslab/scala-cli/specification-level_2.12/1.1.3/specification-level-1.1.3.jar" = {
      url = "https://repo1.maven.org/maven2/org/virtuslab/scala-cli/specification-level_2.12/1.1.3/specification-level_2.12-1.1.3.jar";
      sha256 = "A4748FE8A15594AACFBDB30F1941A78C56D814B482BBE7ABC49EF4F206E780AD";
    };
    "nix-public/org/virtuslab/scala-cli/specification-level_2.12/1.1.3/specification-level-1.1.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/virtuslab/scala-cli/specification-level_2.12/1.1.3/specification-level_2.12-1.1.3.pom";
      sha256 = "7CF8FD511D796D5F6E1C398A2E263308A8B09C0B7B641B46E3B8E58F5D9FFA5B";
    };
    "nix-public/org/virtuslab/scala-cli/specification-level_2.12/1.1.3/specification-level_2.12-1.1.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/virtuslab/scala-cli/specification-level_2.12/1.1.3/specification-level_2.12-1.1.3-sources.jar";
      sha256 = "50138A16137ADD84B1E145E9F89F2BAFE32955DF99A09FD360CA16FC14CA86E1";
    };
    "nix-public/org/virtuslab/scala-cli/specification-level_2.12/1.1.3/specification-level_2.12-1.1.3.jar" = {
      url = "https://repo1.maven.org/maven2/org/virtuslab/scala-cli/specification-level_2.12/1.1.3/specification-level_2.12-1.1.3.jar";
      sha256 = "A4748FE8A15594AACFBDB30F1941A78C56D814B482BBE7ABC49EF4F206E780AD";
    };
    "nix-public/org/virtuslab/scala-cli/specification-level_2.12/1.1.3/specification-level_2.12-1.1.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/virtuslab/scala-cli/specification-level_2.12/1.1.3/specification-level_2.12-1.1.3.pom";
      sha256 = "7CF8FD511D796D5F6E1C398A2E263308A8B09C0B7B641B46E3B8E58F5D9FFA5B";
    };
  };
}