# This file was automatically generated by Sbtix. Do not edit manually.
{
  "versioning" = [{
      "scalaVersion" = "2.12.20";
      "sbtVersion" = "1.10.7";
    }
    {
      "scalaVersion" = "2.13.16";
      "sbtVersion" = "1.10.7";
    }];
  "repos" = {
    "nix-public" = "";
  };
  "artifacts" = {
    "nix-public/com/typesafe/config/1.3.2/config-1.3.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.3.2/config-1.3.2-javadoc.jar";
      sha256 = "57619C3DC0DC23DC74F0B1E14DEE7C87C5118B6700ECFE7400D2742D091C099F";
    };
    "nix-public/com/typesafe/config/1.3.2/config-1.3.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.3.2/config-1.3.2-sources.jar";
      sha256 = "65995ABD56D6AA99EE7F46E7CDAAAAC2968554B16B26D38BF67E13706A12CA82";
    };
    "nix-public/com/typesafe/config/1.3.2/config-1.3.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.3.2/config-1.3.2.jar";
      sha256 = "6563D1723F3300BF596F41E40BC03E54986108B5C45D0AC34EBC66D48C2E25A3";
    };
    "nix-public/com/typesafe/config/1.3.2/config-1.3.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.3.2/config-1.3.2.pom";
      sha256 = "07EE48EC393761693CB95E2D1778CCAF3AD680312E94EB27C0059B8E06C98DBA";
    };
    "nix-public/com/typesafe/slick/slick_2.12/3.3.3/slick_2.12-3.3.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/slick/slick_2.12/3.3.3/slick_2.12-3.3.3-javadoc.jar";
      sha256 = "B9CFD22F1A4F63D1D9C595880CD75770FDD3D058796E2917784FF7F563A6327B";
    };
    "nix-public/com/typesafe/slick/slick_2.12/3.3.3/slick_2.12-3.3.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/slick/slick_2.12/3.3.3/slick_2.12-3.3.3-sources.jar";
      sha256 = "716BA0A5F45549D1F4D46907624BEBBCF8238B6D2AD57A11DECE64A53F85F63F";
    };
    "nix-public/com/typesafe/slick/slick_2.12/3.3.3/slick_2.12-3.3.3.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/slick/slick_2.12/3.3.3/slick_2.12-3.3.3.jar";
      sha256 = "65EC5E8E62DB2CFABE47205C149ABF191951780F0D74B772D22BE1D1F16DFE21";
    };
    "nix-public/com/typesafe/slick/slick_2.12/3.3.3/slick_2.12-3.3.3.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/slick/slick_2.12/3.3.3/slick_2.12-3.3.3.pom";
      sha256 = "44886C073276DCAF92C8F54DBF1A37436FFC6308844B8E6A8AF83532334ACD86";
    };
    "nix-public/io/github/java-diff-utils/java-diff-utils-parent/4.15/java-diff-utils-parent-4.15.pom" = {
      url = "https://repo1.maven.org/maven2/io/github/java-diff-utils/java-diff-utils-parent/4.15/java-diff-utils-parent-4.15.pom";
      sha256 = "09E7D44A7CFA19BC6B23CAD14EC0A41F32AE0B597F0E26ACE91916FDC2BB5C82";
    };
    "nix-public/io/github/java-diff-utils/java-diff-utils/4.15/java-diff-utils-4.15-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/io/github/java-diff-utils/java-diff-utils/4.15/java-diff-utils-4.15-javadoc.jar";
      sha256 = "6F9EAE0EA0DB80492232A85571C1FB4BFBFB43C61BF52F37DFA5747F660A8D28";
    };
    "nix-public/io/github/java-diff-utils/java-diff-utils/4.15/java-diff-utils-4.15-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/github/java-diff-utils/java-diff-utils/4.15/java-diff-utils-4.15-sources.jar";
      sha256 = "85E4ED33A7688BE204D36D48A244CF815C05B54C626C6297EC4CF75BE2AF922F";
    };
    "nix-public/io/github/java-diff-utils/java-diff-utils/4.15/java-diff-utils-4.15.jar" = {
      url = "https://repo1.maven.org/maven2/io/github/java-diff-utils/java-diff-utils/4.15/java-diff-utils-4.15.jar";
      sha256 = "964C69E3A23A892DB2778AE6806AA1D42F81230032BD8E4982DC8620582EE6B7";
    };
    "nix-public/io/github/java-diff-utils/java-diff-utils/4.15/java-diff-utils-4.15.pom" = {
      url = "https://repo1.maven.org/maven2/io/github/java-diff-utils/java-diff-utils/4.15/java-diff-utils-4.15.pom";
      sha256 = "1ADF2A60E862B71AA694A3E8E6A888AA353FAFF5059477EBBFDCABCD3A3FF92E";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6-javadoc.jar";
      sha256 = "EBD162363C0A6CA9E52AF51D7377F78F559D3F2663DC896E0DBF3B16A0188972";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6-sources.jar" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6-sources.jar";
      sha256 = "319A840705E1E46ABE579DD3D079B508558791E0236BC78DA01911748E06AF93";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6-tests.jar" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6-tests.jar";
      sha256 = "AE143A7DC135371F446A44775E8D5337D97151D5FEEC8CA8575F3A718DDF35F3";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6.jar" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6.jar";
      sha256 = "97D1ACAAC82409BE42E622D7A54D3AE9D08517E8AEFDEA3D2BA9791150C2F02D";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6.pom" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6.pom";
      sha256 = "1DF7B6F08DFB81A268D6B93B659A6A9E389C5D8C32BDF0754238BA6483A4E982";
    };
    "nix-public/org/jline/jline-parent/3.27.1/jline-parent-3.27.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-parent/3.27.1/jline-parent-3.27.1.pom";
      sha256 = "E964FD076C20CE24DDB48DD737A08D6050347005E3E6EEC82FF5EB043D561581";
    };
    "nix-public/org/jline/jline/3.27.1/jline-3.27.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline/3.27.1/jline-3.27.1-javadoc.jar";
      sha256 = "D91909BDED4E8D1B6E728B7AC1D750900FCB652F3D1FC42FA9B1CC07B1B04387";
    };
    "nix-public/org/jline/jline/3.27.1/jline-3.27.1-jdk8.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline/3.27.1/jline-3.27.1-jdk8.jar";
      sha256 = "9D165AFF3D714A455DE2E711DC90DF09FDB0A0969A1CD4D52AA72A44CB545DB0";
    };
    "nix-public/org/jline/jline/3.27.1/jline-3.27.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline/3.27.1/jline-3.27.1-sources.jar";
      sha256 = "6CA4D8EACB00F9C99A86732F99087CE1F8F2B94294651B042CB6FDCFBF73E136";
    };
    "nix-public/org/jline/jline/3.27.1/jline-3.27.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline/3.27.1/jline-3.27.1.pom";
      sha256 = "3F3559376D8F45DEB1A02C8BE7DBFE73C927374DBCAB0F08E977A1079828AD67";
    };
    "nix-public/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2-javadoc.jar";
      sha256 = "D6FDA7686D9B8C7A4A2FDBB7C8E17036D07A090C2C701D6CB0AB58A1812A4003";
    };
    "nix-public/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2-sources.jar";
      sha256 = "963A6480F46A64013D0F144BA41C6C6E63C4D34B655761717A436492886F3667";
    };
    "nix-public/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.jar";
      sha256 = "CC09AB0B140E0D0496C2165D4B32CE24F4D6446C0A26C5DC77B06BDF99EE8FAE";
    };
    "nix-public/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.pom";
      sha256 = "5B626A99E5734BA8D0C0C8C3FC6258AFA0624F4CE61AE1192247D03C57463DED";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.12/2.0.0/scala-collection-compat_2.12-2.0.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.12/2.0.0/scala-collection-compat_2.12-2.0.0-javadoc.jar";
      sha256 = "C13E605A5EB422C5790AFABB1D8323A5009CD2257C0AC1812862130C769E8625";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.12/2.0.0/scala-collection-compat_2.12-2.0.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.12/2.0.0/scala-collection-compat_2.12-2.0.0-sources.jar";
      sha256 = "6D01063C650604CB336E8BF24B6D0F1FE750031A911DA825E744D934B6475EBA";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.12/2.0.0/scala-collection-compat_2.12-2.0.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.12/2.0.0/scala-collection-compat_2.12-2.0.0.jar";
      sha256 = "434B0783EAF4855AEE27CB47E7372C5DFB39BA0D056485E047745BDB8832DA70";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.12/2.0.0/scala-collection-compat_2.12-2.0.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.12/2.0.0/scala-collection-compat_2.12-2.0.0.pom";
      sha256 = "103A56E746466B773B5B9D89CC593D418139E1635B6FCC81526F69FC8109CBAD";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0-javadoc.jar";
      sha256 = "3C30CA09ED34A472F48BBA732B1360432DB09584B6540DBBB18904C87CECF80F";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0-sources.jar";
      sha256 = "BB93B2FDCD36EBD3E7E6E6DE961CD2A4EAD3815C9565C7BE5CAD860CF3D8C81C";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0.jar";
      sha256 = "4932C56A2D5AAE77AE8D7AC6BED1F21D48268FDBAC8B4E5F3CA5196AD10FD93E";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0.pom";
      sha256 = "45BC645F881F34E6338B478007C6DD93D17389A4F4138616AE7EFA854BAAAA46";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.13/2.1.0/scala-xml_2.13-2.1.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.13/2.1.0/scala-xml_2.13-2.1.0-javadoc.jar";
      sha256 = "F736357F17C38C15AEA86E4228084B91B3D95A7046D663FF8B82E401330CE72F";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.13/2.1.0/scala-xml_2.13-2.1.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.13/2.1.0/scala-xml_2.13-2.1.0-sources.jar";
      sha256 = "B2F5F01C669F29DC03A8127F7A8CA2CDB40DFF3E29BA416E3DE4F6BEF0480ACA";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.13/2.1.0/scala-xml_2.13-2.1.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.13/2.1.0/scala-xml_2.13-2.1.0.jar";
      sha256 = "D122CBF93115EE714570DE6A9C18E53001FEDB474911D4CB5091758EE51F053A";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.13/2.1.0/scala-xml_2.13-2.1.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.13/2.1.0/scala-xml_2.13-2.1.0.pom";
      sha256 = "048282A7E5FD21C79679869E8A64EA704C7C78DD35DD202532CFDAE52CD2D118";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.20/scala-compiler-2.12.20-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.20/scala-compiler-2.12.20-javadoc.jar";
      sha256 = "F90B5673992922C578471AA7A79B27616943C6DD4167D10381D2A6D5373A77B0";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.20/scala-compiler-2.12.20-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.20/scala-compiler-2.12.20-sources.jar";
      sha256 = "07C140C8187A7BCBCFCE7509EB4F1704FCBFA12AD3C7798F8DDCAB9477DC5028";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.20/scala-compiler-2.12.20.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.20/scala-compiler-2.12.20.jar";
      sha256 = "C88676D75C69721B717EA6C441ECE04FFF262ABAB9D210A2936ABC2BE3731FA2";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.20/scala-compiler-2.12.20.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.20/scala-compiler-2.12.20.pom";
      sha256 = "D04B837110423B145973F9A6516AB6AFD9C09C50543B8C7C63AC6C90AD4CCAA3";
    };
    "nix-public/org/scala-lang/scala-compiler/2.13.16/scala-compiler-2.13.16-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.16/scala-compiler-2.13.16-javadoc.jar";
      sha256 = "C0DC7947FD7A3CD62A80322CD627A8D7F0E3F1377956057349B71E9AD9E1FCC5";
    };
    "nix-public/org/scala-lang/scala-compiler/2.13.16/scala-compiler-2.13.16-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.16/scala-compiler-2.13.16-sources.jar";
      sha256 = "E922DC2F97D545FDC083F2FCF2915EB00C7647F3770B95489DE0BC9EF7B54A3E";
    };
    "nix-public/org/scala-lang/scala-compiler/2.13.16/scala-compiler-2.13.16.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.16/scala-compiler-2.13.16.jar";
      sha256 = "F59982714591E321BA9C087AF2C8666E2F5FB92B11A0CEF72C2C5E9B342152D3";
    };
    "nix-public/org/scala-lang/scala-compiler/2.13.16/scala-compiler-2.13.16.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.16/scala-compiler-2.13.16.pom";
      sha256 = "954B555B12C22D4EA59175517FDD9578E06E62EBA8727A2073A6596FA7EB06AB";
    };
    "nix-public/org/scala-lang/scala-library/2.12.20/scala-library-2.12.20-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.20/scala-library-2.12.20-javadoc.jar";
      sha256 = "1A318A6BF41FE3C28BE1C218DEE4371BCABB456AA3433CCC7E26BB3596FE35FD";
    };
    "nix-public/org/scala-lang/scala-library/2.12.20/scala-library-2.12.20-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.20/scala-library-2.12.20-sources.jar";
      sha256 = "C64CC0D241CC7515240D55AAC05213C8C518940A1CCF229C90B8F43BCF3C38EE";
    };
    "nix-public/org/scala-lang/scala-library/2.12.20/scala-library-2.12.20.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.20/scala-library-2.12.20.jar";
      sha256 = "4D8A8F984CCE31A329A24F10B0BF336F042CB62AEB435290A1B20243154CFCCB";
    };
    "nix-public/org/scala-lang/scala-library/2.12.20/scala-library-2.12.20.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.20/scala-library-2.12.20.pom";
      sha256 = "94C315B4C51A4C8D0A33F177E160DDAD63B68595FEB3997FA25791C5A14A03C9";
    };
    "nix-public/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8-javadoc.jar";
      sha256 = "9940E7CF343DFBDDDEB60B538E559496B836430400575405FE46C7176B95C78E";
    };
    "nix-public/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8-sources.jar";
      sha256 = "11482BCB49B2E47BAEE89C3B1AE10C6A40B89E2FBB0DA2A423E062F444E13492";
    };
    "nix-public/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.jar";
      sha256 = "321FB55685635C931EBA4BC0D7668349DA3F2C09AEE2DE93A70566066FF25C28";
    };
    "nix-public/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.pom";
      sha256 = "22E81EE9D5349BA0E897ADB5C7FCEC25656C9E0B7B86C3E93E9A7AF360481C0D";
    };
    "nix-public/org/scala-lang/scala-library/2.13.10/scala-library-2.13.10-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.10/scala-library-2.13.10-javadoc.jar";
      sha256 = "267884FFB2A709374EBD774C5382621202494D090CD4EBCA4D9824A3CCCE80CA";
    };
    "nix-public/org/scala-lang/scala-library/2.13.10/scala-library-2.13.10-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.10/scala-library-2.13.10-sources.jar";
      sha256 = "A991527579C81765CC74ECDBF57FE8FDA9C1FD88FCEEBF19266F030E456EE0F0";
    };
    "nix-public/org/scala-lang/scala-library/2.13.10/scala-library-2.13.10.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.10/scala-library-2.13.10.jar";
      sha256 = "E6CA607C3FCE03E8FA38AF3374CE1F8BB098E316E8BF6F6D27331360FEDDB1C1";
    };
    "nix-public/org/scala-lang/scala-library/2.13.10/scala-library-2.13.10.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.10/scala-library-2.13.10.pom";
      sha256 = "C9686FD8BA7C62F0928F09D0B105AADC82BDAB06241424BA2660E285DC559546";
    };
    "nix-public/org/scala-lang/scala-library/2.13.16/scala-library-2.13.16-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.16/scala-library-2.13.16-javadoc.jar";
      sha256 = "97F4264F4B5B5377D29A79A3B098BEC4DDB0A855BC57B66071F1E99BCFAB25FB";
    };
    "nix-public/org/scala-lang/scala-library/2.13.16/scala-library-2.13.16-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.16/scala-library-2.13.16-sources.jar";
      sha256 = "C02EDC324E7DB59C52115214A6EF36E2D78D0A50DFF635EDA4DCEE5502B1DEA5";
    };
    "nix-public/org/scala-lang/scala-library/2.13.16/scala-library-2.13.16.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.16/scala-library-2.13.16.jar";
      sha256 = "1EBB2B6F9E4EB4022497C19B1E1E825019C08514F962AAAC197145F88ED730F1";
    };
    "nix-public/org/scala-lang/scala-library/2.13.16/scala-library-2.13.16.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.16/scala-library-2.13.16.pom";
      sha256 = "B25B72BA96EB30934868D86D307298D24D3AC154D362E7A4EEB37BA51BA86853";
    };
    "nix-public/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8-javadoc.jar";
      sha256 = "5D6362FFC5A4DC73E4AA839636A226E56EE371C1658480A307C8104CAF3CC9B2";
    };
    "nix-public/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8-sources.jar";
      sha256 = "FCFBDB5FA409A10C0B0AF775382D19CD648663E325A6CD5212F0FED00AF31824";
    };
    "nix-public/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8.jar";
      sha256 = "A0882B82514190C2BAC7D1A459872A75F005FC0F3E88B2BC0390367146E35DB7";
    };
    "nix-public/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8.pom";
      sha256 = "4AE70B3CB0C215D69AEAC28C9212E6811F9EB978956782340608933420880D52";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.20/scala-reflect-2.12.20-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.20/scala-reflect-2.12.20-javadoc.jar";
      sha256 = "8873C5C2B985427F4EA838B52CED831C1BDC819A20863FA5CA2A56580645E108";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.20/scala-reflect-2.12.20-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.20/scala-reflect-2.12.20-sources.jar";
      sha256 = "1ADD39697B43C4E967C79C2DFA5A1ECA493E56DC66FD14D7566F8E2C306C65FA";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.20/scala-reflect-2.12.20.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.20/scala-reflect-2.12.20.jar";
      sha256 = "5F1914CDC7A70580EA6038D929EBB25736ECF2234F677E2D47F8A4B2BC81E1FB";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.20/scala-reflect-2.12.20.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.20/scala-reflect-2.12.20.pom";
      sha256 = "6151C44B5EC49F7E9555450D6ACE47E994129B511119CF364045E18864AF8E96";
    };
    "nix-public/org/scala-lang/scala-reflect/2.13.10/scala-reflect-2.13.10-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.10/scala-reflect-2.13.10-javadoc.jar";
      sha256 = "3CD8B67BEF0D638052B80202D0D49956D8C48D18643AB0B33843993C71E53F04";
    };
    "nix-public/org/scala-lang/scala-reflect/2.13.10/scala-reflect-2.13.10-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.10/scala-reflect-2.13.10-sources.jar";
      sha256 = "CEE62B64B45FF88FD7B3D5B1E459778F3F8010387DC4DEB5FFA44F71C843EA47";
    };
    "nix-public/org/scala-lang/scala-reflect/2.13.10/scala-reflect-2.13.10.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.10/scala-reflect-2.13.10.jar";
      sha256 = "62BD7A7198193C5373A992C122990279E413AF3307162472A5D3CBB8ECADB35E";
    };
    "nix-public/org/scala-lang/scala-reflect/2.13.10/scala-reflect-2.13.10.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.10/scala-reflect-2.13.10.pom";
      sha256 = "79D5C44035AF6622B04E311FF41EACB04D0471B787B0D4C20B239B1D70D5E724";
    };
    "nix-public/org/scala-lang/scala-reflect/2.13.16/scala-reflect-2.13.16-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.16/scala-reflect-2.13.16-javadoc.jar";
      sha256 = "5D019AC9D2B9DC7983979A4EE0CEBB89E2DE83CDC4003BBA848A77B64DCA994F";
    };
    "nix-public/org/scala-lang/scala-reflect/2.13.16/scala-reflect-2.13.16-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.16/scala-reflect-2.13.16-sources.jar";
      sha256 = "11C15FBF9EE203E262049FDD54D8B8472E1601970FBA655678C237629815117E";
    };
    "nix-public/org/scala-lang/scala-reflect/2.13.16/scala-reflect-2.13.16.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.16/scala-reflect-2.13.16.jar";
      sha256 = "FB49CCD9CAC7464486AB993CDA20A3C1569D8EF26F052E897577AD2A4970FB1D";
    };
    "nix-public/org/scala-lang/scala-reflect/2.13.16/scala-reflect-2.13.16.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.16/scala-reflect-2.13.16.pom";
      sha256 = "66B1833F1EE675AB2AE5F6D55B38DDAD472246CDC092132B8C52D0CF94A31B60";
    };
    "nix-public/org/scala-lang/scala2-sbt-bridge/2.13.16/scala2-sbt-bridge-2.13.16-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala2-sbt-bridge/2.13.16/scala2-sbt-bridge-2.13.16-javadoc.jar";
      sha256 = "D3A13C69FAEF6477BEE7D5D2BB673E7EA7263BA2A1231F9DF417D747C9D4693A";
    };
    "nix-public/org/scala-lang/scala2-sbt-bridge/2.13.16/scala2-sbt-bridge-2.13.16-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala2-sbt-bridge/2.13.16/scala2-sbt-bridge-2.13.16-sources.jar";
      sha256 = "958DC58B891F3EE1C6D8AB22452438A1141CEB16C58386A397FFE4E7DA78AD45";
    };
    "nix-public/org/scala-lang/scala2-sbt-bridge/2.13.16/scala2-sbt-bridge-2.13.16.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala2-sbt-bridge/2.13.16/scala2-sbt-bridge-2.13.16.jar";
      sha256 = "776EF74D8BC1222F4B6E7B5DC5DD1F0ABFC97AB853CB4932292DEE0B32111906";
    };
    "nix-public/org/scala-lang/scala2-sbt-bridge/2.13.16/scala2-sbt-bridge-2.13.16.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala2-sbt-bridge/2.13.16/scala2-sbt-bridge-2.13.16.pom";
      sha256 = "1E514DDBA6DA57565A96CA770678F2831F649AD94D499D185C2D2C638A68E2A2";
    };
    "nix-public/org/scala-sbt/compiler-bridge_2.12/1.10.7/compiler-bridge_2.12-1.10.7-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.12/1.10.7/compiler-bridge_2.12-1.10.7-javadoc.jar";
      sha256 = "2CE7BE22BDFBB946FAFC81F90D2756EDF74448E626FA916E70D6340E6C4974F9";
    };
    "nix-public/org/scala-sbt/compiler-bridge_2.12/1.10.7/compiler-bridge_2.12-1.10.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.12/1.10.7/compiler-bridge_2.12-1.10.7-sources.jar";
      sha256 = "DEBC50F2D3CE476F4FEFC6598D93714973D8194C444CB563E0CDE1ACC92A630E";
    };
    "nix-public/org/scala-sbt/compiler-bridge_2.12/1.10.7/compiler-bridge_2.12-1.10.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.12/1.10.7/compiler-bridge_2.12-1.10.7.jar";
      sha256 = "F7500D7550D1A4BA1ECB4C8D2BF0ECE8F8734D5286249205915A1A942DD3C647";
    };
    "nix-public/org/scala-sbt/compiler-bridge_2.12/1.10.7/compiler-bridge_2.12-1.10.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.12/1.10.7/compiler-bridge_2.12-1.10.7.pom";
      sha256 = "C84FF12716BE701BFEDC69E613F5EF961896E9FD6A50B9E8A702A9E69EC13607";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.10.7/compiler-interface-1.10.7-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.10.7/compiler-interface-1.10.7-javadoc.jar";
      sha256 = "700E5F058F53AD7CB36D4D473F430C6823B81984B21ABEE469A9EAC06F847846";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.10.7/compiler-interface-1.10.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.10.7/compiler-interface-1.10.7-sources.jar";
      sha256 = "6BF753FBA3AFAD192B1837858A2E68D5969976375C27B8E2969CDEA952EFB47F";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.10.7/compiler-interface-1.10.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.10.7/compiler-interface-1.10.7.jar";
      sha256 = "2BACC5761E03920A228E5C9D20B33D9C51D43AAF2F52E8F839ECE630966EB880";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.10.7/compiler-interface-1.10.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.10.7/compiler-interface-1.10.7.pom";
      sha256 = "3B7B0DA8BF5820AA50F4448E19021DE1183164F74A180BD0B68E7D92F3004E31";
    };
    "nix-public/org/scala-sbt/util-interface/1.10.7/util-interface-1.10.7-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.10.7/util-interface-1.10.7-javadoc.jar";
      sha256 = "374E3161D49CA3570F4B454F3229BD8A074E558C90644407E068343C766D5B45";
    };
    "nix-public/org/scala-sbt/util-interface/1.10.7/util-interface-1.10.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.10.7/util-interface-1.10.7-sources.jar";
      sha256 = "6AC907710F3BB66A94E2A5D5703AEF5D16DDC1BBAF35185E9F6ACA1354956B12";
    };
    "nix-public/org/scala-sbt/util-interface/1.10.7/util-interface-1.10.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.10.7/util-interface-1.10.7.jar";
      sha256 = "1D6B91EFA42B70FC064CAED6D62962374E13B27737F885A87C84C667B30BE625";
    };
    "nix-public/org/scala-sbt/util-interface/1.10.7/util-interface-1.10.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.10.7/util-interface-1.10.7.pom";
      sha256 = "D49470C815E070E44F9501116C83F35B179413F5AAFE95E29AC293C67CC16297";
    };
    "nix-public/org/scalactic/scalactic_2.13/3.2.15/scalactic_2.13-3.2.15-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalactic/scalactic_2.13/3.2.15/scalactic_2.13-3.2.15-javadoc.jar";
      sha256 = "D2D1E155A9569B959BD4403045C314A09CEDF5D18464BE2EFC126CC2FE0FE346";
    };
    "nix-public/org/scalactic/scalactic_2.13/3.2.15/scalactic_2.13-3.2.15-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalactic/scalactic_2.13/3.2.15/scalactic_2.13-3.2.15-sources.jar";
      sha256 = "ABA36241CA9FBE9DC37DA4FF5A78A481E31087F31DE41F46D8039E956F912061";
    };
    "nix-public/org/scalactic/scalactic_2.13/3.2.15/scalactic_2.13-3.2.15.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalactic/scalactic_2.13/3.2.15/scalactic_2.13-3.2.15.jar";
      sha256 = "958AE2A1955ABF898A13A6A1CE125CFFF6CCF44BEDE1E1C61E431E1D8805E7E1";
    };
    "nix-public/org/scalactic/scalactic_2.13/3.2.15/scalactic_2.13-3.2.15.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalactic/scalactic_2.13/3.2.15/scalactic_2.13-3.2.15.pom";
      sha256 = "297ACFFC976FA9BB85354EFCB028E49E60DBFEEF5A417B7F91CC01187DB5E1E6";
    };
    "nix-public/org/scalatest/scalatest-compatible/3.2.15/scalatest-compatible-3.2.15-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-compatible/3.2.15/scalatest-compatible-3.2.15-javadoc.jar";
      sha256 = "D7DFC5EB83ABD086DDACC07AF260AD26659A58DF720E74975AA1E47436D414D6";
    };
    "nix-public/org/scalatest/scalatest-compatible/3.2.15/scalatest-compatible-3.2.15-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-compatible/3.2.15/scalatest-compatible-3.2.15-sources.jar";
      sha256 = "585FD3CFC7E943B1738EBC51773391781D74D2B05C829C55964A88CE4AC12294";
    };
    "nix-public/org/scalatest/scalatest-compatible/3.2.15/scalatest-compatible-3.2.15.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-compatible/3.2.15/scalatest-compatible-3.2.15.jar";
      sha256 = "B48A2931333D9522F72F8F74DBF632587103B19620FB1CFEA59E9E1147CFFC78";
    };
    "nix-public/org/scalatest/scalatest-compatible/3.2.15/scalatest-compatible-3.2.15.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-compatible/3.2.15/scalatest-compatible-3.2.15.pom";
      sha256 = "7B19D93715B05FD1D8E046F0FC478BAFCA18FC0BA1259BA8CCFABCD822A40E05";
    };
    "nix-public/org/scalatest/scalatest-core_2.13/3.2.15/scalatest-core_2.13-3.2.15-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-core_2.13/3.2.15/scalatest-core_2.13-3.2.15-javadoc.jar";
      sha256 = "9FF1F35B286F81329886199BE461BFC9BCE90554BBC89D5A67D30624A0421497";
    };
    "nix-public/org/scalatest/scalatest-core_2.13/3.2.15/scalatest-core_2.13-3.2.15-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-core_2.13/3.2.15/scalatest-core_2.13-3.2.15-sources.jar";
      sha256 = "2D44580D74C91D88EFC07850D65E7D15F487D9D6D0D38B1AF2475AFA8D823D2E";
    };
    "nix-public/org/scalatest/scalatest-core_2.13/3.2.15/scalatest-core_2.13-3.2.15.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-core_2.13/3.2.15/scalatest-core_2.13-3.2.15.jar";
      sha256 = "BA788A3CF15BF30D312B028F2D9DF673D448F2DD36B46736D71BD9715481DAF9";
    };
    "nix-public/org/scalatest/scalatest-core_2.13/3.2.15/scalatest-core_2.13-3.2.15.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-core_2.13/3.2.15/scalatest-core_2.13-3.2.15.pom";
      sha256 = "0042EE99521705C65FAE2A95096B4E587462B54F78C2A11327421C0118B78A3E";
    };
    "nix-public/org/scalatest/scalatest-diagrams_2.13/3.2.15/scalatest-diagrams_2.13-3.2.15-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-diagrams_2.13/3.2.15/scalatest-diagrams_2.13-3.2.15-javadoc.jar";
      sha256 = "7AB1D44FC00E72682604D70728CD173828DB6ADC3391A4311540031D8C9441DF";
    };
    "nix-public/org/scalatest/scalatest-diagrams_2.13/3.2.15/scalatest-diagrams_2.13-3.2.15-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-diagrams_2.13/3.2.15/scalatest-diagrams_2.13-3.2.15-sources.jar";
      sha256 = "4E1F01A3CAFA032F979B257AB93875707EBC97D0BAB21F5774389FA113ED638F";
    };
    "nix-public/org/scalatest/scalatest-diagrams_2.13/3.2.15/scalatest-diagrams_2.13-3.2.15.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-diagrams_2.13/3.2.15/scalatest-diagrams_2.13-3.2.15.jar";
      sha256 = "3AC2AD0C2C5039B7084172C489E00DE484DB742C40A9FF5539E2C641A347488D";
    };
    "nix-public/org/scalatest/scalatest-diagrams_2.13/3.2.15/scalatest-diagrams_2.13-3.2.15.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-diagrams_2.13/3.2.15/scalatest-diagrams_2.13-3.2.15.pom";
      sha256 = "654CDC99929540E00A0F3CCC323F84A95235AB60BD296BC6C480EB1B4EEAE4CF";
    };
    "nix-public/org/scalatest/scalatest-featurespec_2.13/3.2.15/scalatest-featurespec_2.13-3.2.15-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-featurespec_2.13/3.2.15/scalatest-featurespec_2.13-3.2.15-javadoc.jar";
      sha256 = "AD12CF31B0DD0AD72BDE72D68A6A3798712412E6D3006DE47876B549DEF19F04";
    };
    "nix-public/org/scalatest/scalatest-featurespec_2.13/3.2.15/scalatest-featurespec_2.13-3.2.15-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-featurespec_2.13/3.2.15/scalatest-featurespec_2.13-3.2.15-sources.jar";
      sha256 = "24A4365654C3762BB542EF24E4988E8F77612F617A013EC2D2852B5D9B925372";
    };
    "nix-public/org/scalatest/scalatest-featurespec_2.13/3.2.15/scalatest-featurespec_2.13-3.2.15.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-featurespec_2.13/3.2.15/scalatest-featurespec_2.13-3.2.15.jar";
      sha256 = "A6FDA4CB0457B76F16F5150B321E8BA01494D51EA5A7A4BAE346002A87E6D9E0";
    };
    "nix-public/org/scalatest/scalatest-featurespec_2.13/3.2.15/scalatest-featurespec_2.13-3.2.15.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-featurespec_2.13/3.2.15/scalatest-featurespec_2.13-3.2.15.pom";
      sha256 = "19F586AA96F0D9183B703DC179E6D361C42D7971A6B0CF7D6CCB9151AED5E04E";
    };
    "nix-public/org/scalatest/scalatest-flatspec_2.13/3.2.15/scalatest-flatspec_2.13-3.2.15-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-flatspec_2.13/3.2.15/scalatest-flatspec_2.13-3.2.15-javadoc.jar";
      sha256 = "322ACE7D673E08915CE4E8B1EC7E4C54F1A2C5C1D5339BBDCD2345589941E638";
    };
    "nix-public/org/scalatest/scalatest-flatspec_2.13/3.2.15/scalatest-flatspec_2.13-3.2.15-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-flatspec_2.13/3.2.15/scalatest-flatspec_2.13-3.2.15-sources.jar";
      sha256 = "E6329C4D586498149C75B9ADF7A1C95852EB0B831BF0045D4D737D02ED49B412";
    };
    "nix-public/org/scalatest/scalatest-flatspec_2.13/3.2.15/scalatest-flatspec_2.13-3.2.15.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-flatspec_2.13/3.2.15/scalatest-flatspec_2.13-3.2.15.jar";
      sha256 = "69DEB630A68FB00CE29F0ADDF7EC4775A2D0E01C7D7C26C6F8B7C0416D4467C8";
    };
    "nix-public/org/scalatest/scalatest-flatspec_2.13/3.2.15/scalatest-flatspec_2.13-3.2.15.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-flatspec_2.13/3.2.15/scalatest-flatspec_2.13-3.2.15.pom";
      sha256 = "F6D8AB2C97C24C70232D3BF4B1F4BD0E5DE3EC305365B5BC364A77DAD46D5B09";
    };
    "nix-public/org/scalatest/scalatest-freespec_2.13/3.2.15/scalatest-freespec_2.13-3.2.15-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-freespec_2.13/3.2.15/scalatest-freespec_2.13-3.2.15-javadoc.jar";
      sha256 = "2C52D730C5A63F32C3D122AEB7850F085CCA3D359F0E4DB941C71715631969B1";
    };
    "nix-public/org/scalatest/scalatest-freespec_2.13/3.2.15/scalatest-freespec_2.13-3.2.15-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-freespec_2.13/3.2.15/scalatest-freespec_2.13-3.2.15-sources.jar";
      sha256 = "C802CBFFD68C2C92F762A47452371D75AFE64D728874DE222F8F230E1B86D0EA";
    };
    "nix-public/org/scalatest/scalatest-freespec_2.13/3.2.15/scalatest-freespec_2.13-3.2.15.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-freespec_2.13/3.2.15/scalatest-freespec_2.13-3.2.15.jar";
      sha256 = "5245B1D8643F3068153477DB9956D9B2E23DB62E2983F70635298E4B41A79E6F";
    };
    "nix-public/org/scalatest/scalatest-freespec_2.13/3.2.15/scalatest-freespec_2.13-3.2.15.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-freespec_2.13/3.2.15/scalatest-freespec_2.13-3.2.15.pom";
      sha256 = "C1281A4B3DB8E6C523BCFE23E10FCCF57939B55B569223E0D1FF3AB96AC22ABC";
    };
    "nix-public/org/scalatest/scalatest-funspec_2.13/3.2.15/scalatest-funspec_2.13-3.2.15-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-funspec_2.13/3.2.15/scalatest-funspec_2.13-3.2.15-javadoc.jar";
      sha256 = "AB71F3647AEA8141E536407EE7C237B48F0A4DC7F50EB2F169E96123330966C7";
    };
    "nix-public/org/scalatest/scalatest-funspec_2.13/3.2.15/scalatest-funspec_2.13-3.2.15-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-funspec_2.13/3.2.15/scalatest-funspec_2.13-3.2.15-sources.jar";
      sha256 = "BADCD6BC3472045279918B1567973FE8819BD5723430E11F1E0B111F27856390";
    };
    "nix-public/org/scalatest/scalatest-funspec_2.13/3.2.15/scalatest-funspec_2.13-3.2.15.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-funspec_2.13/3.2.15/scalatest-funspec_2.13-3.2.15.jar";
      sha256 = "0309E4D44D290EF143E9204772CAB672A021556B84A1FFAE87A6DD6ABA00741D";
    };
    "nix-public/org/scalatest/scalatest-funspec_2.13/3.2.15/scalatest-funspec_2.13-3.2.15.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-funspec_2.13/3.2.15/scalatest-funspec_2.13-3.2.15.pom";
      sha256 = "32941651C32E43810B9D4F89B300261AA3A473000478D9BFF3D0FD89CFEE4B28";
    };
    "nix-public/org/scalatest/scalatest-funsuite_2.13/3.2.15/scalatest-funsuite_2.13-3.2.15-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-funsuite_2.13/3.2.15/scalatest-funsuite_2.13-3.2.15-javadoc.jar";
      sha256 = "E3197189FE92844761C315C6F65B39D9DE3FE619E636F89F6ED9D66214AA3F8A";
    };
    "nix-public/org/scalatest/scalatest-funsuite_2.13/3.2.15/scalatest-funsuite_2.13-3.2.15-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-funsuite_2.13/3.2.15/scalatest-funsuite_2.13-3.2.15-sources.jar";
      sha256 = "2F0964744A9123D7E24B7AF7EDDA4F3831629291A3267D7728EBF39284E3DCAF";
    };
    "nix-public/org/scalatest/scalatest-funsuite_2.13/3.2.15/scalatest-funsuite_2.13-3.2.15.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-funsuite_2.13/3.2.15/scalatest-funsuite_2.13-3.2.15.jar";
      sha256 = "78977911ABFAD02181979A743DBB0D05FEE1CE4F13B911A579129DD11533ABFA";
    };
    "nix-public/org/scalatest/scalatest-funsuite_2.13/3.2.15/scalatest-funsuite_2.13-3.2.15.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-funsuite_2.13/3.2.15/scalatest-funsuite_2.13-3.2.15.pom";
      sha256 = "D3520424055FCD57622D9973F33276B09FBE769F0CA5371FE236C52F80D8FE51";
    };
    "nix-public/org/scalatest/scalatest-matchers-core_2.13/3.2.15/scalatest-matchers-core_2.13-3.2.15-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-matchers-core_2.13/3.2.15/scalatest-matchers-core_2.13-3.2.15-javadoc.jar";
      sha256 = "8744DB32605EF3C87558005A5770EF66ECA63D8F3477D224D6953FDB0B5FF599";
    };
    "nix-public/org/scalatest/scalatest-matchers-core_2.13/3.2.15/scalatest-matchers-core_2.13-3.2.15-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-matchers-core_2.13/3.2.15/scalatest-matchers-core_2.13-3.2.15-sources.jar";
      sha256 = "8C47A3C73638F32713CAFF5C7C5B8660571D44DED947EC08E12407A3A47D21EC";
    };
    "nix-public/org/scalatest/scalatest-matchers-core_2.13/3.2.15/scalatest-matchers-core_2.13-3.2.15.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-matchers-core_2.13/3.2.15/scalatest-matchers-core_2.13-3.2.15.jar";
      sha256 = "788F3191C89F2F0C2E50A1A67A87EBAE899C855D906A5D08B549CC148CA43258";
    };
    "nix-public/org/scalatest/scalatest-matchers-core_2.13/3.2.15/scalatest-matchers-core_2.13-3.2.15.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-matchers-core_2.13/3.2.15/scalatest-matchers-core_2.13-3.2.15.pom";
      sha256 = "4A1C1DA352A674FD28360A478BED2BB8BA49030EDA061DEF3E7DD77AAC5679D9";
    };
    "nix-public/org/scalatest/scalatest-mustmatchers_2.13/3.2.15/scalatest-mustmatchers_2.13-3.2.15-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-mustmatchers_2.13/3.2.15/scalatest-mustmatchers_2.13-3.2.15-javadoc.jar";
      sha256 = "C99B17B3BC6C4818DE1601696164B6A66D0E827A44C8F7F1CC00E4520D1FECF9";
    };
    "nix-public/org/scalatest/scalatest-mustmatchers_2.13/3.2.15/scalatest-mustmatchers_2.13-3.2.15-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-mustmatchers_2.13/3.2.15/scalatest-mustmatchers_2.13-3.2.15-sources.jar";
      sha256 = "C2518D473EC0C9F2912585D0F39DB524DB99EA27B13202F3907BB100490FD81C";
    };
    "nix-public/org/scalatest/scalatest-mustmatchers_2.13/3.2.15/scalatest-mustmatchers_2.13-3.2.15.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-mustmatchers_2.13/3.2.15/scalatest-mustmatchers_2.13-3.2.15.jar";
      sha256 = "3DB8724A43FDB1E6F13076EB0A7F571CD3E2F6B97249FE7723DB2031A8B5E18F";
    };
    "nix-public/org/scalatest/scalatest-mustmatchers_2.13/3.2.15/scalatest-mustmatchers_2.13-3.2.15.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-mustmatchers_2.13/3.2.15/scalatest-mustmatchers_2.13-3.2.15.pom";
      sha256 = "533650623E6ED7B151F2DD3467C05621C3901279C7CAF6F12B81EC52D8820F98";
    };
    "nix-public/org/scalatest/scalatest-propspec_2.13/3.2.15/scalatest-propspec_2.13-3.2.15-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-propspec_2.13/3.2.15/scalatest-propspec_2.13-3.2.15-javadoc.jar";
      sha256 = "EEB5B32B953AAC70A4458DC4B9A1A66172C6A01D564D70F301AD130F1AF62DAF";
    };
    "nix-public/org/scalatest/scalatest-propspec_2.13/3.2.15/scalatest-propspec_2.13-3.2.15-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-propspec_2.13/3.2.15/scalatest-propspec_2.13-3.2.15-sources.jar";
      sha256 = "984F17D56BA1E7918C6DF18F17DA93569651972DA348E8E6F8DB3C8C99A5548D";
    };
    "nix-public/org/scalatest/scalatest-propspec_2.13/3.2.15/scalatest-propspec_2.13-3.2.15.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-propspec_2.13/3.2.15/scalatest-propspec_2.13-3.2.15.jar";
      sha256 = "BA3550D29E1D2F67A045C9F5C6AFB141A4604F1A840C6C1F762CCADD916AA801";
    };
    "nix-public/org/scalatest/scalatest-propspec_2.13/3.2.15/scalatest-propspec_2.13-3.2.15.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-propspec_2.13/3.2.15/scalatest-propspec_2.13-3.2.15.pom";
      sha256 = "F6813205409163C4A00E1A111F6474797F4A253840201BF75E161F842547D4D9";
    };
    "nix-public/org/scalatest/scalatest-refspec_2.13/3.2.15/scalatest-refspec_2.13-3.2.15-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-refspec_2.13/3.2.15/scalatest-refspec_2.13-3.2.15-javadoc.jar";
      sha256 = "1384BD7A4F09CB34244415A24B0290A02E4280DF46C362DAC1D0DB4D01548161";
    };
    "nix-public/org/scalatest/scalatest-refspec_2.13/3.2.15/scalatest-refspec_2.13-3.2.15-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-refspec_2.13/3.2.15/scalatest-refspec_2.13-3.2.15-sources.jar";
      sha256 = "1BCBCB39701D0A5B0C47D21B49966BF7709B2DEE63F23715C27D779BEEB60891";
    };
    "nix-public/org/scalatest/scalatest-refspec_2.13/3.2.15/scalatest-refspec_2.13-3.2.15.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-refspec_2.13/3.2.15/scalatest-refspec_2.13-3.2.15.jar";
      sha256 = "958196F6029E382F027EFE790CEE7449167AC259D89DBF9B14BEBBC8564AD34B";
    };
    "nix-public/org/scalatest/scalatest-refspec_2.13/3.2.15/scalatest-refspec_2.13-3.2.15.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-refspec_2.13/3.2.15/scalatest-refspec_2.13-3.2.15.pom";
      sha256 = "CA8456355AB608426A9C1A794D20D4810AB7845F214F73721DA566B9150477C1";
    };
    "nix-public/org/scalatest/scalatest-shouldmatchers_2.13/3.2.15/scalatest-shouldmatchers_2.13-3.2.15-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-shouldmatchers_2.13/3.2.15/scalatest-shouldmatchers_2.13-3.2.15-javadoc.jar";
      sha256 = "0DA3F73593957074CD0A2AC66A4B9C068105D90BACDE536EBF5F716C31D5762B";
    };
    "nix-public/org/scalatest/scalatest-shouldmatchers_2.13/3.2.15/scalatest-shouldmatchers_2.13-3.2.15-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-shouldmatchers_2.13/3.2.15/scalatest-shouldmatchers_2.13-3.2.15-sources.jar";
      sha256 = "FCD02B7C18CFE03DB42A95F535D696798EBD423DD35F7219AEF48E2F67C3302D";
    };
    "nix-public/org/scalatest/scalatest-shouldmatchers_2.13/3.2.15/scalatest-shouldmatchers_2.13-3.2.15.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-shouldmatchers_2.13/3.2.15/scalatest-shouldmatchers_2.13-3.2.15.jar";
      sha256 = "2BD0E38D338BDF051844C8B19CAA769117A6AA3A3116244A11EE6CF00EEE6355";
    };
    "nix-public/org/scalatest/scalatest-shouldmatchers_2.13/3.2.15/scalatest-shouldmatchers_2.13-3.2.15.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-shouldmatchers_2.13/3.2.15/scalatest-shouldmatchers_2.13-3.2.15.pom";
      sha256 = "A62161354611D70BB0F34B1E412B756431134E2C25ACF551F12EB7B4DB1E6FAF";
    };
    "nix-public/org/scalatest/scalatest-wordspec_2.13/3.2.15/scalatest-wordspec_2.13-3.2.15-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-wordspec_2.13/3.2.15/scalatest-wordspec_2.13-3.2.15-javadoc.jar";
      sha256 = "3B6BA64047D690311457DCA6CAEB1995B77E4D137999C7635194828E5C1306AB";
    };
    "nix-public/org/scalatest/scalatest-wordspec_2.13/3.2.15/scalatest-wordspec_2.13-3.2.15-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-wordspec_2.13/3.2.15/scalatest-wordspec_2.13-3.2.15-sources.jar";
      sha256 = "CA8A1899A3B16C89293F20D5EA8C432485CF55B3683803E9BAC7759E7EF92AEE";
    };
    "nix-public/org/scalatest/scalatest-wordspec_2.13/3.2.15/scalatest-wordspec_2.13-3.2.15.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-wordspec_2.13/3.2.15/scalatest-wordspec_2.13-3.2.15.jar";
      sha256 = "E49F03624A014C37E06719394CC62A882DB34A9817D8498FD60253D0B3288294";
    };
    "nix-public/org/scalatest/scalatest-wordspec_2.13/3.2.15/scalatest-wordspec_2.13-3.2.15.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-wordspec_2.13/3.2.15/scalatest-wordspec_2.13-3.2.15.pom";
      sha256 = "B33B426B23A6F0D8CC80462E93F1F628DB4820C7F45660FE2408C93F810B4230";
    };
    "nix-public/org/scalatest/scalatest_2.13/3.2.15/scalatest_2.13-3.2.15-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest_2.13/3.2.15/scalatest_2.13-3.2.15-javadoc.jar";
      sha256 = "D653AADE571393B17CF4BF5157A64EBBA0F2D6F2909254CD0E120159E52AECC6";
    };
    "nix-public/org/scalatest/scalatest_2.13/3.2.15/scalatest_2.13-3.2.15-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest_2.13/3.2.15/scalatest_2.13-3.2.15-sources.jar";
      sha256 = "3C185D0B7FC5CE5A8B7F2403603420004E283BBE4DA43055C041BDFBEEE4407A";
    };
    "nix-public/org/scalatest/scalatest_2.13/3.2.15/scalatest_2.13-3.2.15.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest_2.13/3.2.15/scalatest_2.13-3.2.15.jar";
      sha256 = "36128473591AE15BB9B0403BE77A6F226F922AA81BBC6AD3C9620B5DE827ADB8";
    };
    "nix-public/org/scalatest/scalatest_2.13/3.2.15/scalatest_2.13-3.2.15.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest_2.13/3.2.15/scalatest_2.13-3.2.15.pom";
      sha256 = "DBA242919F71075B153F9932A8D3F38567662642E20D768631C9CE40CD564B92";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-javadoc.jar";
      sha256 = "8DC4B97B764D6C5B732479936C6CA28DFE9480C8A9B67E4B26CF95C8C64D77BD";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-sources.jar";
      sha256 = "C4BC93180A4F0ACEEC3B057A2514ABE04A79F06C174BBED910A2AFB227B79366";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-tests.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-tests.jar";
      sha256 = "FB82F52621D9DDAFB135DFF968A75B5BC08C40BA4BE77B5AB8DEA8711A032D72";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar";
      sha256 = "18C4A0095D5C1DA6B817592E767BB23D29DD2F560AD74DF75FF3961DBDE25B79";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.pom";
      sha256 = "7CD9D7A0B5D93DFD461A148891B43509CF403A9C7F9FB49060D3554DF1C81E1E";
    };
    "nix-public/org/slf4j/slf4j-parent/1.7.25/slf4j-parent-1.7.25.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.7.25/slf4j-parent-1.7.25.pom";
      sha256 = "18F5C52120DB036E88D6136F8839C832D074BDDA95C756C6F429249D2DB54AC6";
    };
    "nix-public/org/sonatype/oss/oss-parent/9/oss-parent-9.pom" = {
      url = "https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom";
      sha256 = "FB40265F982548212FF82E362E59732B2187EC6F0D80182885C14EF1F982827A";
    };
  };
}
