# This file was automatically generated by Sbtix. Do not edit manually.
{
  "versioning" = [{
      "scalaVersion" = "2.12.20";
      "sbtVersion" = "1.10.7";
    }];
  "repos" = {
    "nix-public" = "";
  };

  "artifacts" = {
  };
}