# This file was automatically generated by Sbtix. Do not edit manually.
{
  "versioning" = [{
      "scalaVersion" = "2.12.21";
      "sbtVersion" = "1.12.11";
    }];
  "repos" = {
    "nix-public" = "";
    "nix-sbt-plugin-releases" = "[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]";
  };

  "artifacts" = {
    "nix-public/ch/qos/logback/logback-classic/1.3.15/logback-classic-1.3.15.pom" = {
      url = "https://repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.3.15/logback-classic-1.3.15.pom";
      sha256 = "A9AE17F9E7545006B4FA85CAE8988435E5D4B2A5D1FFB99BC09FA15B8A9D8A85";
    };
    "nix-public/ch/qos/logback/logback-core/1.3.15/logback-core-1.3.15.pom" = {
      url = "https://repo1.maven.org/maven2/ch/qos/logback/logback-core/1.3.15/logback-core-1.3.15.pom";
      sha256 = "642BE9C29CCF62F2FB8A73A9C91CD19420E68FFF7F158E8F297E5127B11C1A46";
    };
    "nix-public/ch/qos/logback/logback-parent/1.3.15/logback-parent-1.3.15.pom" = {
      url = "https://repo1.maven.org/maven2/ch/qos/logback/logback-parent/1.3.15/logback-parent-1.3.15.pom";
      sha256 = "3379649C6EE225336FDE3704B4A8B7D596DAF741F155B5FC5DBFC73D872CD612";
    };
    "nix-public/com/eed3si9n/gigahorse-apache-http_2.12/0.9.4/gigahorse-apache-http-0.9.4.pom" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/gigahorse-apache-http_2.12/0.9.4/gigahorse-apache-http_2.12-0.9.4.pom";
      sha256 = "497107A3704ED6BA38877D09C8125EF8FA928F101EAFBA440B2BF81A0818CD64";
    };
    "nix-public/com/eed3si9n/gigahorse-apache-http_2.12/0.9.4/gigahorse-apache-http_2.12-0.9.4.pom" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/gigahorse-apache-http_2.12/0.9.4/gigahorse-apache-http_2.12-0.9.4.pom";
      sha256 = "497107A3704ED6BA38877D09C8125EF8FA928F101EAFBA440B2BF81A0818CD64";
    };
    "nix-public/com/eed3si9n/gigahorse-core_2.12/0.4.0/gigahorse-core-0.4.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/gigahorse-core_2.12/0.4.0/gigahorse-core_2.12-0.4.0-sources.jar";
      sha256 = "75D6B41DDCE9A6001A83D6EC794D2CA304BF636FF65121DDA6209C547DFD9870";
    };
    "nix-public/com/eed3si9n/gigahorse-core_2.12/0.4.0/gigahorse-core-0.4.0.jar" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/gigahorse-core_2.12/0.4.0/gigahorse-core_2.12-0.4.0.jar";
      sha256 = "10AAF3BF7843359CE0587CBBB4A796BAE3A193DF25EAECAACFB34801BD8B3D3D";
    };
    "nix-public/com/eed3si9n/gigahorse-core_2.12/0.4.0/gigahorse-core-0.4.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/gigahorse-core_2.12/0.4.0/gigahorse-core_2.12-0.4.0.pom";
      sha256 = "AACBFCA46C8EEE24896A6A59E174F96EA0B8B24383DCC6852A3602312FDDD804";
    };
    "nix-public/com/eed3si9n/gigahorse-core_2.12/0.4.0/gigahorse-core_2.12-0.4.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/gigahorse-core_2.12/0.4.0/gigahorse-core_2.12-0.4.0-sources.jar";
      sha256 = "75D6B41DDCE9A6001A83D6EC794D2CA304BF636FF65121DDA6209C547DFD9870";
    };
    "nix-public/com/eed3si9n/gigahorse-core_2.12/0.4.0/gigahorse-core_2.12-0.4.0.jar" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/gigahorse-core_2.12/0.4.0/gigahorse-core_2.12-0.4.0.jar";
      sha256 = "10AAF3BF7843359CE0587CBBB4A796BAE3A193DF25EAECAACFB34801BD8B3D3D";
    };
    "nix-public/com/eed3si9n/gigahorse-core_2.12/0.4.0/gigahorse-core_2.12-0.4.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/gigahorse-core_2.12/0.4.0/gigahorse-core_2.12-0.4.0.pom";
      sha256 = "AACBFCA46C8EEE24896A6A59E174F96EA0B8B24383DCC6852A3602312FDDD804";
    };
    "nix-public/com/eed3si9n/gigahorse-core_2.12/0.9.4/gigahorse-core-0.9.4.pom" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/gigahorse-core_2.12/0.9.4/gigahorse-core_2.12-0.9.4.pom";
      sha256 = "2C176F4680893DAEAAFE32B2F89D88643A6A057582107FC0A79229661C8B2CB4";
    };
    "nix-public/com/eed3si9n/gigahorse-core_2.12/0.9.4/gigahorse-core_2.12-0.9.4.pom" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/gigahorse-core_2.12/0.9.4/gigahorse-core_2.12-0.9.4.pom";
      sha256 = "2C176F4680893DAEAAFE32B2F89D88643A6A057582107FC0A79229661C8B2CB4";
    };
    "nix-public/com/eed3si9n/gigahorse-okhttp_2.12/0.4.0/gigahorse-okhttp-0.4.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/gigahorse-okhttp_2.12/0.4.0/gigahorse-okhttp_2.12-0.4.0-sources.jar";
      sha256 = "A2C12B9A8F0EDEF9998717B8D23B77C5F7DC1548ACAD38143E2653F29CEFF480";
    };
    "nix-public/com/eed3si9n/gigahorse-okhttp_2.12/0.4.0/gigahorse-okhttp-0.4.0.jar" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/gigahorse-okhttp_2.12/0.4.0/gigahorse-okhttp_2.12-0.4.0.jar";
      sha256 = "F70834AABEC2D304143C1FF5B146BAF020EE365D35A1804BE029B0FD1B86620E";
    };
    "nix-public/com/eed3si9n/gigahorse-okhttp_2.12/0.4.0/gigahorse-okhttp-0.4.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/gigahorse-okhttp_2.12/0.4.0/gigahorse-okhttp_2.12-0.4.0.pom";
      sha256 = "7BF2ADD227EBD3D67F26690779815B25B85D5E0F41D825B411A62595CE28F232";
    };
    "nix-public/com/eed3si9n/gigahorse-okhttp_2.12/0.4.0/gigahorse-okhttp_2.12-0.4.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/gigahorse-okhttp_2.12/0.4.0/gigahorse-okhttp_2.12-0.4.0-sources.jar";
      sha256 = "A2C12B9A8F0EDEF9998717B8D23B77C5F7DC1548ACAD38143E2653F29CEFF480";
    };
    "nix-public/com/eed3si9n/gigahorse-okhttp_2.12/0.4.0/gigahorse-okhttp_2.12-0.4.0.jar" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/gigahorse-okhttp_2.12/0.4.0/gigahorse-okhttp_2.12-0.4.0.jar";
      sha256 = "F70834AABEC2D304143C1FF5B146BAF020EE365D35A1804BE029B0FD1B86620E";
    };
    "nix-public/com/eed3si9n/gigahorse-okhttp_2.12/0.4.0/gigahorse-okhttp_2.12-0.4.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/gigahorse-okhttp_2.12/0.4.0/gigahorse-okhttp_2.12-0.4.0.pom";
      sha256 = "7BF2ADD227EBD3D67F26690779815B25B85D5E0F41D825B411A62595CE28F232";
    };
    "nix-public/com/eed3si9n/shaded-apache-httpclient5/0.9.4/shaded-apache-httpclient5-0.9.4.pom" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/shaded-apache-httpclient5/0.9.4/shaded-apache-httpclient5-0.9.4.pom";
      sha256 = "15F228B947CF1947ED4100FC52506F76D2AF62F238C5D0C0896BE8A15E98F121";
    };
    "nix-public/com/eed3si9n/shaded-jawn-parser_2.12/1.3.2/shaded-jawn-parser-1.3.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/shaded-jawn-parser_2.12/1.3.2/shaded-jawn-parser_2.12-1.3.2.pom";
      sha256 = "1BB26D51BDC7EC05A5421178AF77CCF3C92F35B524ECF8520086A0222A0273FB";
    };
    "nix-public/com/eed3si9n/shaded-jawn-parser_2.12/1.3.2/shaded-jawn-parser_2.12-1.3.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/shaded-jawn-parser_2.12/1.3.2/shaded-jawn-parser_2.12-1.3.2.pom";
      sha256 = "1BB26D51BDC7EC05A5421178AF77CCF3C92F35B524ECF8520086A0222A0273FB";
    };
    "nix-public/com/eed3si9n/shaded-scalajson_2.12/1.0.0-M4/shaded-scalajson-1.0.0-M4.pom" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/shaded-scalajson_2.12/1.0.0-M4/shaded-scalajson_2.12-1.0.0-M4.pom";
      sha256 = "CAF90354288CAB3457A1F80A5B0E204DA43FAD682982051CA0D377EBB37615D0";
    };
    "nix-public/com/eed3si9n/shaded-scalajson_2.12/1.0.0-M4/shaded-scalajson_2.12-1.0.0-M4.pom" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/shaded-scalajson_2.12/1.0.0-M4/shaded-scalajson_2.12-1.0.0-M4.pom";
      sha256 = "CAF90354288CAB3457A1F80A5B0E204DA43FAD682982051CA0D377EBB37615D0";
    };
    "nix-public/com/eed3si9n/sjson-new-core_2.12/0.10.1/sjson-new-core-0.10.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/sjson-new-core_2.12/0.10.1/sjson-new-core_2.12-0.10.1.pom";
      sha256 = "328791285735D73A3CAE2676727AFF42EDB6E58FAD974EF6539147427453E5B0";
    };
    "nix-public/com/eed3si9n/sjson-new-core_2.12/0.10.1/sjson-new-core_2.12-0.10.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/sjson-new-core_2.12/0.10.1/sjson-new-core_2.12-0.10.1.pom";
      sha256 = "328791285735D73A3CAE2676727AFF42EDB6E58FAD974EF6539147427453E5B0";
    };
    "nix-public/com/eed3si9n/sjson-new-murmurhash_2.12/0.10.1/sjson-new-murmurhash-0.10.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/sjson-new-murmurhash_2.12/0.10.1/sjson-new-murmurhash_2.12-0.10.1.pom";
      sha256 = "E5D6AB2243E29FF36407EAF78813BEB4D2E54D5F8D0EAA79338AC33A75EDD0E9";
    };
    "nix-public/com/eed3si9n/sjson-new-murmurhash_2.12/0.10.1/sjson-new-murmurhash_2.12-0.10.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/sjson-new-murmurhash_2.12/0.10.1/sjson-new-murmurhash_2.12-0.10.1.pom";
      sha256 = "E5D6AB2243E29FF36407EAF78813BEB4D2E54D5F8D0EAA79338AC33A75EDD0E9";
    };
    "nix-public/com/eed3si9n/sjson-new-scalajson_2.12/0.10.1/sjson-new-scalajson-0.10.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/sjson-new-scalajson_2.12/0.10.1/sjson-new-scalajson_2.12-0.10.1.pom";
      sha256 = "29446E4D5F74B0406C90FD8DD7CF0704DD28BE3C75094CF2F02289D8A06B34DC";
    };
    "nix-public/com/eed3si9n/sjson-new-scalajson_2.12/0.10.1/sjson-new-scalajson_2.12-0.10.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/sjson-new-scalajson_2.12/0.10.1/sjson-new-scalajson_2.12-0.10.1.pom";
      sha256 = "29446E4D5F74B0406C90FD8DD7CF0704DD28BE3C75094CF2F02289D8A06B34DC";
    };
    "nix-public/com/fasterxml/jackson/jackson-bom/2.19.1/jackson-bom-2.19.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-bom/2.19.1/jackson-bom-2.19.1.pom";
      sha256 = "BA6D68EEAB3A1CC13A77A8ADE2197FF9A32AA1CFFEAC72847D49BADD82E1B9CE";
    };
    "nix-public/com/fasterxml/jackson/jackson-parent/2.19.2/jackson-parent-2.19.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-parent/2.19.2/jackson-parent-2.19.2.pom";
      sha256 = "639A2B63DD05DA4E381081303985CAADFBB7AD9F85B1D2320638F6B11F208365";
    };
    "nix-public/com/fasterxml/oss-parent/68/oss-parent-68.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/oss-parent/68/oss-parent-68.pom";
      sha256 = "25EAFD96DAE242B6B5A7108F55B2C14015B828DAA5ABE234289FD6E774A1CE57";
    };
    "nix-public/com/github/ben-manes/caffeine/caffeine/2.8.5/caffeine-2.8.5.pom" = {
      url = "https://repo1.maven.org/maven2/com/github/ben-manes/caffeine/caffeine/2.8.5/caffeine-2.8.5.pom";
      sha256 = "5E287400775D13334DB5C010E179E29468B3ACD21226D6432A820181661808C6";
    };
    "nix-public/com/github/mwiede/jsch/2.27.5/jsch-2.27.5.pom" = {
      url = "https://repo1.maven.org/maven2/com/github/mwiede/jsch/2.27.5/jsch-2.27.5.pom";
      sha256 = "9E7A1B081DA2631274FB3EDB1E8860B10BEBEFA560C30732F0A7D0C33AAE1FF4";
    };
    "nix-public/com/github/sbt/pgp-library_2.12/2.3.1/pgp-library-2.3.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/sbt/pgp-library_2.12/2.3.1/pgp-library_2.12-2.3.1-sources.jar";
      sha256 = "7F06302FAD0A08EE468FB7EE7D996A89300669EE23F33ADB09DF4A164EAD87EE";
    };
    "nix-public/com/github/sbt/pgp-library_2.12/2.3.1/pgp-library-2.3.1.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/sbt/pgp-library_2.12/2.3.1/pgp-library_2.12-2.3.1.jar";
      sha256 = "974C6FE5B20205F883635208A5BACC59D0015F53099FDD63AA9078BECD08BFE8";
    };
    "nix-public/com/github/sbt/pgp-library_2.12/2.3.1/pgp-library-2.3.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/github/sbt/pgp-library_2.12/2.3.1/pgp-library_2.12-2.3.1.pom";
      sha256 = "F274534FC2B5AEFF6E8ADCD536019D0DF5FF958F634525F1B07A82F109DE7947";
    };
    "nix-public/com/github/sbt/pgp-library_2.12/2.3.1/pgp-library_2.12-2.3.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/sbt/pgp-library_2.12/2.3.1/pgp-library_2.12-2.3.1-sources.jar";
      sha256 = "7F06302FAD0A08EE468FB7EE7D996A89300669EE23F33ADB09DF4A164EAD87EE";
    };
    "nix-public/com/github/sbt/pgp-library_2.12/2.3.1/pgp-library_2.12-2.3.1.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/sbt/pgp-library_2.12/2.3.1/pgp-library_2.12-2.3.1.jar";
      sha256 = "974C6FE5B20205F883635208A5BACC59D0015F53099FDD63AA9078BECD08BFE8";
    };
    "nix-public/com/github/sbt/pgp-library_2.12/2.3.1/pgp-library_2.12-2.3.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/github/sbt/pgp-library_2.12/2.3.1/pgp-library_2.12-2.3.1.pom";
      sha256 = "F274534FC2B5AEFF6E8ADCD536019D0DF5FF958F634525F1B07A82F109DE7947";
    };
    "nix-public/com/github/sbt/sbt-pgp_2.12_1.0/2.3.1/sbt-pgp-2.3.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/sbt/sbt-pgp_2.12_1.0/2.3.1/sbt-pgp_2.12_1.0-2.3.1-sources.jar";
      sha256 = "3D0996DF00DA17105E9057DFA5C2ED9578F57FD535196AFE2B3FE3B2B4CD6184";
    };
    "nix-public/com/github/sbt/sbt-pgp_2.12_1.0/2.3.1/sbt-pgp-2.3.1.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/sbt/sbt-pgp_2.12_1.0/2.3.1/sbt-pgp_2.12_1.0-2.3.1.jar";
      sha256 = "F219C096B0CC5A2102BADB778EA08782F9F345AA455F9F76DB69822F0FC70F2C";
    };
    "nix-public/com/github/sbt/sbt-pgp_2.12_1.0/2.3.1/sbt-pgp-2.3.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/github/sbt/sbt-pgp_2.12_1.0/2.3.1/sbt-pgp_2.12_1.0-2.3.1.pom";
      sha256 = "23C089678A377E0CE90CC9CF12BE5CD4AEB36F3409C8439DCDAB90032DA94EF1";
    };
    "nix-public/com/github/sbt/sbt-pgp_2.12_1.0/2.3.1/sbt-pgp_2.12_1.0-2.3.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/sbt/sbt-pgp_2.12_1.0/2.3.1/sbt-pgp_2.12_1.0-2.3.1-sources.jar";
      sha256 = "3D0996DF00DA17105E9057DFA5C2ED9578F57FD535196AFE2B3FE3B2B4CD6184";
    };
    "nix-public/com/github/sbt/sbt-pgp_2.12_1.0/2.3.1/sbt-pgp_2.12_1.0-2.3.1.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/sbt/sbt-pgp_2.12_1.0/2.3.1/sbt-pgp_2.12_1.0-2.3.1.jar";
      sha256 = "F219C096B0CC5A2102BADB778EA08782F9F345AA455F9F76DB69822F0FC70F2C";
    };
    "nix-public/com/github/sbt/sbt-pgp_2.12_1.0/2.3.1/sbt-pgp_2.12_1.0-2.3.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/github/sbt/sbt-pgp_2.12_1.0/2.3.1/sbt-pgp_2.12_1.0-2.3.1.pom";
      sha256 = "23C089678A377E0CE90CC9CF12BE5CD4AEB36F3409C8439DCDAB90032DA94EF1";
    };
    "nix-public/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.pom";
      sha256 = "19889DBDF1B254B2601A5EE645B8147A974644882297684C798AFE5D63D78DFE";
    };
    "nix-public/com/googlecode/java-diff-utils/diffutils/1.3.0/diffutils-1.3.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/googlecode/java-diff-utils/diffutils/1.3.0/diffutils-1.3.0-sources.jar";
      sha256 = "7F4D40E97827F8A3285C3E47E8D28797ECFD45FB2FF94BD12CB6A83760A5F427";
    };
    "nix-public/com/googlecode/java-diff-utils/diffutils/1.3.0/diffutils-1.3.0.jar" = {
      url = "https://repo1.maven.org/maven2/com/googlecode/java-diff-utils/diffutils/1.3.0/diffutils-1.3.0.jar";
      sha256 = "61BA4DC49ADCA95243BEAA0569ADC2A23AEDB5292AE78AA01186FA782EBDC5C2";
    };
    "nix-public/com/googlecode/java-diff-utils/diffutils/1.3.0/diffutils-1.3.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/googlecode/java-diff-utils/diffutils/1.3.0/diffutils-1.3.0.pom";
      sha256 = "2FE31DD6309B0F5F195BBDC4749CFC0AF065D61F06CFE183DFD2F2092AB847B6";
    };
    "nix-public/com/lmax/disruptor/3.4.2/disruptor-3.4.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/lmax/disruptor/3.4.2/disruptor-3.4.2.pom";
      sha256 = "7311E5E261CA62F259B2D14E6D6F1CE375A64718731A730FD7CEC0228D50F5DA";
    };
    "nix-public/com/squareup/okhttp3/okhttp/3.14.0/okhttp-3.14.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/squareup/okhttp3/okhttp/3.14.0/okhttp-3.14.0-sources.jar";
      sha256 = "771A0EF23EA94FB7F4107B9E900E595022586952F00A3264B0C351723669392D";
    };
    "nix-public/com/squareup/okhttp3/okhttp/3.14.0/okhttp-3.14.0.jar" = {
      url = "https://repo1.maven.org/maven2/com/squareup/okhttp3/okhttp/3.14.0/okhttp-3.14.0.jar";
      sha256 = "FAF6DEB90DDF90346B350BB24F00991F27984C4B0D18DD159B93CBD44131B455";
    };
    "nix-public/com/squareup/okhttp3/okhttp/3.14.0/okhttp-3.14.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/squareup/okhttp3/okhttp/3.14.0/okhttp-3.14.0.pom";
      sha256 = "50919AA53BE393BCF8C9622078AAEB64141EC36A494AD7933052A7EDFC401EBF";
    };
    "nix-public/com/squareup/okhttp3/parent/3.14.0/parent-3.14.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/squareup/okhttp3/parent/3.14.0/parent-3.14.0.pom";
      sha256 = "410CE2AD824A6D0949112A8786F26F169BF892C3CC1565930D3F13270B367DF7";
    };
    "nix-public/com/squareup/okio/okio-parent/1.17.2/okio-parent-1.17.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/squareup/okio/okio-parent/1.17.2/okio-parent-1.17.2.pom";
      sha256 = "E81F40146F2A0EB394B10FA3A175C85AB9FBE757AA418AA44D4B760EFE16F024";
    };
    "nix-public/com/squareup/okio/okio/1.17.2/okio-1.17.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/squareup/okio/okio/1.17.2/okio-1.17.2-sources.jar";
      sha256 = "F96949004BDC5951C27256B96C33667D3DBD5369C467A8FA0D4157DBA98B4252";
    };
    "nix-public/com/squareup/okio/okio/1.17.2/okio-1.17.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/squareup/okio/okio/1.17.2/okio-1.17.2.jar";
      sha256 = "F80CE42D2FFAC47AD4C47E1D6F980D604D247CEB1A886705CF4581AB0C9FE2B8";
    };
    "nix-public/com/squareup/okio/okio/1.17.2/okio-1.17.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/squareup/okio/okio/1.17.2/okio-1.17.2.pom";
      sha256 = "CD57F75443AB6A714B203DA51994EE64ED0E919FEA81F04E4F4B5324E4BB03F0";
    };
    "nix-public/com/sun/activation/all/1.2.0/all-1.2.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/sun/activation/all/1.2.0/all-1.2.0.pom";
      sha256 = "1D8518E3AC7532A104E4F7BE77DEF37C982E530723C6BDB3D67708CCE2B0C2C4";
    };
    "nix-public/com/sun/activation/all/2.0.1/all-2.0.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/sun/activation/all/2.0.1/all-2.0.1.pom";
      sha256 = "648D5D62B6153F42F190CED2D6E70C1E6442550C9CFEB66FBEE0961C6616B2CC";
    };
    "nix-public/com/sun/activation/jakarta.activation/2.0.1/jakarta.activation-2.0.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/sun/activation/jakarta.activation/2.0.1/jakarta.activation-2.0.1.pom";
      sha256 = "8A068592DB08E6853204FF0B625A301438E3C36EA5F1AE65BABFED208502781A";
    };
    "nix-public/com/sun/activation/javax.activation/1.2.0/javax.activation-1.2.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/sun/activation/javax.activation/1.2.0/javax.activation-1.2.0.pom";
      sha256 = "F879B6E945854C6900B0DBEE1C8384D7AB3DE7E157FD7AC84937405C416D2A5E";
    };
    "nix-public/com/sun/mail/all/2.0.1/all-2.0.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/sun/mail/all/2.0.1/all-2.0.1.pom";
      sha256 = "1B8B941E98ABAC6CA94E91A60323728ABDC46E391BDAC5C7368F458773332266";
    };
    "nix-public/com/sun/mail/jakarta.mail/2.0.1/jakarta.mail-2.0.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/sun/mail/jakarta.mail/2.0.1/jakarta.mail-2.0.1.pom";
      sha256 = "65CE182014C8009A84C9605E3DF3E85E3EED98B5691A16BDB3DEA5DC1D33D3BD";
    };
    "nix-public/com/swoval/file-tree-views/2.1.12/file-tree-views-2.1.12.pom" = {
      url = "https://repo1.maven.org/maven2/com/swoval/file-tree-views/2.1.12/file-tree-views-2.1.12.pom";
      sha256 = "EDD270DC776D1D85DD300E415CFF9E0609757D7AFEB223A6B187BAD5B0ABE746";
    };
    "nix-public/com/typesafe/config/1.4.5/config-1.4.5-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.4.5/config-1.4.5-sources.jar";
      sha256 = "4E17AD7D6A83922A9F1F7B65A33A2D33052A85314303D6F6E318CA3CAF9C5D75";
    };
    "nix-public/com/typesafe/config/1.4.5/config-1.4.5.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.4.5/config-1.4.5.jar";
      sha256 = "4A4B0AFFB22A9572409D3A6BDE99CE3F2045C551CADC1CA7FE09690892C526C3";
    };
    "nix-public/com/typesafe/config/1.4.5/config-1.4.5.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.4.5/config-1.4.5.pom";
      sha256 = "FF3255EEC0EC8BD5F0653738EC1B48342A6A90E3D4EAC7A56F904C6AE2E12ED5";
    };
    "nix-public/com/typesafe/ssl-config-core_2.12/0.2.2/ssl-config-core-0.2.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/ssl-config-core_2.12/0.2.2/ssl-config-core_2.12-0.2.2-sources.jar";
      sha256 = "6B8B6F4135E7BCCE10A8507B7B9F8A70982E71F34926B9F2118706F82793B410";
    };
    "nix-public/com/typesafe/ssl-config-core_2.12/0.2.2/ssl-config-core-0.2.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/ssl-config-core_2.12/0.2.2/ssl-config-core_2.12-0.2.2.jar";
      sha256 = "CF144EC0ADEB7F97DA59542910EF18471F03FDE2E174148E711B7F071155C7E4";
    };
    "nix-public/com/typesafe/ssl-config-core_2.12/0.2.2/ssl-config-core-0.2.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/ssl-config-core_2.12/0.2.2/ssl-config-core_2.12-0.2.2.pom";
      sha256 = "521E96B4352FF2CB3B1D4FE7BBB935E53D1BCA9412DD1BC9D2E61F7027A1938F";
    };
    "nix-public/com/typesafe/ssl-config-core_2.12/0.2.2/ssl-config-core_2.12-0.2.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/ssl-config-core_2.12/0.2.2/ssl-config-core_2.12-0.2.2-sources.jar";
      sha256 = "6B8B6F4135E7BCCE10A8507B7B9F8A70982E71F34926B9F2118706F82793B410";
    };
    "nix-public/com/typesafe/ssl-config-core_2.12/0.2.2/ssl-config-core_2.12-0.2.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/ssl-config-core_2.12/0.2.2/ssl-config-core_2.12-0.2.2.jar";
      sha256 = "CF144EC0ADEB7F97DA59542910EF18471F03FDE2E174148E711B7F071155C7E4";
    };
    "nix-public/com/typesafe/ssl-config-core_2.12/0.2.2/ssl-config-core_2.12-0.2.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/ssl-config-core_2.12/0.2.2/ssl-config-core_2.12-0.2.2.pom";
      sha256 = "521E96B4352FF2CB3B1D4FE7BBB935E53D1BCA9412DD1BC9D2E61F7027A1938F";
    };
    "nix-public/com/typesafe/ssl-config-core_2.12/0.7.1/ssl-config-core-0.7.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/ssl-config-core_2.12/0.7.1/ssl-config-core_2.12-0.7.1.pom";
      sha256 = "BDBA333C63A806053BA36B5D465D52EAEC21501678D44F6E014AB647B2A1D10A";
    };
    "nix-public/com/typesafe/ssl-config-core_2.12/0.7.1/ssl-config-core_2.12-0.7.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/ssl-config-core_2.12/0.7.1/ssl-config-core_2.12-0.7.1.pom";
      sha256 = "BDBA333C63A806053BA36B5D465D52EAEC21501678D44F6E014AB647B2A1D10A";
    };
    "nix-public/commons-codec/commons-codec/1.17.1/commons-codec-1.17.1.pom" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.17.1/commons-codec-1.17.1.pom";
      sha256 = "7FA0DB4D8150DAF932958B8AEA89EE24ABB4D18E2316A5DE535278FC131512A0";
    };
    "nix-public/commons-io/commons-io/2.16.1/commons-io-2.16.1.pom" = {
      url = "https://repo1.maven.org/maven2/commons-io/commons-io/2.16.1/commons-io-2.16.1.pom";
      sha256 = "5777D292251C7895C04A4C57015683EC3B353A12486C9B3E7178E9B0B3C38FFF";
    };
    "nix-public/commons-logging/commons-logging/1.2/commons-logging-1.2.pom" = {
      url = "https://repo1.maven.org/maven2/commons-logging/commons-logging/1.2/commons-logging-1.2.pom";
      sha256 = "C91AB5AA570D86F6FD07CC158EC6BC2C50080402972EE9179FE24100739FBB20";
    };
    "nix-public/io/get-coursier/lm-coursier-shaded_2.12/2.1.13/lm-coursier-shaded-2.1.13.pom" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/lm-coursier-shaded_2.12/2.1.13/lm-coursier-shaded_2.12-2.1.13.pom";
      sha256 = "C4C3CEA80BDFD1EC6895874845E3B931C62D0E653E036B366B421AF5637460C6";
    };
    "nix-public/io/get-coursier/lm-coursier-shaded_2.12/2.1.13/lm-coursier-shaded_2.12-2.1.13.pom" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/lm-coursier-shaded_2.12/2.1.13/lm-coursier-shaded_2.12-2.1.13.pom";
      sha256 = "C4C3CEA80BDFD1EC6895874845E3B931C62D0E653E036B366B421AF5637460C6";
    };
    "nix-public/jakarta/platform/jakarta.jakartaee-bom/9.1.0/jakarta.jakartaee-bom-9.1.0.pom" = {
      url = "https://repo1.maven.org/maven2/jakarta/platform/jakarta.jakartaee-bom/9.1.0/jakarta.jakartaee-bom-9.1.0.pom";
      sha256 = "DF98E0266219FDBB82562826D79A3A20776A8BA02AA787F0F0765A538654C8A4";
    };
    "nix-public/jakarta/platform/jakartaee-api-parent/9.1.0/jakartaee-api-parent-9.1.0.pom" = {
      url = "https://repo1.maven.org/maven2/jakarta/platform/jakartaee-api-parent/9.1.0/jakartaee-api-parent-9.1.0.pom";
      sha256 = "A7702C487026802784B5797B62330A8B8D6592BF0F4737B25C67A5EAC82659C0";
    };
    "nix-public/javax/activation/javax.activation-api/1.2.0/javax.activation-api-1.2.0.pom" = {
      url = "https://repo1.maven.org/maven2/javax/activation/javax.activation-api/1.2.0/javax.activation-api-1.2.0.pom";
      sha256 = "DA2926F3C8BE898643CC10ACDEC6DE0B0351A57FB2735770FA0177B06ADE71B9";
    };
    "nix-public/javax/inject/javax.inject/1/javax.inject-1.pom" = {
      url = "https://repo1.maven.org/maven2/javax/inject/javax.inject/1/javax.inject-1.pom";
      sha256 = "943E12B100627804638FA285805A0AB788A680266531E650921EBFE4621A8BFA";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6-sources.jar" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6-sources.jar";
      sha256 = "319A840705E1E46ABE579DD3D079B508558791E0236BC78DA01911748E06AF93";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6-tests.jar" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6-tests.jar";
      sha256 = "AE143A7DC135371F446A44775E8D5337D97151D5FEEC8CA8575F3A718DDF35F3";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6.jar" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6.jar";
      sha256 = "97D1ACAAC82409BE42E622D7A54D3AE9D08517E8AEFDEA3D2BA9791150C2F02D";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6.pom" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6.pom";
      sha256 = "1DF7B6F08DFB81A268D6B93B659A6A9E389C5D8C32BDF0754238BA6483A4E982";
    };
    "nix-public/junit/junit/4.13.2/junit-4.13.2.pom" = {
      url = "https://repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.pom";
      sha256 = "569B6977EE4603C965C1C46C3058FA6E969291B0160EB6964DD092CD89EADD94";
    };
    "nix-public/net/java/dev/jna/jna-platform/5.12.0/jna-platform-5.12.0.pom" = {
      url = "https://repo1.maven.org/maven2/net/java/dev/jna/jna-platform/5.12.0/jna-platform-5.12.0.pom";
      sha256 = "FCD900B44FEC7361A6ECEED13309A88DD447DB1526E141D0412AA81292775DDB";
    };
    "nix-public/net/java/dev/jna/jna/5.12.0/jna-5.12.0.pom" = {
      url = "https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.12.0/jna-5.12.0.pom";
      sha256 = "154B5D0977E081C9654770AF90A35CD2BE9FA6C575B16AE239C01161496B3313";
    };
    "nix-public/net/java/dev/jna/jna/5.15.0/jna-5.15.0.pom" = {
      url = "https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.15.0/jna-5.15.0.pom";
      sha256 = "276602FF367A4C39155DAECC1E8CB54F4789E5D80DF90A3A8B6603F1DEB59E05";
    };
    "nix-public/net/java/jvnet-parent/1/jvnet-parent-1.pom" = {
      url = "https://repo1.maven.org/maven2/net/java/jvnet-parent/1/jvnet-parent-1.pom";
      sha256 = "281440811268E65D9E266B3CC898297E214E04F09740D0386CEEB4A8923D63BF";
    };
    "nix-public/net/openhft/java-parent-pom/1.1.28/java-parent-pom-1.1.28.pom" = {
      url = "https://repo1.maven.org/maven2/net/openhft/java-parent-pom/1.1.28/java-parent-pom-1.1.28.pom";
      sha256 = "02199C347A9D2B9E6F5DBF8E13D4C34E8FEBFAB90C9B81FBA13A16E8208809BF";
    };
    "nix-public/net/openhft/root-parent-pom/1.2.12/root-parent-pom-1.2.12.pom" = {
      url = "https://repo1.maven.org/maven2/net/openhft/root-parent-pom/1.2.12/root-parent-pom-1.2.12.pom";
      sha256 = "31802B4C86422D91AC5337DAD705113535CA986F7CD7BC239701B9F9DF967CCF";
    };
    "nix-public/net/openhft/zero-allocation-hashing/0.16/zero-allocation-hashing-0.16.pom" = {
      url = "https://repo1.maven.org/maven2/net/openhft/zero-allocation-hashing/0.16/zero-allocation-hashing-0.16.pom";
      sha256 = "0949496963193655F81AFB9DBA28743444DD2A23A6F4933638A6991CFD728FC6";
    };
    "nix-public/org/apache/apache/13/apache-13.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/apache/13/apache-13.pom";
      sha256 = "FF513DB0361FD41237BEF4784968BC15AAE478D4EC0A9496F811072CCAF3841D";
    };
    "nix-public/org/apache/apache/21/apache-21.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/apache/21/apache-21.pom";
      sha256 = "AF10C108DA014F17CAFAC7B52B2B4B5A3A1C18265FA2AF97A325D9143537B380";
    };
    "nix-public/org/apache/apache/31/apache-31.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/apache/31/apache-31.pom";
      sha256 = "555D0C9EAA69C042AFF924927B9381E8F8174136D355EEAD445224452E6291CC";
    };
    "nix-public/org/apache/apache/32/apache-32.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/apache/32/apache-32.pom";
      sha256 = "CFD872C0EC27F53AE68F43DBC0FECDED8ADD773079A53AFBD390E407B42CE72F";
    };
    "nix-public/org/apache/apache/33/apache-33.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/apache/33/apache-33.pom";
      sha256 = "D78BD8524C5F8380A190A6525686629A95DFE512DF21111383A6D8C0923A4415";
    };
    "nix-public/org/apache/commons/commons-compress/1.27.1/commons-compress-1.27.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.27.1/commons-compress-1.27.1.pom";
      sha256 = "DF8CC1A8387D4CE842363B7209FDC6D35DF9763839FD3FCAB558A0F83F9D841C";
    };
    "nix-public/org/apache/commons/commons-lang3/3.16.0/commons-lang3-3.16.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.16.0/commons-lang3-3.16.0.pom";
      sha256 = "E280383956C2E72C1DEB3A307B3B75F05EE43649B7D43F0215F7B6C7B15EEA2C";
    };
    "nix-public/org/apache/commons/commons-lang3/3.17.0/commons-lang3-3.17.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.17.0/commons-lang3-3.17.0.pom";
      sha256 = "351C6E4940E939B1F330DF47F60F13BA383DB81EE008181AF541F3A2A6D2A56C";
    };
    "nix-public/org/apache/commons/commons-parent/34/commons-parent-34.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-parent/34/commons-parent-34.pom";
      sha256 = "3A2E69D06D641D1F3B293126DC9E2E4EA6563BF8C36C87E0AB6FA4292D04B79C";
    };
    "nix-public/org/apache/commons/commons-parent/69/commons-parent-69.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-parent/69/commons-parent-69.pom";
      sha256 = "D50DA9C39BDCA823D618D1B4A03B73F196497FCB8616FD0DA727C8623592A9BB";
    };
    "nix-public/org/apache/commons/commons-parent/71/commons-parent-71.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-parent/71/commons-parent-71.pom";
      sha256 = "95B7BE70F316AE4CA22F6FBDD08DE2182E87CD874A650DE7C3D3386A747A82A3";
    };
    "nix-public/org/apache/commons/commons-parent/72/commons-parent-72.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-parent/72/commons-parent-72.pom";
      sha256 = "4345DEBFC767B1AEAC68ABDD72FC67D18B521D4B390372A11B63FF0C586B2320";
    };
    "nix-public/org/apache/commons/commons-parent/73/commons-parent-73.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-parent/73/commons-parent-73.pom";
      sha256 = "4ED44560B07F8448479DFD1E83A422BA4E83E60B36E51B2871AC502A6D5C1BEA";
    };
    "nix-public/org/apache/groovy/groovy-bom/4.0.27/groovy-bom-4.0.27.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/groovy/groovy-bom/4.0.27/groovy-bom-4.0.27.pom";
      sha256 = "AA44EB52BFDFE61D27B3E450D2B348D88DEAA3437AB4D9D49A84095348F9F6FB";
    };
    "nix-public/org/apache/httpcomponents/httpclient/4.5.14/httpclient-4.5.14.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.5.14/httpclient-4.5.14.pom";
      sha256 = "F18355AF4CF80A8A4EF04EBD742A47E90A7EAF080C725B2095DBC4FC5DBDEFB7";
    };
    "nix-public/org/apache/httpcomponents/httpcomponents-client/4.5.14/httpcomponents-client-4.5.14.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcomponents-client/4.5.14/httpcomponents-client-4.5.14.pom";
      sha256 = "5BAD1DE4F101447659F89D089868CCBAD64A68CC503D2D65410B51F6904AA061";
    };
    "nix-public/org/apache/httpcomponents/httpcomponents-core/4.4.16/httpcomponents-core-4.4.16.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcomponents-core/4.4.16/httpcomponents-core-4.4.16.pom";
      sha256 = "F2D75A2C2D423AD18539BF21656D56F88A4091944A662FCAF159D5AE283DB7F7";
    };
    "nix-public/org/apache/httpcomponents/httpcomponents-parent/11/httpcomponents-parent-11.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcomponents-parent/11/httpcomponents-parent-11.pom";
      sha256 = "A901F87B115C55070C7EE43EFFF63E20E7B02D30AF2443AE292BF1F4E532D3AA";
    };
    "nix-public/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.pom";
      sha256 = "3CBAD849B35DACFE6CEC31ADADA2C623C026C3261141B0D26EEC7E399C6CD7FA";
    };
    "nix-public/org/apache/logging/log4j/log4j-api/2.25.4/log4j-api-2.25.4.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.25.4/log4j-api-2.25.4.pom";
      sha256 = "943A43DA1430DBEB501ABD08972F283EA89F3B1DBFC4252EC3059543B4E06B55";
    };
    "nix-public/org/apache/logging/log4j/log4j-bom/2.25.4/log4j-bom-2.25.4.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-bom/2.25.4/log4j-bom-2.25.4.pom";
      sha256 = "7313D339FB632A8610E1140B3290FC24D63743B9AA625E2A0BD59DED40A3AE54";
    };
    "nix-public/org/apache/logging/log4j/log4j-core/2.25.4/log4j-core-2.25.4.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.25.4/log4j-core-2.25.4.pom";
      sha256 = "34C073FC74966DAFA44CC5BFD76DE5E3668EA240F284BAB8478E417EE03A56AA";
    };
    "nix-public/org/apache/logging/log4j/log4j-slf4j-impl/2.25.4/log4j-slf4j-impl-2.25.4.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-slf4j-impl/2.25.4/log4j-slf4j-impl-2.25.4.pom";
      sha256 = "C4E02CC4C29D164B47AE6F388EF01AD90228FEFC76923A9E0F76B2DD5C5D001F";
    };
    "nix-public/org/apache/logging/log4j/log4j/2.25.4/log4j-2.25.4.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j/2.25.4/log4j-2.25.4.pom";
      sha256 = "F8AE8904A28E34FA04C35D3740619DAE83632401BA1E313BAFD7CCF5A3000DEC";
    };
    "nix-public/org/bouncycastle/bcpg-jdk18on/1.78.1/bcpg-jdk18on-1.78.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/bouncycastle/bcpg-jdk18on/1.78.1/bcpg-jdk18on-1.78.1-sources.jar";
      sha256 = "6A2D15047188285CF084BAC95DC9BB5EF29FE98ABB1C6A5149D5E9B484D67E6C";
    };
    "nix-public/org/bouncycastle/bcpg-jdk18on/1.78.1/bcpg-jdk18on-1.78.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/bouncycastle/bcpg-jdk18on/1.78.1/bcpg-jdk18on-1.78.1.jar";
      sha256 = "1463BB2CB8737E9AE34F5BD93F48E27711365BB277F4918F44608ED89B68792D";
    };
    "nix-public/org/bouncycastle/bcpg-jdk18on/1.78.1/bcpg-jdk18on-1.78.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/bouncycastle/bcpg-jdk18on/1.78.1/bcpg-jdk18on-1.78.1.pom";
      sha256 = "5BDC23AD5FC7DEE999F433F2176FEA933FD52F0D6C2C8CA44CA6B18F13E37241";
    };
    "nix-public/org/bouncycastle/bcprov-jdk18on/1.78.1/bcprov-jdk18on-1.78.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk18on/1.78.1/bcprov-jdk18on-1.78.1-sources.jar";
      sha256 = "BE87A544D921152CEDCEF4B740155047EF2F402544D47382B8C0B15DEC11A642";
    };
    "nix-public/org/bouncycastle/bcprov-jdk18on/1.78.1/bcprov-jdk18on-1.78.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk18on/1.78.1/bcprov-jdk18on-1.78.1.jar";
      sha256 = "ADD5915E6ACFC6AB5836E1FD8A5E21C6488536A8C1F21F386EEB3BF280B702D7";
    };
    "nix-public/org/bouncycastle/bcprov-jdk18on/1.78.1/bcprov-jdk18on-1.78.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk18on/1.78.1/bcprov-jdk18on-1.78.1.pom";
      sha256 = "28912D139F9EED141C394371FBE5BA6FFFF91E78F1C9CB8348F944A24D204ED2";
    };
    "nix-public/org/bouncycastle/bcutil-jdk18on/1.78.1/bcutil-jdk18on-1.78.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/bouncycastle/bcutil-jdk18on/1.78.1/bcutil-jdk18on-1.78.1-sources.jar";
      sha256 = "667B6334FF25C4303D3B1AF02599F8547FCC37D0D55393BCB17DE4F179C78BAA";
    };
    "nix-public/org/bouncycastle/bcutil-jdk18on/1.78.1/bcutil-jdk18on-1.78.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/bouncycastle/bcutil-jdk18on/1.78.1/bcutil-jdk18on-1.78.1.jar";
      sha256 = "D9FA56F97B0F761CE3BC8D9D74C5D7137A987BF5BD3ABFE1003F9BAFA45A1D2F";
    };
    "nix-public/org/bouncycastle/bcutil-jdk18on/1.78.1/bcutil-jdk18on-1.78.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/bouncycastle/bcutil-jdk18on/1.78.1/bcutil-jdk18on-1.78.1.pom";
      sha256 = "741D55CB45C4C2C889B5A436B747DC2152923132E426BE6EF55500EEE7FA5312";
    };
    "nix-public/org/eclipse/ee4j/project/1.0.6/project-1.0.6.pom" = {
      url = "https://repo1.maven.org/maven2/org/eclipse/ee4j/project/1.0.6/project-1.0.6.pom";
      sha256 = "4E7D8329D8DA7DCF30779D824241BE145F27108932F5A5A24EB907677BC8D72D";
    };
    "nix-public/org/eclipse/ee4j/project/1.0.7/project-1.0.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/eclipse/ee4j/project/1.0.7/project-1.0.7.pom";
      sha256 = "205C039A42CBAE3556EFBEB04A483EB3A3CF9550BD75BF84260DC8F28218F105";
    };
    "nix-public/org/fusesource/fusesource-pom/1.12/fusesource-pom-1.12.pom" = {
      url = "https://repo1.maven.org/maven2/org/fusesource/fusesource-pom/1.12/fusesource-pom-1.12.pom";
      sha256 = "C40D960DAADCEF7B01C1B1C6657AFBAC4FFFB5E53168F8FCB0B28B84E6FDCCA1";
    };
    "nix-public/org/fusesource/jansi/jansi/2.4.1/jansi-2.4.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/2.4.1/jansi-2.4.1.pom";
      sha256 = "3F98D979A4D3559F8779FBB004B34AE7516AFADF510E11DF7CC3CD073EB1BB3B";
    };
    "nix-public/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.pom";
      sha256 = "FDE386A7905173A1B103DE6AB820727584B50D0E32282E2797787C20A64FFA93";
    };
    "nix-public/org/hamcrest/hamcrest-parent/1.3/hamcrest-parent-1.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/hamcrest/hamcrest-parent/1.3/hamcrest-parent-1.3.pom";
      sha256 = "6D535F94EFB663BDB682C9F27A50335394688009642BA7A9677504BC1BE4129B";
    };
    "nix-public/org/jline/jline-builtins/3.27.1/jline-builtins-3.27.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-builtins/3.27.1/jline-builtins-3.27.1.pom";
      sha256 = "7771F3BF04A1592BB0420D2280FA7718C572591BD4CEEB3CF443CB83C68172AE";
    };
    "nix-public/org/jline/jline-native/3.27.1/jline-native-3.27.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-native/3.27.1/jline-native-3.27.1.pom";
      sha256 = "9FFE28AECC9F546EC9695F2D521F67459B4B36917148C08D16F4556B383D328F";
    };
    "nix-public/org/jline/jline-parent/3.27.1/jline-parent-3.27.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-parent/3.27.1/jline-parent-3.27.1.pom";
      sha256 = "E964FD076C20CE24DDB48DD737A08D6050347005E3E6EEC82FF5EB043D561581";
    };
    "nix-public/org/jline/jline-reader/3.27.1/jline-reader-3.27.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-reader/3.27.1/jline-reader-3.27.1.pom";
      sha256 = "1AE3547D6DF3045AE9339CBDA2571868263BE1B73C7673D17057A505CACF1F08";
    };
    "nix-public/org/jline/jline-style/3.27.1/jline-style-3.27.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-style/3.27.1/jline-style-3.27.1.pom";
      sha256 = "2FD933346D21AB2AB2D04BA360ED33F1B383203D3474CB24D34A6497D6741311";
    };
    "nix-public/org/jline/jline-terminal-jni/3.27.1/jline-terminal-jni-3.27.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-terminal-jni/3.27.1/jline-terminal-jni-3.27.1.pom";
      sha256 = "52448DE3CBF55F80701484CB4A23B58CB1B0D8FEAA86DBDDC321360724369757";
    };
    "nix-public/org/jline/jline-terminal/3.27.1/jline-terminal-3.27.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-terminal/3.27.1/jline-terminal-3.27.1.pom";
      sha256 = "8478E79AA22EA6AF79796443F8ED30FFFA5DC647EB3D2D1860BAC2E23F34D297";
    };
    "nix-public/org/junit/junit-bom/5.10.2/junit-bom-5.10.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/junit/junit-bom/5.10.2/junit-bom-5.10.2.pom";
      sha256 = "169DD904A4B0F6520CFFE658CC62292BFE9F3C14A989FA92120724CDE43A9968";
    };
    "nix-public/org/junit/junit-bom/5.11.0-M2/junit-bom-5.11.0-M2.pom" = {
      url = "https://repo1.maven.org/maven2/org/junit/junit-bom/5.11.0-M2/junit-bom-5.11.0-M2.pom";
      sha256 = "4A3FFC4A4EDCFEC2CB5D619922706A9407161798571939F854DFDA73E4E17CC8";
    };
    "nix-public/org/junit/junit-bom/5.11.0/junit-bom-5.11.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/junit/junit-bom/5.11.0/junit-bom-5.11.0.pom";
      sha256 = "E67459D4882424AC6374F40DB1C8F4A2E88946B340BA072C80BE932A2BE4644D";
    };
    "nix-public/org/junit/junit-bom/5.13.2/junit-bom-5.13.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/junit/junit-bom/5.13.2/junit-bom-5.13.2.pom";
      sha256 = "43B1104FB3FD4EF4B72A9751D41E09C29F001C8BE00FF3972238DC169A734B49";
    };
    "nix-public/org/mockito/mockito-bom/4.11.0/mockito-bom-4.11.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/mockito/mockito-bom/4.11.0/mockito-bom-4.11.0.pom";
      sha256 = "D8531A746C988F7F68ED5F188CDEA945006AEA993EC5DF9E524E0D27D61491DA";
    };
    "nix-public/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2-sources.jar";
      sha256 = "963A6480F46A64013D0F144BA41C6C6E63C4D34B655761717A436492886F3667";
    };
    "nix-public/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.jar";
      sha256 = "CC09AB0B140E0D0496C2165D4B32CE24F4D6446C0A26C5DC77B06BDF99EE8FAE";
    };
    "nix-public/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.pom";
      sha256 = "5B626A99E5734BA8D0C0C8C3FC6258AFA0624F4CE61AE1192247D03C57463DED";
    };
    "nix-public/org/reactivestreams/reactive-streams/1.0.3/reactive-streams-1.0.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/reactivestreams/reactive-streams/1.0.3/reactive-streams-1.0.3.pom";
      sha256 = "CCED467175F4257833F6CB07510FF97B3C75A06E1A58D882A39D79853D51C602";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.12/2.14.0/scala-collection-compat-2.14.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.12/2.14.0/scala-collection-compat_2.12-2.14.0.pom";
      sha256 = "7D33231F1D3A5A09F831A6C73F7603CEF37A3EEF4674A49B5FE27D63AB666734";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.12/2.14.0/scala-collection-compat_2.12-2.14.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.12/2.14.0/scala-collection-compat_2.12-2.14.0.pom";
      sha256 = "7D33231F1D3A5A09F831A6C73F7603CEF37A3EEF4674A49B5FE27D63AB666734";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators-1.1.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2-sources.jar";
      sha256 = "8FBE3FA9E748F24AA6D6868C0C2BE30D41A02D20428ED5429BB57A897CB756E3";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators-1.1.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2.jar";
      sha256 = "24985EB43E295A9DD77905ADA307A850CA25ACF819CDB579C093FC6987B0DBC2";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators-1.1.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2.pom";
      sha256 = "A5500678F39B9B8C962A8FEE98359E9E2F2A4E5D434F3501762B30188642A2F5";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2-sources.jar";
      sha256 = "8FBE3FA9E748F24AA6D6868C0C2BE30D41A02D20428ED5429BB57A897CB756E3";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2.jar";
      sha256 = "24985EB43E295A9DD77905ADA307A850CA25ACF819CDB579C093FC6987B0DBC2";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2.pom";
      sha256 = "A5500678F39B9B8C962A8FEE98359E9E2F2A4E5D434F3501762B30188642A2F5";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.2.0/scala-xml-2.2.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.2.0/scala-xml_2.12-2.2.0.pom";
      sha256 = "81B0510AB4A86724912246E0E18F3988A7086BDE716D819CA7F937474BAC34AC";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.2.0/scala-xml_2.12-2.2.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.2.0/scala-xml_2.12-2.2.0.pom";
      sha256 = "81B0510AB4A86724912246E0E18F3988A7086BDE716D819CA7F937474BAC34AC";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml-2.3.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0-sources.jar";
      sha256 = "BB93B2FDCD36EBD3E7E6E6DE961CD2A4EAD3815C9565C7BE5CAD860CF3D8C81C";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml-2.3.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0.jar";
      sha256 = "4932C56A2D5AAE77AE8D7AC6BED1F21D48268FDBAC8B4E5F3CA5196AD10FD93E";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml-2.3.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0.pom";
      sha256 = "45BC645F881F34E6338B478007C6DD93D17389A4F4138616AE7EFA854BAAAA46";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0-sources.jar";
      sha256 = "BB93B2FDCD36EBD3E7E6E6DE961CD2A4EAD3815C9565C7BE5CAD860CF3D8C81C";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0.jar";
      sha256 = "4932C56A2D5AAE77AE8D7AC6BED1F21D48268FDBAC8B4E5F3CA5196AD10FD93E";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0.pom";
      sha256 = "45BC645F881F34E6338B478007C6DD93D17389A4F4138616AE7EFA854BAAAA46";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.20/scala-compiler-2.12.20.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.20/scala-compiler-2.12.20.pom";
      sha256 = "D04B837110423B145973F9A6516AB6AFD9C09C50543B8C7C63AC6C90AD4CCAA3";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.21/scala-compiler-2.12.21.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.21/scala-compiler-2.12.21.pom";
      sha256 = "4253340C4791B50E487EBEBC35832E412279A6A6743D92948904166147FBEAEA";
    };
    "nix-public/org/scala-lang/scala-library/2.12.18/scala-library-2.12.18.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.18/scala-library-2.12.18.pom";
      sha256 = "C7BCAE55EB71211DCB3305FD5EAFF1ADD551C53A8B6173C1C02D800C6EACF097";
    };
    "nix-public/org/scala-lang/scala-library/2.12.20/scala-library-2.12.20.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.20/scala-library-2.12.20.pom";
      sha256 = "94C315B4C51A4C8D0A33F177E160DDAD63B68595FEB3997FA25791C5A14A03C9";
    };
    "nix-public/org/scala-lang/scala-library/2.12.21/scala-library-2.12.21.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.21/scala-library-2.12.21.pom";
      sha256 = "F0CB22ADB1668EDE4B19E273096E9D97CD35F9864C7F28B5A2E5C21E08CA6847";
    };
    "nix-public/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.pom";
      sha256 = "22E81EE9D5349BA0E897ADB5C7FCEC25656C9E0B7B86C3E93E9A7AF360481C0D";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.20/scala-reflect-2.12.20.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.20/scala-reflect-2.12.20.pom";
      sha256 = "6151C44B5EC49F7E9555450D6ACE47E994129B511119CF364045E18864AF8E96";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.21/scala-reflect-2.12.21.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.21/scala-reflect-2.12.21.pom";
      sha256 = "66DC35AA4123EFD8A550B963D82FDFA2BAD17878D627647E39967ACB4B7B4167";
    };
    "nix-public/org/scala-sbt/actions_2.12/1.12.11/actions-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/actions_2.12/1.12.11/actions_2.12-1.12.11.pom";
      sha256 = "F5121EC91C503EB3483BD8BF60E01C302E35A38B017EFAF3A4F18918DF9AA937";
    };
    "nix-public/org/scala-sbt/actions_2.12/1.12.11/actions_2.12-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/actions_2.12/1.12.11/actions_2.12-1.12.11.pom";
      sha256 = "F5121EC91C503EB3483BD8BF60E01C302E35A38B017EFAF3A4F18918DF9AA937";
    };
    "nix-public/org/scala-sbt/collections_2.12/1.12.11/collections-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/collections_2.12/1.12.11/collections_2.12-1.12.11.pom";
      sha256 = "9059EC9AB14CE378156FCE16B1C97DA21DE3076E4057CA80EDEF990DF8B98B6C";
    };
    "nix-public/org/scala-sbt/collections_2.12/1.12.11/collections_2.12-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/collections_2.12/1.12.11/collections_2.12-1.12.11.pom";
      sha256 = "9059EC9AB14CE378156FCE16B1C97DA21DE3076E4057CA80EDEF990DF8B98B6C";
    };
    "nix-public/org/scala-sbt/command_2.12/1.12.11/command-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/command_2.12/1.12.11/command_2.12-1.12.11.pom";
      sha256 = "45731738E5F4D917D82336CD53392F19912E5524C7F2A03F349B3C758F186634";
    };
    "nix-public/org/scala-sbt/command_2.12/1.12.11/command_2.12-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/command_2.12/1.12.11/command_2.12-1.12.11.pom";
      sha256 = "45731738E5F4D917D82336CD53392F19912E5524C7F2A03F349B3C758F186634";
    };
    "nix-public/org/scala-sbt/compiler-bridge_2.12/1.12.0/compiler-bridge-1.12.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.12/1.12.0/compiler-bridge_2.12-1.12.0.pom";
      sha256 = "0D53D08A626CA53E82296A7E3BD2559F361A0E5101257D5B433B81104AAA872C";
    };
    "nix-public/org/scala-sbt/compiler-bridge_2.12/1.12.0/compiler-bridge_2.12-1.12.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.12/1.12.0/compiler-bridge_2.12-1.12.0.pom";
      sha256 = "0D53D08A626CA53E82296A7E3BD2559F361A0E5101257D5B433B81104AAA872C";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.12.0/compiler-interface-1.12.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.12.0/compiler-interface-1.12.0.pom";
      sha256 = "B5CFD5574AD88819D64E3D4B50F909D399BB836BA56883D37EF13D9D13B6C214";
    };
    "nix-public/org/scala-sbt/completion_2.12/1.12.11/completion-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/completion_2.12/1.12.11/completion_2.12-1.12.11.pom";
      sha256 = "FB77AEACEF406755CD2A7CA5DA773C962E4E614B749913D621C26D22D2CB82BB";
    };
    "nix-public/org/scala-sbt/completion_2.12/1.12.11/completion_2.12-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/completion_2.12/1.12.11/completion_2.12-1.12.11.pom";
      sha256 = "FB77AEACEF406755CD2A7CA5DA773C962E4E614B749913D621C26D22D2CB82BB";
    };
    "nix-public/org/scala-sbt/core-macros_2.12/1.12.11/core-macros-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/core-macros_2.12/1.12.11/core-macros_2.12-1.12.11.pom";
      sha256 = "1CAD5E6483436FE3C436CCD2FE306BAB480E8581A6D7E79096092DB0604D56A4";
    };
    "nix-public/org/scala-sbt/core-macros_2.12/1.12.11/core-macros_2.12-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/core-macros_2.12/1.12.11/core-macros_2.12-1.12.11.pom";
      sha256 = "1CAD5E6483436FE3C436CCD2FE306BAB480E8581A6D7E79096092DB0604D56A4";
    };
    "nix-public/org/scala-sbt/io_2.12/1.10.5/io-1.10.5.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/io_2.12/1.10.5/io_2.12-1.10.5.pom";
      sha256 = "5188CA1797EEC2703ABECCDBC0B9CBF13EB9C8D3FBB7F1A6EA1A4DABFB6DC311";
    };
    "nix-public/org/scala-sbt/io_2.12/1.10.5/io_2.12-1.10.5.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/io_2.12/1.10.5/io_2.12-1.10.5.pom";
      sha256 = "5188CA1797EEC2703ABECCDBC0B9CBF13EB9C8D3FBB7F1A6EA1A4DABFB6DC311";
    };
    "nix-public/org/scala-sbt/ipcsocket/ipcsocket/1.6.3/ipcsocket-1.6.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/ipcsocket/ipcsocket/1.6.3/ipcsocket-1.6.3.pom";
      sha256 = "6E31DDD0D7485EE5CA6B48BF7BAE3C252C1973637EC245E23820BBCACC9CDBBC";
    };
    "nix-public/org/scala-sbt/ivy/ivy/2.3.0-sbt-77cc781d727b367d3761f097d89f5a4762771d41/ivy-2.3.0-sbt-77cc781d727b367d3761f097d89f5a4762771d41.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/ivy/ivy/2.3.0-sbt-77cc781d727b367d3761f097d89f5a4762771d41/ivy-2.3.0-sbt-77cc781d727b367d3761f097d89f5a4762771d41.pom";
      sha256 = "4B6EF7E5A45C03140566CE4F1CF106CAB82646F28C149588C35DE11A8BFCEE10";
    };
    "nix-public/org/scala-sbt/jline/jline/2.14.7-sbt-9a88bc413e2b34a4580c001c654d1a7f4f65bf18/jline-2.14.7-sbt-9a88bc413e2b34a4580c001c654d1a7f4f65bf18.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/jline/jline/2.14.7-sbt-9a88bc413e2b34a4580c001c654d1a7f4f65bf18/jline-2.14.7-sbt-9a88bc413e2b34a4580c001c654d1a7f4f65bf18.pom";
      sha256 = "7E279B887B4D30D1A8D4DB657DF6A86EAD4F8F4EE6B2FFDD00B417EAF809F325";
    };
    "nix-public/org/scala-sbt/launcher-interface/1.4.4/launcher-interface-1.4.4.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/launcher-interface/1.4.4/launcher-interface-1.4.4.pom";
      sha256 = "E259F51112945677C3712CC701018F6F664630A493197C7D2D7B5C3B2091A2D4";
    };
    "nix-public/org/scala-sbt/launcher-interface/1.5.2/launcher-interface-1.5.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/launcher-interface/1.5.2/launcher-interface-1.5.2.pom";
      sha256 = "F856EBA6496725ABF43584F0423A2F73DDA386471EF5D858F0239D8929397AF3";
    };
    "nix-public/org/scala-sbt/launcher-interface/1.6.1/launcher-interface-1.6.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/launcher-interface/1.6.1/launcher-interface-1.6.1.pom";
      sha256 = "8C7000C28FC5EFAA9D91B9922697C90E89BFFF826E20BD1938C1FC2D535CBDFA";
    };
    "nix-public/org/scala-sbt/librarymanagement-core_2.12/1.12.2/librarymanagement-core-1.12.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/librarymanagement-core_2.12/1.12.2/librarymanagement-core_2.12-1.12.2.pom";
      sha256 = "3F2DD3BBC384AB3EF3144D4ACF1EC9BB8C9C76108C0971066E2C2B5C5E59D678";
    };
    "nix-public/org/scala-sbt/librarymanagement-core_2.12/1.12.2/librarymanagement-core_2.12-1.12.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/librarymanagement-core_2.12/1.12.2/librarymanagement-core_2.12-1.12.2.pom";
      sha256 = "3F2DD3BBC384AB3EF3144D4ACF1EC9BB8C9C76108C0971066E2C2B5C5E59D678";
    };
    "nix-public/org/scala-sbt/librarymanagement-ivy_2.12/1.12.2/librarymanagement-ivy-1.12.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/librarymanagement-ivy_2.12/1.12.2/librarymanagement-ivy_2.12-1.12.2.pom";
      sha256 = "7831AFFD7E141D87AEBE27DABFA09EC168B568DE0017B992F5DE6B43640FD7A6";
    };
    "nix-public/org/scala-sbt/librarymanagement-ivy_2.12/1.12.2/librarymanagement-ivy_2.12-1.12.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/librarymanagement-ivy_2.12/1.12.2/librarymanagement-ivy_2.12-1.12.2.pom";
      sha256 = "7831AFFD7E141D87AEBE27DABFA09EC168B568DE0017B992F5DE6B43640FD7A6";
    };
    "nix-public/org/scala-sbt/logic_2.12/1.12.11/logic-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/logic_2.12/1.12.11/logic_2.12-1.12.11.pom";
      sha256 = "C4693F7CB81B82FD41BB38C01BD06774EECC02FA5CD121623AD5E49E48FD0D41";
    };
    "nix-public/org/scala-sbt/logic_2.12/1.12.11/logic_2.12-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/logic_2.12/1.12.11/logic_2.12-1.12.11.pom";
      sha256 = "C4693F7CB81B82FD41BB38C01BD06774EECC02FA5CD121623AD5E49E48FD0D41";
    };
    "nix-public/org/scala-sbt/main-settings_2.12/1.12.11/main-settings-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/main-settings_2.12/1.12.11/main-settings_2.12-1.12.11.pom";
      sha256 = "6D900A6C5EA78227EA905CB3264D9DDCCFBB7B62B25746ADB6728DCBA1714310";
    };
    "nix-public/org/scala-sbt/main-settings_2.12/1.12.11/main-settings_2.12-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/main-settings_2.12/1.12.11/main-settings_2.12-1.12.11.pom";
      sha256 = "6D900A6C5EA78227EA905CB3264D9DDCCFBB7B62B25746ADB6728DCBA1714310";
    };
    "nix-public/org/scala-sbt/main_2.12/1.12.11/main-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/main_2.12/1.12.11/main_2.12-1.12.11.pom";
      sha256 = "2AAB3A0CB2002A5F4E0747A3D0A3DA5824DC48DCB2353AE37732D38498852DCC";
    };
    "nix-public/org/scala-sbt/main_2.12/1.12.11/main_2.12-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/main_2.12/1.12.11/main_2.12-1.12.11.pom";
      sha256 = "2AAB3A0CB2002A5F4E0747A3D0A3DA5824DC48DCB2353AE37732D38498852DCC";
    };
    "nix-public/org/scala-sbt/protocol_2.12/1.12.11/protocol-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/protocol_2.12/1.12.11/protocol_2.12-1.12.11.pom";
      sha256 = "277FADB4EC0EC7AA8191434555921D9CD48F61DCDDFFE3E8B855D76D9D525216";
    };
    "nix-public/org/scala-sbt/protocol_2.12/1.12.11/protocol_2.12-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/protocol_2.12/1.12.11/protocol_2.12-1.12.11.pom";
      sha256 = "277FADB4EC0EC7AA8191434555921D9CD48F61DCDDFFE3E8B855D76D9D525216";
    };
    "nix-public/org/scala-sbt/run_2.12/1.12.11/run-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/run_2.12/1.12.11/run_2.12-1.12.11.pom";
      sha256 = "E3F59369779376E5040EA7296DB547FD16576FECF70E7A99A4A58420255F070B";
    };
    "nix-public/org/scala-sbt/run_2.12/1.12.11/run_2.12-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/run_2.12/1.12.11/run_2.12-1.12.11.pom";
      sha256 = "E3F59369779376E5040EA7296DB547FD16576FECF70E7A99A4A58420255F070B";
    };
    "nix-public/org/scala-sbt/sbinary_2.12/0.5.1/sbinary-0.5.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/sbinary_2.12/0.5.1/sbinary_2.12-0.5.1.pom";
      sha256 = "A341EB17ADDEFBF08F8F4BC063442079230B930523177B0CD494002D645E2124";
    };
    "nix-public/org/scala-sbt/sbinary_2.12/0.5.1/sbinary_2.12-0.5.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/sbinary_2.12/0.5.1/sbinary_2.12-0.5.1.pom";
      sha256 = "A341EB17ADDEFBF08F8F4BC063442079230B930523177B0CD494002D645E2124";
    };
    "nix-public/org/scala-sbt/sbt/1.12.11/sbt-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.12.11/sbt-1.12.11.pom";
      sha256 = "0625A4B440DAF4C75D716B1857D434940DF8820DD7099B2D8B16521AC6F13092";
    };
    "nix-public/org/scala-sbt/scripted-plugin_2.12/1.12.11/scripted-plugin-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/scripted-plugin_2.12/1.12.11/scripted-plugin_2.12-1.12.11.pom";
      sha256 = "764E0C3CCE3D1761831D56A546E0A71B8F608F8896416FB185685956FBD4B1B9";
    };
    "nix-public/org/scala-sbt/scripted-plugin_2.12/1.12.11/scripted-plugin_2.12-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/scripted-plugin_2.12/1.12.11/scripted-plugin_2.12-1.12.11.pom";
      sha256 = "764E0C3CCE3D1761831D56A546E0A71B8F608F8896416FB185685956FBD4B1B9";
    };
    "nix-public/org/scala-sbt/task-system_2.12/1.12.11/task-system-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/task-system_2.12/1.12.11/task-system_2.12-1.12.11.pom";
      sha256 = "6E2ABB9B7E7DE0CAB082F2C16AD721D4F34ED2AABD7CD85669C6C5A1D6FF819F";
    };
    "nix-public/org/scala-sbt/task-system_2.12/1.12.11/task-system_2.12-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/task-system_2.12/1.12.11/task-system_2.12-1.12.11.pom";
      sha256 = "6E2ABB9B7E7DE0CAB082F2C16AD721D4F34ED2AABD7CD85669C6C5A1D6FF819F";
    };
    "nix-public/org/scala-sbt/tasks_2.12/1.12.11/tasks-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/tasks_2.12/1.12.11/tasks_2.12-1.12.11.pom";
      sha256 = "188EF2C8B4B2EDFAFF9D12E672075C7CD52E03C20652D80E6CF123ED58C29F8C";
    };
    "nix-public/org/scala-sbt/tasks_2.12/1.12.11/tasks_2.12-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/tasks_2.12/1.12.11/tasks_2.12-1.12.11.pom";
      sha256 = "188EF2C8B4B2EDFAFF9D12E672075C7CD52E03C20652D80E6CF123ED58C29F8C";
    };
    "nix-public/org/scala-sbt/template-resolver/0.1/template-resolver-0.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/template-resolver/0.1/template-resolver-0.1.pom";
      sha256 = "038B38F07EE8F73CFDB358B9D53A836E6AA56E0E6B01944DBBD88E153C425D5B";
    };
    "nix-public/org/scala-sbt/test-agent/1.12.11/test-agent-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/test-agent/1.12.11/test-agent-1.12.11.pom";
      sha256 = "2259C091469FF5C15B756D778FFC02638D5A4D5EB24F707A2AFC519AEEBF9666";
    };
    "nix-public/org/scala-sbt/test-interface/1.0/test-interface-1.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.pom";
      sha256 = "61BA06A9D0C226E10F048004FCEBFB300FDD9B077D05ED502E9875324C8B762E";
    };
    "nix-public/org/scala-sbt/testing_2.12/1.12.11/testing-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/testing_2.12/1.12.11/testing_2.12-1.12.11.pom";
      sha256 = "2EF9E943E4684E2EDDB5A4ADDC39538A28CED96BC613109DEAE0579B5037646C";
    };
    "nix-public/org/scala-sbt/testing_2.12/1.12.11/testing_2.12-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/testing_2.12/1.12.11/testing_2.12-1.12.11.pom";
      sha256 = "2EF9E943E4684E2EDDB5A4ADDC39538A28CED96BC613109DEAE0579B5037646C";
    };
    "nix-public/org/scala-sbt/util-cache_2.12/1.12.10/util-cache-1.12.10.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-cache_2.12/1.12.10/util-cache_2.12-1.12.10.pom";
      sha256 = "52639F6A7FA2EA43C56881AF6A1DA0252B7EA654C637E76DC99F946A03BBCA2A";
    };
    "nix-public/org/scala-sbt/util-cache_2.12/1.12.10/util-cache_2.12-1.12.10.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-cache_2.12/1.12.10/util-cache_2.12-1.12.10.pom";
      sha256 = "52639F6A7FA2EA43C56881AF6A1DA0252B7EA654C637E76DC99F946A03BBCA2A";
    };
    "nix-public/org/scala-sbt/util-cache_2.12/1.12.11/util-cache-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-cache_2.12/1.12.11/util-cache_2.12-1.12.11.pom";
      sha256 = "4A513E4546EF25FDF5C3518007DF3261F611EC7F1C80EA2718DD9BCC66F274BD";
    };
    "nix-public/org/scala-sbt/util-cache_2.12/1.12.11/util-cache_2.12-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-cache_2.12/1.12.11/util-cache_2.12-1.12.11.pom";
      sha256 = "4A513E4546EF25FDF5C3518007DF3261F611EC7F1C80EA2718DD9BCC66F274BD";
    };
    "nix-public/org/scala-sbt/util-control_2.12/1.12.11/util-control-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-control_2.12/1.12.11/util-control_2.12-1.12.11.pom";
      sha256 = "500183B5B221F0189304CF562EA4EAC98B325ACCD035C810763C3E7651044DF2";
    };
    "nix-public/org/scala-sbt/util-control_2.12/1.12.11/util-control_2.12-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-control_2.12/1.12.11/util-control_2.12-1.12.11.pom";
      sha256 = "500183B5B221F0189304CF562EA4EAC98B325ACCD035C810763C3E7651044DF2";
    };
    "nix-public/org/scala-sbt/util-interface/1.12.11/util-interface-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.12.11/util-interface-1.12.11.pom";
      sha256 = "1A6D7890872924654A60DA7EDD756AFE06FA597B92FA4F0795E62FF1E42BC55A";
    };
    "nix-public/org/scala-sbt/util-logging_2.12/1.12.11/util-logging-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-logging_2.12/1.12.11/util-logging_2.12-1.12.11.pom";
      sha256 = "C6763187AA6B756C3433A8B5C168C40EFD5CAC92CB372F6FB2FEF7A19ABEACC2";
    };
    "nix-public/org/scala-sbt/util-logging_2.12/1.12.11/util-logging_2.12-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-logging_2.12/1.12.11/util-logging_2.12-1.12.11.pom";
      sha256 = "C6763187AA6B756C3433A8B5C168C40EFD5CAC92CB372F6FB2FEF7A19ABEACC2";
    };
    "nix-public/org/scala-sbt/util-position_2.12/1.12.10/util-position-1.12.10.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-position_2.12/1.12.10/util-position_2.12-1.12.10.pom";
      sha256 = "5F536702CA390CC6A493644E9E58F256D3A38BECECDCB5A4C3222862A46591E9";
    };
    "nix-public/org/scala-sbt/util-position_2.12/1.12.10/util-position_2.12-1.12.10.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-position_2.12/1.12.10/util-position_2.12-1.12.10.pom";
      sha256 = "5F536702CA390CC6A493644E9E58F256D3A38BECECDCB5A4C3222862A46591E9";
    };
    "nix-public/org/scala-sbt/util-position_2.12/1.12.11/util-position-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-position_2.12/1.12.11/util-position_2.12-1.12.11.pom";
      sha256 = "2576E5313D040B6B050883D7FD51A68856737D88E698CD78AEC7A000885F4C5D";
    };
    "nix-public/org/scala-sbt/util-position_2.12/1.12.11/util-position_2.12-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-position_2.12/1.12.11/util-position_2.12-1.12.11.pom";
      sha256 = "2576E5313D040B6B050883D7FD51A68856737D88E698CD78AEC7A000885F4C5D";
    };
    "nix-public/org/scala-sbt/util-relation_2.12/1.12.11/util-relation-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-relation_2.12/1.12.11/util-relation_2.12-1.12.11.pom";
      sha256 = "35B0E6DCC9692CA027E31229CD65ECAB9855368516CC262C959FDE92C9DD859C";
    };
    "nix-public/org/scala-sbt/util-relation_2.12/1.12.11/util-relation_2.12-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-relation_2.12/1.12.11/util-relation_2.12-1.12.11.pom";
      sha256 = "35B0E6DCC9692CA027E31229CD65ECAB9855368516CC262C959FDE92C9DD859C";
    };
    "nix-public/org/scala-sbt/util-tracking_2.12/1.12.11/util-tracking-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-tracking_2.12/1.12.11/util-tracking_2.12-1.12.11.pom";
      sha256 = "3A5DF2A221B240E174132D72EE827E133938221C0AC687396894C69C1783F362";
    };
    "nix-public/org/scala-sbt/util-tracking_2.12/1.12.11/util-tracking_2.12-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-tracking_2.12/1.12.11/util-tracking_2.12-1.12.11.pom";
      sha256 = "3A5DF2A221B240E174132D72EE827E133938221C0AC687396894C69C1783F362";
    };
    "nix-public/org/scala-sbt/zinc-apiinfo_2.12/1.12.0/zinc-apiinfo-1.12.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc-apiinfo_2.12/1.12.0/zinc-apiinfo_2.12-1.12.0.pom";
      sha256 = "549B624ABB883AEDF5582977D8FBD3B83888376B38469C4D9EB885D32BD2B433";
    };
    "nix-public/org/scala-sbt/zinc-apiinfo_2.12/1.12.0/zinc-apiinfo_2.12-1.12.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc-apiinfo_2.12/1.12.0/zinc-apiinfo_2.12-1.12.0.pom";
      sha256 = "549B624ABB883AEDF5582977D8FBD3B83888376B38469C4D9EB885D32BD2B433";
    };
    "nix-public/org/scala-sbt/zinc-classfile_2.12/1.12.0/zinc-classfile-1.12.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc-classfile_2.12/1.12.0/zinc-classfile_2.12-1.12.0.pom";
      sha256 = "BE3EEB4A1BBB6185CE2CAF3103D2B865A27C314C2CC546A457E81EBD8C85CA67";
    };
    "nix-public/org/scala-sbt/zinc-classfile_2.12/1.12.0/zinc-classfile_2.12-1.12.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc-classfile_2.12/1.12.0/zinc-classfile_2.12-1.12.0.pom";
      sha256 = "BE3EEB4A1BBB6185CE2CAF3103D2B865A27C314C2CC546A457E81EBD8C85CA67";
    };
    "nix-public/org/scala-sbt/zinc-classpath_2.12/1.12.0/zinc-classpath-1.12.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc-classpath_2.12/1.12.0/zinc-classpath_2.12-1.12.0.pom";
      sha256 = "0589FF29E53D27EAC647983E86BAD3E25CF550BD085809BEF51A8CFF30734229";
    };
    "nix-public/org/scala-sbt/zinc-classpath_2.12/1.12.0/zinc-classpath_2.12-1.12.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc-classpath_2.12/1.12.0/zinc-classpath_2.12-1.12.0.pom";
      sha256 = "0589FF29E53D27EAC647983E86BAD3E25CF550BD085809BEF51A8CFF30734229";
    };
    "nix-public/org/scala-sbt/zinc-compile-core_2.12/1.12.0/zinc-compile-core-1.12.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc-compile-core_2.12/1.12.0/zinc-compile-core_2.12-1.12.0.pom";
      sha256 = "8D8B162C91B44779DC89759BFF6CC531582C004DC6809078344D833FDA235BD4";
    };
    "nix-public/org/scala-sbt/zinc-compile-core_2.12/1.12.0/zinc-compile-core_2.12-1.12.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc-compile-core_2.12/1.12.0/zinc-compile-core_2.12-1.12.0.pom";
      sha256 = "8D8B162C91B44779DC89759BFF6CC531582C004DC6809078344D833FDA235BD4";
    };
    "nix-public/org/scala-sbt/zinc-compile_2.12/1.12.0/zinc-compile-1.12.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc-compile_2.12/1.12.0/zinc-compile_2.12-1.12.0.pom";
      sha256 = "1B9FE6FDC9EC635638F8D470FB733C4C422A39ED7C8947228908DB15619C9B4D";
    };
    "nix-public/org/scala-sbt/zinc-compile_2.12/1.12.0/zinc-compile_2.12-1.12.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc-compile_2.12/1.12.0/zinc-compile_2.12-1.12.0.pom";
      sha256 = "1B9FE6FDC9EC635638F8D470FB733C4C422A39ED7C8947228908DB15619C9B4D";
    };
    "nix-public/org/scala-sbt/zinc-core_2.12/1.12.0/zinc-core-1.12.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc-core_2.12/1.12.0/zinc-core_2.12-1.12.0.pom";
      sha256 = "2FD984FFF44B2BF4BEF1E76C35500B1DD45A017751EE04BDEF3B5F7A8D0CEA80";
    };
    "nix-public/org/scala-sbt/zinc-core_2.12/1.12.0/zinc-core_2.12-1.12.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc-core_2.12/1.12.0/zinc-core_2.12-1.12.0.pom";
      sha256 = "2FD984FFF44B2BF4BEF1E76C35500B1DD45A017751EE04BDEF3B5F7A8D0CEA80";
    };
    "nix-public/org/scala-sbt/zinc-lm-integration_2.12/1.12.11/zinc-lm-integration-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc-lm-integration_2.12/1.12.11/zinc-lm-integration_2.12-1.12.11.pom";
      sha256 = "78682975E3C9FA642EEFB106A2568E7A048D36734C9B026D8AA5FFA5F4A2406B";
    };
    "nix-public/org/scala-sbt/zinc-lm-integration_2.12/1.12.11/zinc-lm-integration_2.12-1.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc-lm-integration_2.12/1.12.11/zinc-lm-integration_2.12-1.12.11.pom";
      sha256 = "78682975E3C9FA642EEFB106A2568E7A048D36734C9B026D8AA5FFA5F4A2406B";
    };
    "nix-public/org/scala-sbt/zinc-persist-core-assembly/1.12.0/zinc-persist-core-assembly-1.12.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc-persist-core-assembly/1.12.0/zinc-persist-core-assembly-1.12.0.pom";
      sha256 = "AB88F77A6895D673209376AAF98700448C50B338E647998D49B8490FDD0337B5";
    };
    "nix-public/org/scala-sbt/zinc-persist_2.12/1.12.0/zinc-persist-1.12.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc-persist_2.12/1.12.0/zinc-persist_2.12-1.12.0.pom";
      sha256 = "9AFB4C6A4F55C7A7EE83CBEC044655EB43460EBD0CA8AC03285F251FED7120D3";
    };
    "nix-public/org/scala-sbt/zinc-persist_2.12/1.12.0/zinc-persist_2.12-1.12.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc-persist_2.12/1.12.0/zinc-persist_2.12-1.12.0.pom";
      sha256 = "9AFB4C6A4F55C7A7EE83CBEC044655EB43460EBD0CA8AC03285F251FED7120D3";
    };
    "nix-public/org/scala-sbt/zinc_2.12/1.12.0/zinc-1.12.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc_2.12/1.12.0/zinc_2.12-1.12.0.pom";
      sha256 = "56A5E74B7F195AE0066D2382E988BDCD7BC50922AEC36C26034CB4582DA28AFB";
    };
    "nix-public/org/scala-sbt/zinc_2.12/1.12.0/zinc_2.12-1.12.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc_2.12/1.12.0/zinc_2.12-1.12.0.pom";
      sha256 = "56A5E74B7F195AE0066D2382E988BDCD7BC50922AEC36C26034CB4582DA28AFB";
    };
    "nix-public/org/scalameta/sbt-scalafmt_2.12_1.0/2.6.1/sbt-scalafmt-2.6.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalameta/sbt-scalafmt_2.12_1.0/2.6.1/sbt-scalafmt_2.12_1.0-2.6.1-sources.jar";
      sha256 = "25CE82134257D46CB0A1C7694C4A5BB3BB1E4D43AD4942FACC2AA7A9897F28A7";
    };
    "nix-public/org/scalameta/sbt-scalafmt_2.12_1.0/2.6.1/sbt-scalafmt-2.6.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalameta/sbt-scalafmt_2.12_1.0/2.6.1/sbt-scalafmt_2.12_1.0-2.6.1.jar";
      sha256 = "EA72DCF7C0C8AA317676F72452529B5FD4A9FBCFEF28A6EEAD83B9F1C95269CF";
    };
    "nix-public/org/scalameta/sbt-scalafmt_2.12_1.0/2.6.1/sbt-scalafmt-2.6.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalameta/sbt-scalafmt_2.12_1.0/2.6.1/sbt-scalafmt_2.12_1.0-2.6.1.pom";
      sha256 = "9B0C218C02B48E4165751C131C409538A3EDBF7EEF8D8F84F85C41BF2A81DF68";
    };
    "nix-public/org/scalameta/sbt-scalafmt_2.12_1.0/2.6.1/sbt-scalafmt_2.12_1.0-2.6.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalameta/sbt-scalafmt_2.12_1.0/2.6.1/sbt-scalafmt_2.12_1.0-2.6.1-sources.jar";
      sha256 = "25CE82134257D46CB0A1C7694C4A5BB3BB1E4D43AD4942FACC2AA7A9897F28A7";
    };
    "nix-public/org/scalameta/sbt-scalafmt_2.12_1.0/2.6.1/sbt-scalafmt_2.12_1.0-2.6.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalameta/sbt-scalafmt_2.12_1.0/2.6.1/sbt-scalafmt_2.12_1.0-2.6.1.jar";
      sha256 = "EA72DCF7C0C8AA317676F72452529B5FD4A9FBCFEF28A6EEAD83B9F1C95269CF";
    };
    "nix-public/org/scalameta/sbt-scalafmt_2.12_1.0/2.6.1/sbt-scalafmt_2.12_1.0-2.6.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalameta/sbt-scalafmt_2.12_1.0/2.6.1/sbt-scalafmt_2.12_1.0-2.6.1.pom";
      sha256 = "9B0C218C02B48E4165751C131C409538A3EDBF7EEF8D8F84F85C41BF2A81DF68";
    };
    "nix-public/org/scalameta/scalafmt-dynamic-core_2.12/3.11.1/scalafmt-dynamic-core-3.11.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalameta/scalafmt-dynamic-core_2.12/3.11.1/scalafmt-dynamic-core_2.12-3.11.1-sources.jar";
      sha256 = "E8B661DA3DC58E87A6D20F70AAE807FE2136D479F01EFB4152746789912AE9FB";
    };
    "nix-public/org/scalameta/scalafmt-dynamic-core_2.12/3.11.1/scalafmt-dynamic-core-3.11.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalameta/scalafmt-dynamic-core_2.12/3.11.1/scalafmt-dynamic-core_2.12-3.11.1.jar";
      sha256 = "8954A9FF96C64095D466DF8340B37B3525E98AD852F738141E2D9E0287203B96";
    };
    "nix-public/org/scalameta/scalafmt-dynamic-core_2.12/3.11.1/scalafmt-dynamic-core-3.11.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalameta/scalafmt-dynamic-core_2.12/3.11.1/scalafmt-dynamic-core_2.12-3.11.1.pom";
      sha256 = "4931D3168AA8E79C9598C66658232E9617EDD955F4E3570CB28AC7E19EAAB20D";
    };
    "nix-public/org/scalameta/scalafmt-dynamic-core_2.12/3.11.1/scalafmt-dynamic-core_2.12-3.11.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalameta/scalafmt-dynamic-core_2.12/3.11.1/scalafmt-dynamic-core_2.12-3.11.1-sources.jar";
      sha256 = "E8B661DA3DC58E87A6D20F70AAE807FE2136D479F01EFB4152746789912AE9FB";
    };
    "nix-public/org/scalameta/scalafmt-dynamic-core_2.12/3.11.1/scalafmt-dynamic-core_2.12-3.11.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalameta/scalafmt-dynamic-core_2.12/3.11.1/scalafmt-dynamic-core_2.12-3.11.1.jar";
      sha256 = "8954A9FF96C64095D466DF8340B37B3525E98AD852F738141E2D9E0287203B96";
    };
    "nix-public/org/scalameta/scalafmt-dynamic-core_2.12/3.11.1/scalafmt-dynamic-core_2.12-3.11.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalameta/scalafmt-dynamic-core_2.12/3.11.1/scalafmt-dynamic-core_2.12-3.11.1.pom";
      sha256 = "4931D3168AA8E79C9598C66658232E9617EDD955F4E3570CB28AC7E19EAAB20D";
    };
    "nix-public/org/scalameta/scalafmt-interfaces/3.11.1/scalafmt-interfaces-3.11.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalameta/scalafmt-interfaces/3.11.1/scalafmt-interfaces-3.11.1-sources.jar";
      sha256 = "A84BA245F10FB479EB1D0CADDBEE2E6DA6066C27D6838113E3A08C8C6C4AF449";
    };
    "nix-public/org/scalameta/scalafmt-interfaces/3.11.1/scalafmt-interfaces-3.11.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalameta/scalafmt-interfaces/3.11.1/scalafmt-interfaces-3.11.1.jar";
      sha256 = "EC8AC6769C5960E8EE04D4FEE15A4B82BA6032B3DF3F4D725221EF94DD1DAD90";
    };
    "nix-public/org/scalameta/scalafmt-interfaces/3.11.1/scalafmt-interfaces-3.11.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalameta/scalafmt-interfaces/3.11.1/scalafmt-interfaces-3.11.1.pom";
      sha256 = "16CB056965B8537BB7D4DCBFDC44E35259C0D49BE0C33298F174FF011D915814";
    };
    "nix-public/org/scalameta/scalafmt-sysops_2.12/3.11.1/scalafmt-sysops-3.11.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalameta/scalafmt-sysops_2.12/3.11.1/scalafmt-sysops_2.12-3.11.1-sources.jar";
      sha256 = "98F6D41950F52BBA6486888114832DFC314D18F295B58E7D093E203C9FD480E7";
    };
    "nix-public/org/scalameta/scalafmt-sysops_2.12/3.11.1/scalafmt-sysops-3.11.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalameta/scalafmt-sysops_2.12/3.11.1/scalafmt-sysops_2.12-3.11.1.jar";
      sha256 = "AED868569BA43ACF45272A61B4E4E7D9ADA24C04579A88F67D9E7176C4A2944D";
    };
    "nix-public/org/scalameta/scalafmt-sysops_2.12/3.11.1/scalafmt-sysops-3.11.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalameta/scalafmt-sysops_2.12/3.11.1/scalafmt-sysops_2.12-3.11.1.pom";
      sha256 = "DA4148C6021FA08FD58750F8F12705F3C2F759A0767C73468F1C913CC105EF6B";
    };
    "nix-public/org/scalameta/scalafmt-sysops_2.12/3.11.1/scalafmt-sysops_2.12-3.11.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalameta/scalafmt-sysops_2.12/3.11.1/scalafmt-sysops_2.12-3.11.1-sources.jar";
      sha256 = "98F6D41950F52BBA6486888114832DFC314D18F295B58E7D093E203C9FD480E7";
    };
    "nix-public/org/scalameta/scalafmt-sysops_2.12/3.11.1/scalafmt-sysops_2.12-3.11.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalameta/scalafmt-sysops_2.12/3.11.1/scalafmt-sysops_2.12-3.11.1.jar";
      sha256 = "AED868569BA43ACF45272A61B4E4E7D9ADA24C04579A88F67D9E7176C4A2944D";
    };
    "nix-public/org/scalameta/scalafmt-sysops_2.12/3.11.1/scalafmt-sysops_2.12-3.11.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalameta/scalafmt-sysops_2.12/3.11.1/scalafmt-sysops_2.12-3.11.1.pom";
      sha256 = "DA4148C6021FA08FD58750F8F12705F3C2F759A0767C73468F1C913CC105EF6B";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-sources.jar";
      sha256 = "C4BC93180A4F0ACEEC3B057A2514ABE04A79F06C174BBED910A2AFB227B79366";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-tests.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-tests.jar";
      sha256 = "FB82F52621D9DDAFB135DFF968A75B5BC08C40BA4BE77B5AB8DEA8711A032D72";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar";
      sha256 = "18C4A0095D5C1DA6B817592E767BB23D29DD2F560AD74DF75FF3961DBDE25B79";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.pom";
      sha256 = "7CD9D7A0B5D93DFD461A148891B43509CF403A9C7F9FB49060D3554DF1C81E1E";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.pom";
      sha256 = "FB046A9C229437928BB11C2D27C8B5D773EB8A25E60CBD253D985210DEDC2684";
    };
    "nix-public/org/slf4j/slf4j-api/2.0.16/slf4j-api-2.0.16.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/2.0.16/slf4j-api-2.0.16.pom";
      sha256 = "B1A00F5B1C4DBE62B805D65D23911A6F77063889D7CB1E86FE8389D6190473F7";
    };
    "nix-public/org/slf4j/slf4j-api/2.0.7/slf4j-api-2.0.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/2.0.7/slf4j-api-2.0.7.pom";
      sha256 = "2D403CCF0E0A02D5C1A8667B0E2A33C8DFC6038AB287B9671DD681C205267981";
    };
    "nix-public/org/slf4j/slf4j-bom/2.0.16/slf4j-bom-2.0.16.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-bom/2.0.16/slf4j-bom-2.0.16.pom";
      sha256 = "0566048EC825CDF28758620AF64D9E14AE38A9CD8748DD6FAFA6DF4A4194C279";
    };
    "nix-public/org/slf4j/slf4j-parent/1.7.25/slf4j-parent-1.7.25.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.7.25/slf4j-parent-1.7.25.pom";
      sha256 = "18F5C52120DB036E88D6136F8839C832D074BDDA95C756C6F429249D2DB54AC6";
    };
    "nix-public/org/slf4j/slf4j-parent/1.7.36/slf4j-parent-1.7.36.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.7.36/slf4j-parent-1.7.36.pom";
      sha256 = "BB388D37FBCDD3CDE64C3CEDE21838693218DC451F04040C5DF360A78ED7E812";
    };
    "nix-public/org/slf4j/slf4j-parent/2.0.16/slf4j-parent-2.0.16.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/2.0.16/slf4j-parent-2.0.16.pom";
      sha256 = "09A0B4CC814D7274616C9B16D4C0FD9AAF1ECC813334DE5131E547271B1982E5";
    };
    "nix-public/org/slf4j/slf4j-parent/2.0.7/slf4j-parent-2.0.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/2.0.7/slf4j-parent-2.0.7.pom";
      sha256 = "C182BB36CD3AF1C93C1603CDFEFE7889157DB30BA8B584F4A44535FCD22E45E7";
    };
    "nix-public/org/sonatype/oss/oss-parent/7/oss-parent-7.pom" = {
      url = "https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/7/oss-parent-7.pom";
      sha256 = "B51F8867C92B6A722499557FC3A1FDEA77BDF9EF574722FE90CE436A29559454";
    };
    "nix-public/org/sonatype/oss/oss-parent/9/oss-parent-9.pom" = {
      url = "https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom";
      sha256 = "FB40265F982548212FF82E362E59732B2187EC6F0D80182885C14EF1F982827A";
    };
    "nix-public/org/springframework/spring-framework-bom/5.3.39/spring-framework-bom-5.3.39.pom" = {
      url = "https://repo1.maven.org/maven2/org/springframework/spring-framework-bom/5.3.39/spring-framework-bom-5.3.39.pom";
      sha256 = "F6D481093E75767CBA1AC7E1DB38F8F692CBE3E38744693371A75AEB21C6148B";
    };
  };
}