# This file was automatically generated by Sbtix. Do not edit manually.
{
  "versioning" = [{
      "scalaVersion" = "2.12.20";
      "sbtVersion" = "1.10.7";
    }];
  "repos" = {
    "nix-public" = "";
  };

  "artifacts" = {
    "nix-public/com/github/luben/zstd-jni/1.5.6-3/zstd-jni-1.5.6-3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/luben/zstd-jni/1.5.6-3/zstd-jni-1.5.6-3-javadoc.jar";
      sha256 = "74BB7880A397BD1F0B89F9640FB24317F312AE0A4D5641A842D9332D04363603";
    };
    "nix-public/com/github/luben/zstd-jni/1.5.6-3/zstd-jni-1.5.6-3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/luben/zstd-jni/1.5.6-3/zstd-jni-1.5.6-3-sources.jar";
      sha256 = "7136C42F56D17C8B2C7BE16FE7744C2C36B85C0C274750EFE5050E283D9BD31F";
    };
    "nix-public/com/github/luben/zstd-jni/1.5.6-3/zstd-jni-1.5.6-3.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/luben/zstd-jni/1.5.6-3/zstd-jni-1.5.6-3.jar";
      sha256 = "F72EDE1B39258FAF81277DC58DE30C71CBAE4253732558D2CE10B53D8B5763D5";
    };
    "nix-public/com/github/luben/zstd-jni/1.5.6-3/zstd-jni-1.5.6-3.pom" = {
      url = "https://repo1.maven.org/maven2/com/github/luben/zstd-jni/1.5.6-3/zstd-jni-1.5.6-3.pom";
      sha256 = "DFD2FA7B1D23939216902F844FA5E86A79CDFB9209760E4C04242B5A58D49490";
    };
    "nix-public/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5.2/jsoniter-scala-core_2.12-2.13.5.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5.2/jsoniter-scala-core_2.12-2.13.5.2-javadoc.jar";
      sha256 = "78DB77E7096ACE2D9EB0493F133E758467BE07E39A24E9FC8F3B7FA2AD3CA7EA";
    };
    "nix-public/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5.2/jsoniter-scala-core_2.12-2.13.5.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5.2/jsoniter-scala-core_2.12-2.13.5.2-sources.jar";
      sha256 = "E99CB5EAC8FCE727E68AD7EBEBBF2FB247AF6EBF8FB7B0D530943FEA06776E35";
    };
    "nix-public/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5.2/jsoniter-scala-core_2.12-2.13.5.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5.2/jsoniter-scala-core_2.12-2.13.5.2.jar";
      sha256 = "8E2737C4B3D3B80FA4F2024F16351CC1018997249B8345AC8A98826BA158EEB3";
    };
    "nix-public/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5.2/jsoniter-scala-core_2.12-2.13.5.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5.2/jsoniter-scala-core_2.12-2.13.5.2.pom";
      sha256 = "7CB5513032999F0A2A8061AD2A5C0F3C1DD341272D0A8ACC4696C700A82F5F21";
    };
    "nix-public/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5/jsoniter-scala-core_2.12-2.13.5-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5/jsoniter-scala-core_2.12-2.13.5-javadoc.jar";
      sha256 = "78DB77E7096ACE2D9EB0493F133E758467BE07E39A24E9FC8F3B7FA2AD3CA7EA";
    };
    "nix-public/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5/jsoniter-scala-core_2.12-2.13.5-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5/jsoniter-scala-core_2.12-2.13.5-sources.jar";
      sha256 = "648ABEC87AA92B16D65565C02B59A63D34469F81977164AEB60498D7048C43C2";
    };
    "nix-public/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5/jsoniter-scala-core_2.12-2.13.5.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5/jsoniter-scala-core_2.12-2.13.5.jar";
      sha256 = "6B7A8149F1D8EB379B236CE0A593F8EEDCCA341BF1D2E1A42FF2AD5D445AA4A3";
    };
    "nix-public/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5/jsoniter-scala-core_2.12-2.13.5.pom" = {
      url = "https://repo1.maven.org/maven2/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.13.5/jsoniter-scala-core_2.12-2.13.5.pom";
      sha256 = "237F6A260F8B26591DF661679BD5FFA0CCC2634F8F78A5170FBB1BF523AB8E2D";
    };
    "nix-public/com/lihaoyi/geny_2.12/1.0.0/geny_2.12-1.0.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/geny_2.12/1.0.0/geny_2.12-1.0.0-javadoc.jar";
      sha256 = "2C3B203A1CDD68A1085F6D9F25B6CFF1C304784EC0079BB4C96688CA8D107ED7";
    };
    "nix-public/com/lihaoyi/geny_2.12/1.0.0/geny_2.12-1.0.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/geny_2.12/1.0.0/geny_2.12-1.0.0-sources.jar";
      sha256 = "F15E65E28FB23B09D94382DEF51DBB4C08864B756232F5DAAF6A6A7135FE3339";
    };
    "nix-public/com/lihaoyi/geny_2.12/1.0.0/geny_2.12-1.0.0.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/geny_2.12/1.0.0/geny_2.12-1.0.0.jar";
      sha256 = "D68722581D58F1F9F361B0E35988C404DDACA26630D12E6A7377E94FA264AF2E";
    };
    "nix-public/com/lihaoyi/geny_2.12/1.0.0/geny_2.12-1.0.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/geny_2.12/1.0.0/geny_2.12-1.0.0.pom";
      sha256 = "D4D7895A71FE65AF03DE98BD5CA2880DA4EB2B01237F95EEEF681BE65EA6F86F";
    };
    "nix-public/com/lihaoyi/ujson_2.12/3.1.3/ujson_2.12-3.1.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/ujson_2.12/3.1.3/ujson_2.12-3.1.3-javadoc.jar";
      sha256 = "C1A6520B0EC7EA6F4D66BEDE7784A612A974AAE5AAF353D4BAC9DCB591504417";
    };
    "nix-public/com/lihaoyi/ujson_2.12/3.1.3/ujson_2.12-3.1.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/ujson_2.12/3.1.3/ujson_2.12-3.1.3-sources.jar";
      sha256 = "E8A8FAABA43A0A129B53EB69C4FA58EF31143C445A96BCB9E18AF0491F8F0AE9";
    };
    "nix-public/com/lihaoyi/ujson_2.12/3.1.3/ujson_2.12-3.1.3.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/ujson_2.12/3.1.3/ujson_2.12-3.1.3.jar";
      sha256 = "0D954D17FF2A62351DFCC943EFD8738D2ACBFBCF88173E4FDD249804B97DDDD3";
    };
    "nix-public/com/lihaoyi/ujson_2.12/3.1.3/ujson_2.12-3.1.3.pom" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/ujson_2.12/3.1.3/ujson_2.12-3.1.3.pom";
      sha256 = "890C5488DD8A743D070F8195D082075129FD2E561F30CD17BD0DC27F4963EEE4";
    };
    "nix-public/com/lihaoyi/upack_2.12/3.1.3/upack_2.12-3.1.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upack_2.12/3.1.3/upack_2.12-3.1.3-javadoc.jar";
      sha256 = "749C1DBA896CEA00F4EA107578D40D98420C22FA8E97183ECEF6D100A0BFCB1F";
    };
    "nix-public/com/lihaoyi/upack_2.12/3.1.3/upack_2.12-3.1.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upack_2.12/3.1.3/upack_2.12-3.1.3-sources.jar";
      sha256 = "2E861FDB3CF436D93ECFE0D03ADC9859821E4780A128B38D5EBCDF4855755445";
    };
    "nix-public/com/lihaoyi/upack_2.12/3.1.3/upack_2.12-3.1.3.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upack_2.12/3.1.3/upack_2.12-3.1.3.jar";
      sha256 = "88B6892113C87F00589D1B95A00AD533F2EDD669C5BFCA120BEF9A0C35BC56FC";
    };
    "nix-public/com/lihaoyi/upack_2.12/3.1.3/upack_2.12-3.1.3.pom" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upack_2.12/3.1.3/upack_2.12-3.1.3.pom";
      sha256 = "AD0A571ED25A5F5E4378C7A552C988D74911AAB7B5DD2E3B910F51A5324FBA2E";
    };
    "nix-public/com/lihaoyi/upickle-core_2.12/3.1.3/upickle-core_2.12-3.1.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle-core_2.12/3.1.3/upickle-core_2.12-3.1.3-javadoc.jar";
      sha256 = "F6EB52A4AF2CD88812B19A3CF9A2FFEE0265F855086D6587AB8914402CABACA4";
    };
    "nix-public/com/lihaoyi/upickle-core_2.12/3.1.3/upickle-core_2.12-3.1.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle-core_2.12/3.1.3/upickle-core_2.12-3.1.3-sources.jar";
      sha256 = "96E138206926A4E72AAB8A62BF4865C5146679C6686B851835AE2B3905D8103B";
    };
    "nix-public/com/lihaoyi/upickle-core_2.12/3.1.3/upickle-core_2.12-3.1.3.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle-core_2.12/3.1.3/upickle-core_2.12-3.1.3.jar";
      sha256 = "E709BF30895070D63B55ACC3F839067C9F5D610EFF9E6CF1F4C77F630BC817C3";
    };
    "nix-public/com/lihaoyi/upickle-core_2.12/3.1.3/upickle-core_2.12-3.1.3.pom" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle-core_2.12/3.1.3/upickle-core_2.12-3.1.3.pom";
      sha256 = "289C99C23A09F38ACBE4B679297DE73E65A2A0787955C0103F68C4F609A6533C";
    };
    "nix-public/com/lihaoyi/upickle-implicits_2.12/3.1.3/upickle-implicits_2.12-3.1.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle-implicits_2.12/3.1.3/upickle-implicits_2.12-3.1.3-javadoc.jar";
      sha256 = "FD7E2B8601C399386D542168204C272FF29FCDB738204AFBFA90D0A5EC675E50";
    };
    "nix-public/com/lihaoyi/upickle-implicits_2.12/3.1.3/upickle-implicits_2.12-3.1.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle-implicits_2.12/3.1.3/upickle-implicits_2.12-3.1.3-sources.jar";
      sha256 = "C2F6A4151C2DB87235C5262AC1138CF212CF709B7B327CD0AFEEDF058C8CFFB6";
    };
    "nix-public/com/lihaoyi/upickle-implicits_2.12/3.1.3/upickle-implicits_2.12-3.1.3.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle-implicits_2.12/3.1.3/upickle-implicits_2.12-3.1.3.jar";
      sha256 = "C7F5D25846376BEE5FB6A3A2CA7E14E41B80F7FB6C7CE2C367D29DF21F827010";
    };
    "nix-public/com/lihaoyi/upickle-implicits_2.12/3.1.3/upickle-implicits_2.12-3.1.3.pom" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle-implicits_2.12/3.1.3/upickle-implicits_2.12-3.1.3.pom";
      sha256 = "D21C033750CEEB8D7F1DCFC823E0637EA32F289D54C43FB0A494EC3619CDD107";
    };
    "nix-public/com/lihaoyi/upickle_2.12/3.1.3/upickle_2.12-3.1.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle_2.12/3.1.3/upickle_2.12-3.1.3-javadoc.jar";
      sha256 = "27EB2B40A3CAFA19CF47B5AB11B48B45E8A81E6AE20793AFFE7B4910C4E43ECA";
    };
    "nix-public/com/lihaoyi/upickle_2.12/3.1.3/upickle_2.12-3.1.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle_2.12/3.1.3/upickle_2.12-3.1.3-sources.jar";
      sha256 = "04F33F4A4F05F72FAF8B065353783DEFFCC8D34D6D589F2B868BCE89A282D588";
    };
    "nix-public/com/lihaoyi/upickle_2.12/3.1.3/upickle_2.12-3.1.3.jar" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle_2.12/3.1.3/upickle_2.12-3.1.3.jar";
      sha256 = "CE0BF0E162F7EA7F8638856302524EB0A0C659F5FEE7554AE7A57BF9C458D77A";
    };
    "nix-public/com/lihaoyi/upickle_2.12/3.1.3/upickle_2.12-3.1.3.pom" = {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle_2.12/3.1.3/upickle_2.12-3.1.3.pom";
      sha256 = "5D97F0C586D5E862E60F7466B82FAB5129F834696CD2A53372BAD9734772CEAA";
    };
    "nix-public/commons-codec/commons-codec/1.17.0/commons-codec-1.17.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.17.0/commons-codec-1.17.0-javadoc.jar";
      sha256 = "523649F0FD42D565BA7FF8B8BAB112EC84269FEE4EDBE9647543290064D947C5";
    };
    "nix-public/commons-codec/commons-codec/1.17.0/commons-codec-1.17.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.17.0/commons-codec-1.17.0-sources.jar";
      sha256 = "9869277D653510F670039B77945BEFE71C1CA34EF2E281855BD86E6605AAB4A6";
    };
    "nix-public/commons-codec/commons-codec/1.17.0/commons-codec-1.17.0-tests.jar" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.17.0/commons-codec-1.17.0-tests.jar";
      sha256 = "949297112C37C82D3E3C0A54B28F0212DF35819D48AD042299253D924884FCF2";
    };
    "nix-public/commons-codec/commons-codec/1.17.0/commons-codec-1.17.0.jar" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.17.0/commons-codec-1.17.0.jar";
      sha256 = "F700DE80AC270D0344FDEA7468201D8B9C805E5C648331C3619F2EE067CCFC59";
    };
    "nix-public/commons-codec/commons-codec/1.17.0/commons-codec-1.17.0.pom" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.17.0/commons-codec-1.17.0.pom";
      sha256 = "C01C4CDA5E408F41ED1D83E4A0A170CF53801B6338ABA49F0F904786BC1214FC";
    };
    "nix-public/commons-io/commons-io/2.16.1/commons-io-2.16.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/commons-io/commons-io/2.16.1/commons-io-2.16.1-javadoc.jar";
      sha256 = "5FC868EF3981BA0AE27A3F8259FC6D80E1FEEF899B09E9BC40FAE70EA91BFD4E";
    };
    "nix-public/commons-io/commons-io/2.16.1/commons-io-2.16.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/commons-io/commons-io/2.16.1/commons-io-2.16.1-sources.jar";
      sha256 = "FCFE84E39FB44E38A0EA0AB0815B53ADEA6FFF89C7B72535BC42495F400CB9A1";
    };
    "nix-public/commons-io/commons-io/2.16.1/commons-io-2.16.1-tests.jar" = {
      url = "https://repo1.maven.org/maven2/commons-io/commons-io/2.16.1/commons-io-2.16.1-tests.jar";
      sha256 = "12B99F1989D29DBBC3638FF9EEE855963F6B04262D4150C0FE49981FDBB37E14";
    };
    "nix-public/commons-io/commons-io/2.16.1/commons-io-2.16.1.jar" = {
      url = "https://repo1.maven.org/maven2/commons-io/commons-io/2.16.1/commons-io-2.16.1.jar";
      sha256 = "F41F7BAACD716896447ACE9758621F62C1C6B0A91D89ACEE488DA26FC477C84F";
    };
    "nix-public/commons-io/commons-io/2.16.1/commons-io-2.16.1.pom" = {
      url = "https://repo1.maven.org/maven2/commons-io/commons-io/2.16.1/commons-io-2.16.1.pom";
      sha256 = "5777D292251C7895C04A4C57015683EC3B353A12486C9B3E7178E9B0B3C38FFF";
    };
    "nix-public/io/airlift/airbase/112/airbase-112.pom" = {
      url = "https://repo1.maven.org/maven2/io/airlift/airbase/112/airbase-112.pom";
      sha256 = "18CCD104CBD97EB44BD57B68C047AB7FF81FBC800987F82D815C68AC4C2304CE";
    };
    "nix-public/io/airlift/aircompressor/0.27/aircompressor-0.27-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/io/airlift/aircompressor/0.27/aircompressor-0.27-javadoc.jar";
      sha256 = "6FFA215C7BC57898C7A3EEB4EFFF1688A2741FB25E6BBFFB44E80E97FAAB96B3";
    };
    "nix-public/io/airlift/aircompressor/0.27/aircompressor-0.27-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/airlift/aircompressor/0.27/aircompressor-0.27-sources.jar";
      sha256 = "7F5952D138E9CFF1445A961B90228680B5714145038648E02E4433490E5F078D";
    };
    "nix-public/io/airlift/aircompressor/0.27/aircompressor-0.27-tests.jar" = {
      url = "https://repo1.maven.org/maven2/io/airlift/aircompressor/0.27/aircompressor-0.27-tests.jar";
      sha256 = "4E252565719C07327EB2C5AB38D2BF2FC7A2A24CA880566154DC250A866C5763";
    };
    "nix-public/io/airlift/aircompressor/0.27/aircompressor-0.27.jar" = {
      url = "https://repo1.maven.org/maven2/io/airlift/aircompressor/0.27/aircompressor-0.27.jar";
      sha256 = "FDBEF3137A28F63BB0CB93487803080EDE746A4EC3D421E36C6F0C305C35E5E4";
    };
    "nix-public/io/airlift/aircompressor/0.27/aircompressor-0.27.pom" = {
      url = "https://repo1.maven.org/maven2/io/airlift/aircompressor/0.27/aircompressor-0.27.pom";
      sha256 = "5AACDA89BE38563BDF3BFAC79333616C0802CA617070DEA66BA649507C994441";
    };
    "nix-public/io/get-coursier/cache-util/2.1.24/cache-util-2.1.24-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/cache-util/2.1.24/cache-util-2.1.24-javadoc.jar";
      sha256 = "66BA0245A767362045298C12DB13B60506015781732EE2F7852EC2AB57CA9A04";
    };
    "nix-public/io/get-coursier/cache-util/2.1.24/cache-util-2.1.24-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/cache-util/2.1.24/cache-util-2.1.24-sources.jar";
      sha256 = "46F152A3ECD09199A541E5E9A6A67DBD3080DC20E69CE7CE11BFA5AC477EFCAE";
    };
    "nix-public/io/get-coursier/cache-util/2.1.24/cache-util-2.1.24.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/cache-util/2.1.24/cache-util-2.1.24.jar";
      sha256 = "447741AFB13B90E7F650ED89F230BF0E9D76874F80EF516E2AA3963BA56EDF84";
    };
    "nix-public/io/get-coursier/cache-util/2.1.24/cache-util-2.1.24.pom" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/cache-util/2.1.24/cache-util-2.1.24.pom";
      sha256 = "C58D75C3DE6AA7F1ABCE757524370D43665F9E07E89F2141DB21AABC9F83845E";
    };
    "nix-public/io/get-coursier/coursier-cache_2.12/2.1.24/coursier-cache_2.12-2.1.24-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-cache_2.12/2.1.24/coursier-cache_2.12-2.1.24-javadoc.jar";
      sha256 = "F41D2E4A1660D8DC8DE5B4437B574EDBBC98AB683B56F0E83FE98A50543E19C1";
    };
    "nix-public/io/get-coursier/coursier-cache_2.12/2.1.24/coursier-cache_2.12-2.1.24-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-cache_2.12/2.1.24/coursier-cache_2.12-2.1.24-sources.jar";
      sha256 = "C48ACB00717DD2D385FB792599D5FAC9C0BCEC803BCD1862641F237A8FF46360";
    };
    "nix-public/io/get-coursier/coursier-cache_2.12/2.1.24/coursier-cache_2.12-2.1.24.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-cache_2.12/2.1.24/coursier-cache_2.12-2.1.24.jar";
      sha256 = "FDA852B40E62241FA61E2C56332A83B1D7A11E677FE0EBB9E9EF33A189D310FE";
    };
    "nix-public/io/get-coursier/coursier-cache_2.12/2.1.24/coursier-cache_2.12-2.1.24.pom" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-cache_2.12/2.1.24/coursier-cache_2.12-2.1.24.pom";
      sha256 = "A5359DD19A1C5081F949CCBB532BBEFF28944F5C5BBF93DD1CF8CC4E116384A9";
    };
    "nix-public/io/get-coursier/coursier-core_2.12/2.1.24/coursier-core_2.12-2.1.24-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-core_2.12/2.1.24/coursier-core_2.12-2.1.24-javadoc.jar";
      sha256 = "0FB44849904B9B721174260E8C554F7198204D3CA70E73E117B9E5B2FA26CDFC";
    };
    "nix-public/io/get-coursier/coursier-core_2.12/2.1.24/coursier-core_2.12-2.1.24-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-core_2.12/2.1.24/coursier-core_2.12-2.1.24-sources.jar";
      sha256 = "FA4A88EDF9CC756D4F785BCF8C406D69F1CEB409D3EE6D1A7D5F4C8930986816";
    };
    "nix-public/io/get-coursier/coursier-core_2.12/2.1.24/coursier-core_2.12-2.1.24.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-core_2.12/2.1.24/coursier-core_2.12-2.1.24.jar";
      sha256 = "85BA2F54DB0B79A5D8BE519EB4F5B45B1065924D8DBCF4F19FDA98BF93417D2A";
    };
    "nix-public/io/get-coursier/coursier-core_2.12/2.1.24/coursier-core_2.12-2.1.24.pom" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-core_2.12/2.1.24/coursier-core_2.12-2.1.24.pom";
      sha256 = "8D3D38BE8202E34465E3C01BDC08467C3FD6B394C4C35C5D9205AC0777CDD87E";
    };
    "nix-public/io/get-coursier/coursier-proxy-setup/2.1.24/coursier-proxy-setup-2.1.24-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-proxy-setup/2.1.24/coursier-proxy-setup-2.1.24-javadoc.jar";
      sha256 = "FC92EBA5ACA0F336A4B92B5126CFE36F60C4E6D93D44A33B057234B58344B53B";
    };
    "nix-public/io/get-coursier/coursier-proxy-setup/2.1.24/coursier-proxy-setup-2.1.24-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-proxy-setup/2.1.24/coursier-proxy-setup-2.1.24-sources.jar";
      sha256 = "A5B50CCD284C23708C9FD788D1B611F68697E098D0B26B8F4AE85482492801DA";
    };
    "nix-public/io/get-coursier/coursier-proxy-setup/2.1.24/coursier-proxy-setup-2.1.24.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-proxy-setup/2.1.24/coursier-proxy-setup-2.1.24.jar";
      sha256 = "BD7DFA4325FEC5E2E4CB671BB42953E970A2F9141526D93AAEA678A07DA3CE5B";
    };
    "nix-public/io/get-coursier/coursier-proxy-setup/2.1.24/coursier-proxy-setup-2.1.24.pom" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-proxy-setup/2.1.24/coursier-proxy-setup-2.1.24.pom";
      sha256 = "E9F1B2344F6644BCCE799B5378067CD83AC5E471BBB4730B5875AC6B03E0A4AD";
    };
    "nix-public/io/get-coursier/coursier-sbt-maven-repository_2.12/2.1.24/coursier-sbt-maven-repository_2.12-2.1.24-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-sbt-maven-repository_2.12/2.1.24/coursier-sbt-maven-repository_2.12-2.1.24-javadoc.jar";
      sha256 = "226C988E6926370296CBB2886380F5F8ED98A05EF05B680EE0321F90C7B4ADFA";
    };
    "nix-public/io/get-coursier/coursier-sbt-maven-repository_2.12/2.1.24/coursier-sbt-maven-repository_2.12-2.1.24-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-sbt-maven-repository_2.12/2.1.24/coursier-sbt-maven-repository_2.12-2.1.24-sources.jar";
      sha256 = "974B3D52E91876A04592A3D7401447D4B81E462104AD38D42B55D436844D18A9";
    };
    "nix-public/io/get-coursier/coursier-sbt-maven-repository_2.12/2.1.24/coursier-sbt-maven-repository_2.12-2.1.24.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-sbt-maven-repository_2.12/2.1.24/coursier-sbt-maven-repository_2.12-2.1.24.jar";
      sha256 = "1713701912FF4EF9C76EFBA2FC86ACBFA2438C2A02487CDC66711747E87FAA58";
    };
    "nix-public/io/get-coursier/coursier-sbt-maven-repository_2.12/2.1.24/coursier-sbt-maven-repository_2.12-2.1.24.pom" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-sbt-maven-repository_2.12/2.1.24/coursier-sbt-maven-repository_2.12-2.1.24.pom";
      sha256 = "C492D5F4BD8EA29DA5F5A51EDD8C4796A4BE6EC5D14907F8DF3E517C00E4C564";
    };
    "nix-public/io/get-coursier/coursier-util_2.12/2.1.24/coursier-util_2.12-2.1.24-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-util_2.12/2.1.24/coursier-util_2.12-2.1.24-javadoc.jar";
      sha256 = "0F08093AB9D312193600AFD3B468F2822290563E3680DFBD374C664D08FC1821";
    };
    "nix-public/io/get-coursier/coursier-util_2.12/2.1.24/coursier-util_2.12-2.1.24-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-util_2.12/2.1.24/coursier-util_2.12-2.1.24-sources.jar";
      sha256 = "9410C64FDF5553347DF8574FD99F0EFFACD391D1567415E1368BF18A41E132AD";
    };
    "nix-public/io/get-coursier/coursier-util_2.12/2.1.24/coursier-util_2.12-2.1.24.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-util_2.12/2.1.24/coursier-util_2.12-2.1.24.jar";
      sha256 = "30D02902DBF7D1AC6CB2822974226732B1CEB957D87F22B3AD14108495BDFCB1";
    };
    "nix-public/io/get-coursier/coursier-util_2.12/2.1.24/coursier-util_2.12-2.1.24.pom" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier-util_2.12/2.1.24/coursier-util_2.12-2.1.24.pom";
      sha256 = "A5EE542FBC25A0D3DC28E31594087F0F63CA8B6CCFF57A7C7DDC9168B7539967";
    };
    "nix-public/io/get-coursier/coursier_2.12/2.1.24/coursier_2.12-2.1.24-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier_2.12/2.1.24/coursier_2.12-2.1.24-javadoc.jar";
      sha256 = "DA946B9CD7256E9208661000A4070FD1D9593D0555257824DCAF9C08C4FC2D30";
    };
    "nix-public/io/get-coursier/coursier_2.12/2.1.24/coursier_2.12-2.1.24-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier_2.12/2.1.24/coursier_2.12-2.1.24-sources.jar";
      sha256 = "D561C39815E06C8851C9BDF517403F0BDDA67B05A6D48451974D20C939BF171F";
    };
    "nix-public/io/get-coursier/coursier_2.12/2.1.24/coursier_2.12-2.1.24.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier_2.12/2.1.24/coursier_2.12-2.1.24.jar";
      sha256 = "F5A93B3C4374452CB36E60C304830F381EDA216EDF8855EB31C7E0FC33AB4197";
    };
    "nix-public/io/get-coursier/coursier_2.12/2.1.24/coursier_2.12-2.1.24.pom" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/coursier_2.12/2.1.24/coursier_2.12-2.1.24.pom";
      sha256 = "5ACEF40230D2D121FD6B98941444EE03BD01A984F9CA608CECCD9DEB39DF372D";
    };
    "nix-public/io/get-coursier/dependency_2.12/0.3.2/dependency_2.12-0.3.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/dependency_2.12/0.3.2/dependency_2.12-0.3.2-javadoc.jar";
      sha256 = "BA3498B96E39083817D89476BF878832DC4802C87DAF8FE1E0EB4B2622EC8988";
    };
    "nix-public/io/get-coursier/dependency_2.12/0.3.2/dependency_2.12-0.3.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/dependency_2.12/0.3.2/dependency_2.12-0.3.2-sources.jar";
      sha256 = "10AC0FC9FEE555BE20023D2458E02E1ABE150A9F122A3E0D500E553DC819C95D";
    };
    "nix-public/io/get-coursier/dependency_2.12/0.3.2/dependency_2.12-0.3.2.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/dependency_2.12/0.3.2/dependency_2.12-0.3.2.jar";
      sha256 = "5192587C13DEE48917304611902D45B2ABDD8F7811CCAF4D74B45C18746D266E";
    };
    "nix-public/io/get-coursier/dependency_2.12/0.3.2/dependency_2.12-0.3.2.pom" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/dependency_2.12/0.3.2/dependency_2.12-0.3.2.pom";
      sha256 = "0886A37BB039A0C93B1EEDE44BAB390D0AC72F38E5507F1C1DA8E20AE6764151";
    };
    "nix-public/io/get-coursier/jniutils/windows-jni-utils/0.3.3/windows-jni-utils-0.3.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/jniutils/windows-jni-utils/0.3.3/windows-jni-utils-0.3.3-javadoc.jar";
      sha256 = "36063D2BF6BC4E82FF9B5941050407C91801D54563A76EEDD360F36B4D8AE561";
    };
    "nix-public/io/get-coursier/jniutils/windows-jni-utils/0.3.3/windows-jni-utils-0.3.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/jniutils/windows-jni-utils/0.3.3/windows-jni-utils-0.3.3-sources.jar";
      sha256 = "D533760CEF440EB3A8A47CFE6815E1F9A161CB1F01A5A61DBF8B2A30489C8583";
    };
    "nix-public/io/get-coursier/jniutils/windows-jni-utils/0.3.3/windows-jni-utils-0.3.3.jar" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/jniutils/windows-jni-utils/0.3.3/windows-jni-utils-0.3.3.jar";
      sha256 = "AB68EFCF162355E20007B238D8108B7FFEC0C06B467EE44CBB44EC3F8AC3A7E6";
    };
    "nix-public/io/get-coursier/jniutils/windows-jni-utils/0.3.3/windows-jni-utils-0.3.3.pom" = {
      url = "https://repo1.maven.org/maven2/io/get-coursier/jniutils/windows-jni-utils/0.3.3/windows-jni-utils-0.3.3.pom";
      sha256 = "AD53900F92683F3714BE442ECB464421A5F8FA2890C1A91B1FBE3E0ECD62914B";
    };
    "nix-public/io/github/alexarchambault/concurrent-reference-hash-map/1.1.0/concurrent-reference-hash-map-1.1.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/io/github/alexarchambault/concurrent-reference-hash-map/1.1.0/concurrent-reference-hash-map-1.1.0-javadoc.jar";
      sha256 = "D0426D106B0ACC361EEA00E1717DBA2DBA1FB179034FFC76F200A25526671B43";
    };
    "nix-public/io/github/alexarchambault/concurrent-reference-hash-map/1.1.0/concurrent-reference-hash-map-1.1.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/github/alexarchambault/concurrent-reference-hash-map/1.1.0/concurrent-reference-hash-map-1.1.0-sources.jar";
      sha256 = "931213419BA6C90769C7BA73F85973EC79EF55BB6A99BA3093E87A427AC0D2AC";
    };
    "nix-public/io/github/alexarchambault/concurrent-reference-hash-map/1.1.0/concurrent-reference-hash-map-1.1.0.jar" = {
      url = "https://repo1.maven.org/maven2/io/github/alexarchambault/concurrent-reference-hash-map/1.1.0/concurrent-reference-hash-map-1.1.0.jar";
      sha256 = "552707982209AFB9FEFFDCCB2E73CC4681A1353E34A47DF1BF643D1D2E0A2F61";
    };
    "nix-public/io/github/alexarchambault/concurrent-reference-hash-map/1.1.0/concurrent-reference-hash-map-1.1.0.pom" = {
      url = "https://repo1.maven.org/maven2/io/github/alexarchambault/concurrent-reference-hash-map/1.1.0/concurrent-reference-hash-map-1.1.0.pom";
      sha256 = "21096686F9964694DB1B8F16F471C3B9B8FB278E390950FAC683760C4A6F0816";
    };
    "nix-public/io/github/alexarchambault/is-terminal/0.1.1/is-terminal-0.1.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/io/github/alexarchambault/is-terminal/0.1.1/is-terminal-0.1.1-javadoc.jar";
      sha256 = "4DBBE48AB653AE5A6EF450D81857311FD1C9825C921DFCF1EDB341243281502C";
    };
    "nix-public/io/github/alexarchambault/is-terminal/0.1.1/is-terminal-0.1.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/github/alexarchambault/is-terminal/0.1.1/is-terminal-0.1.1-sources.jar";
      sha256 = "A2D6525537B7DC6552C541F4C0BA485B05079D01DB85D59DDD1B69A40F159CE4";
    };
    "nix-public/io/github/alexarchambault/is-terminal/0.1.1/is-terminal-0.1.1.jar" = {
      url = "https://repo1.maven.org/maven2/io/github/alexarchambault/is-terminal/0.1.1/is-terminal-0.1.1.jar";
      sha256 = "73735B053B01FF47B53D28AB2D9B23FD86447F6FB6463DD462258067AD6AD3FA";
    };
    "nix-public/io/github/alexarchambault/is-terminal/0.1.1/is-terminal-0.1.1.pom" = {
      url = "https://repo1.maven.org/maven2/io/github/alexarchambault/is-terminal/0.1.1/is-terminal-0.1.1.pom";
      sha256 = "6B666C221711D8289CF2FB4F443FE728EC531348175DA529056D7FCECBEE6122";
    };
    "nix-public/io/github/alexarchambault/windows-ansi/windows-ansi/0.0.6/windows-ansi-0.0.6-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/io/github/alexarchambault/windows-ansi/windows-ansi/0.0.6/windows-ansi-0.0.6-javadoc.jar";
      sha256 = "DAAE9745F475F4DD2E1B5A5F2134E032ABDD14B4C391DCDE3214BF38F3035EAC";
    };
    "nix-public/io/github/alexarchambault/windows-ansi/windows-ansi/0.0.6/windows-ansi-0.0.6-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/github/alexarchambault/windows-ansi/windows-ansi/0.0.6/windows-ansi-0.0.6-sources.jar";
      sha256 = "121FA106CB26F398D36BAF6D56CB145ADC2052923BF73AEC7A36C1035278194F";
    };
    "nix-public/io/github/alexarchambault/windows-ansi/windows-ansi/0.0.6/windows-ansi-0.0.6.jar" = {
      url = "https://repo1.maven.org/maven2/io/github/alexarchambault/windows-ansi/windows-ansi/0.0.6/windows-ansi-0.0.6.jar";
      sha256 = "077DBDBB977C94FC8B1FB82113CFB0AA5304D4E307C4E0688F69A9895F0DA482";
    };
    "nix-public/io/github/alexarchambault/windows-ansi/windows-ansi/0.0.6/windows-ansi-0.0.6.pom" = {
      url = "https://repo1.maven.org/maven2/io/github/alexarchambault/windows-ansi/windows-ansi/0.0.6/windows-ansi-0.0.6.pom";
      sha256 = "FE05E4478202C3DADD72E1FC0B66AA342462688D2E66114B4DD356BB0F011D5E";
    };
    "nix-public/javax/inject/javax.inject/1/javax.inject-1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/javax/inject/javax.inject/1/javax.inject-1-javadoc.jar";
      sha256 = "F938E8EB481314D7306AE16AD91998409C8C8056BF336BC0732B4A07AD4A4F44";
    };
    "nix-public/javax/inject/javax.inject/1/javax.inject-1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/javax/inject/javax.inject/1/javax.inject-1-sources.jar";
      sha256 = "C4B87EE2911C139C3DAF498A781967F1EB2E75BC1A8529A2E7B328A15D0E433E";
    };
    "nix-public/javax/inject/javax.inject/1/javax.inject-1.jar" = {
      url = "https://repo1.maven.org/maven2/javax/inject/javax.inject/1/javax.inject-1.jar";
      sha256 = "91C77044A50C481636C32D916FD89C9118A72195390452C81065080F957DE7FF";
    };
    "nix-public/javax/inject/javax.inject/1/javax.inject-1.pom" = {
      url = "https://repo1.maven.org/maven2/javax/inject/javax.inject/1/javax.inject-1.pom";
      sha256 = "943E12B100627804638FA285805A0AB788A680266531E650921EBFE4621A8BFA";
    };
    "nix-public/org/apache/apache/30/apache-30.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/apache/30/apache-30.pom";
      sha256 = "63DD4A393A9C0DFCB314EFE83871A41D243BC8D200CBC7F2D197F30DA78239D8";
    };
    "nix-public/org/apache/apache/31/apache-31.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/apache/31/apache-31.pom";
      sha256 = "555D0C9EAA69C042AFF924927B9381E8F8174136D355EEAD445224452E6291CC";
    };
    "nix-public/org/apache/apache/6/apache-6.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/apache/6/apache-6.pom";
      sha256 = "12EDB5096E13F40C362D0BD40902589FA9586505123FA26799CE50B116FA5BB3";
    };
    "nix-public/org/apache/commons/commons-compress/1.26.2/commons-compress-1.26.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.26.2/commons-compress-1.26.2-javadoc.jar";
      sha256 = "4CB8833D3A768EFDBCEB2E65109DB720A09F0A75C7D631DE50451A5677C939D6";
    };
    "nix-public/org/apache/commons/commons-compress/1.26.2/commons-compress-1.26.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.26.2/commons-compress-1.26.2-sources.jar";
      sha256 = "89F2AC13872E1AC0024DC77573A0DA8E8E0DA2DDA58973F19244F6E60F08D138";
    };
    "nix-public/org/apache/commons/commons-compress/1.26.2/commons-compress-1.26.2-tests.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.26.2/commons-compress-1.26.2-tests.jar";
      sha256 = "5E59D46D2089641EA392C7AC059D38619AA664869FF5D2C1CAA26EAC512DD8DC";
    };
    "nix-public/org/apache/commons/commons-compress/1.26.2/commons-compress-1.26.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.26.2/commons-compress-1.26.2.jar";
      sha256 = "9168A03141D8FC7EDA21A2360D83CC0412BCBB1D6204D992BD48C2573CB3C6B8";
    };
    "nix-public/org/apache/commons/commons-compress/1.26.2/commons-compress-1.26.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.26.2/commons-compress-1.26.2.pom";
      sha256 = "1428719895CD0A913AEE33E2424B9A804B10F1197E5D35A9CE99CF2A1174CB0E";
    };
    "nix-public/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0-javadoc.jar";
      sha256 = "8FF9B01323BC636012D0140034C2ED00A00A3F754E32C6640F90680686DD3603";
    };
    "nix-public/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0-sources.jar";
      sha256 = "AB3B86AFB898F1026DBE43AAF71E9C1D719EC52D6E41887B362D86777C299B6F";
    };
    "nix-public/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0-tests.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0-tests.jar";
      sha256 = "36BFD79260225E8EC173856A23E10FB6D514783EFCCCB1153804AA6C6CD2125E";
    };
    "nix-public/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0.jar";
      sha256 = "7B96BF3EE68949ABB5BC465559AC270E0551596FA34523FDDF890EC418DDE13C";
    };
    "nix-public/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0.pom";
      sha256 = "110438863BAD37C28F906BF87016E38C7A8C758BA321E09D11DC5A2363A8E79E";
    };
    "nix-public/org/apache/commons/commons-parent/64/commons-parent-64.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-parent/64/commons-parent-64.pom";
      sha256 = "6F19638994E8357B4ED734696F992057EFAAFA1235673998133299798E2CCDDB";
    };
    "nix-public/org/apache/commons/commons-parent/69/commons-parent-69.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-parent/69/commons-parent-69.pom";
      sha256 = "D50DA9C39BDCA823D618D1B4A03B73F196497FCB8616FD0DA727C8623592A9BB";
    };
    "nix-public/org/apache/geronimo/genesis/genesis-default-flava/2.0/genesis-default-flava-2.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/geronimo/genesis/genesis-default-flava/2.0/genesis-default-flava-2.0.pom";
      sha256 = "08E6E146F4E245266DFF9DD800B12875DD2367D3F67A34AB660A126C811215F8";
    };
    "nix-public/org/apache/geronimo/genesis/genesis-java5-flava/2.0/genesis-java5-flava-2.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/geronimo/genesis/genesis-java5-flava/2.0/genesis-java5-flava-2.0.pom";
      sha256 = "E7C5358BBBBC27DAA5B327F63BC12650A75DDC9F9AC6D4BFA12789BE1F2C29DB";
    };
    "nix-public/org/apache/geronimo/genesis/genesis/2.0/genesis-2.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/geronimo/genesis/genesis/2.0/genesis-2.0.pom";
      sha256 = "B9ED2F9DD434631158D77308EE5648622C229CCECE1722C5E377A4296923DAE6";
    };
    "nix-public/org/apache/xbean/xbean-reflect/3.7/xbean-reflect-3.7-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/xbean/xbean-reflect/3.7/xbean-reflect-3.7-javadoc.jar";
      sha256 = "0D8E51B243F53E282D9B14C8436FE7C831D288C7B38877BA87E2F05F39E216DD";
    };
    "nix-public/org/apache/xbean/xbean-reflect/3.7/xbean-reflect-3.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/xbean/xbean-reflect/3.7/xbean-reflect-3.7-sources.jar";
      sha256 = "ED59780DB1EE258D806C6DA541D74EF23FB9B05A5C96CC7F28E6FB203D2D4F9E";
    };
    "nix-public/org/apache/xbean/xbean-reflect/3.7/xbean-reflect-3.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/xbean/xbean-reflect/3.7/xbean-reflect-3.7.jar";
      sha256 = "104E5E9BB5A669F86722F32281960700F7EC8E3209EF51B23EB9B6D23D1629CB";
    };
    "nix-public/org/apache/xbean/xbean-reflect/3.7/xbean-reflect-3.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/xbean/xbean-reflect/3.7/xbean-reflect-3.7.pom";
      sha256 = "9795C15322C5D19AF336EEBD9E164FA7D5897C4B004A7D66E21635A173E748A9";
    };
    "nix-public/org/apache/xbean/xbean/3.7/xbean-3.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/xbean/xbean/3.7/xbean-3.7.pom";
      sha256 = "EA717132DE8404B62FC9097A1F3215C705D525D457BE9A5F12653ADC68C33AB7";
    };
    "nix-public/org/codehaus/plexus/plexus-archiver/4.10.0/plexus-archiver-4.10.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-archiver/4.10.0/plexus-archiver-4.10.0-javadoc.jar";
      sha256 = "79AA09A519C9DEC14125B9C0CA4DA660498F4561C07AB2BA3C21F8BAD6122295";
    };
    "nix-public/org/codehaus/plexus/plexus-archiver/4.10.0/plexus-archiver-4.10.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-archiver/4.10.0/plexus-archiver-4.10.0-sources.jar";
      sha256 = "8559ED68292E11228D36155C0932AE3F54D743F7A19AD5CE51E253A52D6499C8";
    };
    "nix-public/org/codehaus/plexus/plexus-archiver/4.10.0/plexus-archiver-4.10.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-archiver/4.10.0/plexus-archiver-4.10.0.jar";
      sha256 = "4C07814FF4A39199999AE82BBA1E38AA4F25637467FCAC6A66ED63A76535799A";
    };
    "nix-public/org/codehaus/plexus/plexus-archiver/4.10.0/plexus-archiver-4.10.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-archiver/4.10.0/plexus-archiver-4.10.0.pom";
      sha256 = "93CA001FD33DA53D38B74F6DAF19E71BC9736ED6143091FF9003CD4C05ACE6C9";
    };
    "nix-public/org/codehaus/plexus/plexus-classworlds/2.6.0/plexus-classworlds-2.6.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-classworlds/2.6.0/plexus-classworlds-2.6.0-javadoc.jar";
      sha256 = "5E8D56C40B60A36455ACE80AECDD46F5310A0385C9C4DDC074CBEE660942C848";
    };
    "nix-public/org/codehaus/plexus/plexus-classworlds/2.6.0/plexus-classworlds-2.6.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-classworlds/2.6.0/plexus-classworlds-2.6.0-sources.jar";
      sha256 = "A9DC469D6D1AD442D6661E677614BD102B5FCF30A27D55533EF05AF7807CAB89";
    };
    "nix-public/org/codehaus/plexus/plexus-classworlds/2.6.0/plexus-classworlds-2.6.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-classworlds/2.6.0/plexus-classworlds-2.6.0.jar";
      sha256 = "52F77C5EC49F787C9C417EBED5D6EFD9922F44A202F217376E4F94C0D74F3549";
    };
    "nix-public/org/codehaus/plexus/plexus-classworlds/2.6.0/plexus-classworlds-2.6.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-classworlds/2.6.0/plexus-classworlds-2.6.0.pom";
      sha256 = "469A6C59F92EFFA62C0797CE7D52D2C03CF8EE1034B923C360DD78A9F505A7BA";
    };
    "nix-public/org/codehaus/plexus/plexus-container-default/2.1.1/plexus-container-default-2.1.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-container-default/2.1.1/plexus-container-default-2.1.1-javadoc.jar";
      sha256 = "66AA674CE73FABE8BAE3B9F2A992CD4DC211CE459EE15FFD7C964634ACE15AF0";
    };
    "nix-public/org/codehaus/plexus/plexus-container-default/2.1.1/plexus-container-default-2.1.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-container-default/2.1.1/plexus-container-default-2.1.1-sources.jar";
      sha256 = "9356606244FB5E6E19F5DB845D8C09BD62DD74AC8444251740968B6241DFAE8F";
    };
    "nix-public/org/codehaus/plexus/plexus-container-default/2.1.1/plexus-container-default-2.1.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-container-default/2.1.1/plexus-container-default-2.1.1.jar";
      sha256 = "8B65840E41CA669A1A69EC1DAEDB3426304E560B24172CC93BB02E8C199E1CE7";
    };
    "nix-public/org/codehaus/plexus/plexus-container-default/2.1.1/plexus-container-default-2.1.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-container-default/2.1.1/plexus-container-default-2.1.1.pom";
      sha256 = "0F5C6E592459262FC34942C2F4DF370230EC2765DD4B707F54C269FDF5C5A7E3";
    };
    "nix-public/org/codehaus/plexus/plexus-containers/2.1.1/plexus-containers-2.1.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-containers/2.1.1/plexus-containers-2.1.1.pom";
      sha256 = "C129AE94BC6DE8BA2596FCDAD4B3FCFE4F67640A4CB6D76A5540182214AA833C";
    };
    "nix-public/org/codehaus/plexus/plexus-io/3.5.0/plexus-io-3.5.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-io/3.5.0/plexus-io-3.5.0-javadoc.jar";
      sha256 = "E6F633470350E68EBE36DD51F62775A4C71739739074C97B77091E78D3757543";
    };
    "nix-public/org/codehaus/plexus/plexus-io/3.5.0/plexus-io-3.5.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-io/3.5.0/plexus-io-3.5.0-sources.jar";
      sha256 = "C2505097B5F1493A65B83252176008C887FAFA502198DE04293DC9276C50EFAA";
    };
    "nix-public/org/codehaus/plexus/plexus-io/3.5.0/plexus-io-3.5.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-io/3.5.0/plexus-io-3.5.0.jar";
      sha256 = "965ED28912CF1AE4C628112C4009E0C19819BC44ED5DB8AF54EE5EDA21036A3E";
    };
    "nix-public/org/codehaus/plexus/plexus-io/3.5.0/plexus-io-3.5.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-io/3.5.0/plexus-io-3.5.0.pom";
      sha256 = "F5B86CD223A0BF4BA649DE19E7E8E4E1F14344FF636F8B0024C89C46D28CC9D8";
    };
    "nix-public/org/codehaus/plexus/plexus-utils/3.1.1/plexus-utils-3.1.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-utils/3.1.1/plexus-utils-3.1.1-javadoc.jar";
      sha256 = "F3BDED62A7CAC2102C4DC17ACF04E4ECB416A02175E9C3B426B059BF414D5810";
    };
    "nix-public/org/codehaus/plexus/plexus-utils/3.1.1/plexus-utils-3.1.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-utils/3.1.1/plexus-utils-3.1.1-sources.jar";
      sha256 = "487D8082A32FA72ECFFCFE5AA7AB783ECCEB4BC26F2AF858AE10AC83C4DF3F45";
    };
    "nix-public/org/codehaus/plexus/plexus-utils/3.1.1/plexus-utils-3.1.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-utils/3.1.1/plexus-utils-3.1.1.jar";
      sha256 = "D1F74A7A0D91EB82536D71175B177BF21B1D7D286376B0EA5BA8A194265BA90B";
    };
    "nix-public/org/codehaus/plexus/plexus-utils/3.1.1/plexus-utils-3.1.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-utils/3.1.1/plexus-utils-3.1.1.pom";
      sha256 = "6E9EF6A42B78C418176D07882762F53664BC39BAC88135BE8CB56337C050E6DD";
    };
    "nix-public/org/codehaus/plexus/plexus-utils/4.0.1/plexus-utils-4.0.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-utils/4.0.1/plexus-utils-4.0.1-javadoc.jar";
      sha256 = "9E3440911D4ED752ABE3A53E6124D2B678F313E7B2644290A65F62B47E45EAB6";
    };
    "nix-public/org/codehaus/plexus/plexus-utils/4.0.1/plexus-utils-4.0.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-utils/4.0.1/plexus-utils-4.0.1-sources.jar";
      sha256 = "AFE1A6B22D68B06ECD0CFCD1B2F881762C1FA4912ACE3F1B002A38EE62765331";
    };
    "nix-public/org/codehaus/plexus/plexus-utils/4.0.1/plexus-utils-4.0.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-utils/4.0.1/plexus-utils-4.0.1.jar";
      sha256 = "96B9CC44439191D2D0635974E2D44E768736B4FB2ABCB65F94CD95E41912FA8B";
    };
    "nix-public/org/codehaus/plexus/plexus-utils/4.0.1/plexus-utils-4.0.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-utils/4.0.1/plexus-utils-4.0.1.pom";
      sha256 = "BC4235A95CD1EBAE42644C81EBBA9C1D4C52565F81E96AB204B6E56E3E378CC1";
    };
    "nix-public/org/codehaus/plexus/plexus/17/plexus-17.pom" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus/17/plexus-17.pom";
      sha256 = "91526EE66327C7F50FBB25BD41BFCB916E284414B868E31D50A23004BD7DEEA7";
    };
    "nix-public/org/codehaus/plexus/plexus/18/plexus-18.pom" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus/18/plexus-18.pom";
      sha256 = "B43EE89C8890B9E5BC48D079FCB4C44F082B5139253356DC455806A33C3DD8FD";
    };
    "nix-public/org/codehaus/plexus/plexus/4.0/plexus-4.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus/4.0/plexus-4.0.pom";
      sha256 = "0A1B692D7FCC90D6A45DAE2E50F4660D48F7A44504F174AA60EF34FBE1327F6A";
    };
    "nix-public/org/codehaus/plexus/plexus/5.1/plexus-5.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus/5.1/plexus-5.1.pom";
      sha256 = "A343E44FF5796AED0EA60BE11454C935CE20AB1C5F164ACC8DA574482DCBC7E9";
    };
    "nix-public/org/codehaus/plexus/plexus/6.5/plexus-6.5.pom" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/plexus/plexus/6.5/plexus-6.5.pom";
      sha256 = "737FF2200498DD54C920712404CAA4426D38639D05014FF3EF1B3E7C5BD91397";
    };
    "nix-public/org/fusesource/fusesource-pom/1.12/fusesource-pom-1.12.pom" = {
      url = "https://repo1.maven.org/maven2/org/fusesource/fusesource-pom/1.12/fusesource-pom-1.12.pom";
      sha256 = "C40D960DAADCEF7B01C1B1C6657AFBAC4FFFB5E53168F8FCB0B28B84E6FDCCA1";
    };
    "nix-public/org/fusesource/jansi/jansi/2.4.1/jansi-2.4.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/2.4.1/jansi-2.4.1-javadoc.jar";
      sha256 = "7FDE25D354E977715F0D0FFE3EF49E0747226CB5FD7F1E4E34CF3758F87064DC";
    };
    "nix-public/org/fusesource/jansi/jansi/2.4.1/jansi-2.4.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/2.4.1/jansi-2.4.1-sources.jar";
      sha256 = "F707511567A13EBF8C51164133770EB5A8E023E1D391BFBC6E7A0591C71729B8";
    };
    "nix-public/org/fusesource/jansi/jansi/2.4.1/jansi-2.4.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/2.4.1/jansi-2.4.1.jar";
      sha256 = "2E5E775A9DC58FFA6BBD6AA6F099D62F8B62DCDEB4C3C3BBBE5CF2301BC2DCC1";
    };
    "nix-public/org/fusesource/jansi/jansi/2.4.1/jansi-2.4.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/2.4.1/jansi-2.4.1.pom";
      sha256 = "3F98D979A4D3559F8779FBB004B34AE7516AFADF510E11DF7CC3CD073EB1BB3B";
    };
    "nix-public/org/junit/junit-bom/5.10.0/junit-bom-5.10.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/junit/junit-bom/5.10.0/junit-bom-5.10.0.pom";
      sha256 = "E006DD8894F9FC7B75FC32BB12FE5ED8BE65667D5B454F99E2E0B8C5BB8D30B3";
    };
    "nix-public/org/junit/junit-bom/5.10.2/junit-bom-5.10.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/junit/junit-bom/5.10.2/junit-bom-5.10.2.pom";
      sha256 = "169DD904A4B0F6520CFFE658CC62292BFE9F3C14A989FA92120724CDE43A9968";
    };
    "nix-public/org/junit/junit-bom/5.8.0-M1/junit-bom-5.8.0-M1.pom" = {
      url = "https://repo1.maven.org/maven2/org/junit/junit-bom/5.8.0-M1/junit-bom-5.8.0-M1.pom";
      sha256 = "77144432FFC68BD98A790AB1069619D91032CFC0E4E13C08163AA03DA36FD6E2";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.12/2.11.0/scala-collection-compat_2.12-2.11.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.12/2.11.0/scala-collection-compat_2.12-2.11.0-javadoc.jar";
      sha256 = "56084DEA915CDDFA6A9ACC7D8D0F8A4601673B6A5F26F339F8E2A1DD9B5C6195";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.12/2.11.0/scala-collection-compat_2.12-2.11.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.12/2.11.0/scala-collection-compat_2.12-2.11.0-sources.jar";
      sha256 = "417EE9A96807566572956777AA7633BA8A63B3452357C4CB064C3F99A725F07C";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.12/2.11.0/scala-collection-compat_2.12-2.11.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.12/2.11.0/scala-collection-compat_2.12-2.11.0.jar";
      sha256 = "7BF170604A148A342C7D1B1C7D181DD41E9C60B7B459DD49B2BCF12BE69EA675";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.12/2.11.0/scala-collection-compat_2.12-2.11.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.12/2.11.0/scala-collection-compat_2.12-2.11.0.pom";
      sha256 = "FFCFEE77D98AF426C1B0481D0093CA626C045625764E31EA916E03C527635387";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.12/2.12.0/scala-collection-compat_2.12-2.12.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.12/2.12.0/scala-collection-compat_2.12-2.12.0-javadoc.jar";
      sha256 = "20238FA6BF4E2572A61A2A85A99BA6EA5876344B8CF1FF0FA3E0029069F4197E";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.12/2.12.0/scala-collection-compat_2.12-2.12.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.12/2.12.0/scala-collection-compat_2.12-2.12.0-sources.jar";
      sha256 = "96A9B593330C8B0FE82D2E269BD8E6B46DD9EBA5532F0C06D01DAB2F87665E87";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.12/2.12.0/scala-collection-compat_2.12-2.12.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.12/2.12.0/scala-collection-compat_2.12-2.12.0.jar";
      sha256 = "1619C5E4399E1E4793667970AAE232652DB0549E795C90ABF91E44C55EC37CB3";
    };
    "nix-public/org/scala-lang/modules/scala-collection-compat_2.12/2.12.0/scala-collection-compat_2.12-2.12.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.12/2.12.0/scala-collection-compat_2.12-2.12.0.pom";
      sha256 = "02C3511378C3A0568F4B1B150A385637AF86BCF5F8CAB642F28B71622BF9ED4B";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.1.0/scala-xml_2.12-2.1.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.1.0/scala-xml_2.12-2.1.0-javadoc.jar";
      sha256 = "E3FCF430BDCE9EF43AF2F216A66912802E5F4ED84E4D59AB7D229D9788A6FDE8";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.1.0/scala-xml_2.12-2.1.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.1.0/scala-xml_2.12-2.1.0-sources.jar";
      sha256 = "A1E978244D4FA59A22846B2553343EB8D8CAE0933928238E3154AA02B47CF8EE";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.1.0/scala-xml_2.12-2.1.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.1.0/scala-xml_2.12-2.1.0.jar";
      sha256 = "D9A6DF43CFAC692F05E7166D39AAE4476A246DAC7740C7794A3072F1A67280CE";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.1.0/scala-xml_2.12-2.1.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.1.0/scala-xml_2.12-2.1.0.pom";
      sha256 = "3222A480A238295AB5ED9AAA03D4DCEDB37921F2D2353755E558A9FF9C290A57";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0-javadoc.jar";
      sha256 = "3C30CA09ED34A472F48BBA732B1360432DB09584B6540DBBB18904C87CECF80F";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0-sources.jar";
      sha256 = "BB93B2FDCD36EBD3E7E6E6DE961CD2A4EAD3815C9565C7BE5CAD860CF3D8C81C";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0.jar";
      sha256 = "4932C56A2D5AAE77AE8D7AC6BED1F21D48268FDBAC8B4E5F3CA5196AD10FD93E";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/2.3.0/scala-xml_2.12-2.3.0.pom";
      sha256 = "45BC645F881F34E6338B478007C6DD93D17389A4F4138616AE7EFA854BAAAA46";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.20/scala-compiler-2.12.20-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.20/scala-compiler-2.12.20-javadoc.jar";
      sha256 = "F90B5673992922C578471AA7A79B27616943C6DD4167D10381D2A6D5373A77B0";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.20/scala-compiler-2.12.20-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.20/scala-compiler-2.12.20-sources.jar";
      sha256 = "07C140C8187A7BCBCFCE7509EB4F1704FCBFA12AD3C7798F8DDCAB9477DC5028";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.20/scala-compiler-2.12.20.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.20/scala-compiler-2.12.20.jar";
      sha256 = "C88676D75C69721B717EA6C441ECE04FFF262ABAB9D210A2936ABC2BE3731FA2";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.20/scala-compiler-2.12.20.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.20/scala-compiler-2.12.20.pom";
      sha256 = "D04B837110423B145973F9A6516AB6AFD9C09C50543B8C7C63AC6C90AD4CCAA3";
    };
    "nix-public/org/scala-lang/scala-library/2.12.15/scala-library-2.12.15-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.15/scala-library-2.12.15-javadoc.jar";
      sha256 = "EDE7B5B9F794B8D370D1D3AAF1820B7397D16F005948C14DD7577FA77DC90DC2";
    };
    "nix-public/org/scala-lang/scala-library/2.12.15/scala-library-2.12.15-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.15/scala-library-2.12.15-sources.jar";
      sha256 = "E6BE8E8AD322CFD312B06FE96E38F58DB30A512EFC009B91D9045C2D4F331CE2";
    };
    "nix-public/org/scala-lang/scala-library/2.12.15/scala-library-2.12.15.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.15/scala-library-2.12.15.jar";
      sha256 = "E518BB640E2175DE5CB1F8E326679B8D975376221F1B547757DE429BBF4563F0";
    };
    "nix-public/org/scala-lang/scala-library/2.12.15/scala-library-2.12.15.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.15/scala-library-2.12.15.pom";
      sha256 = "4F3AAE4C7F93BBE5AFCDBED7B6AB560CEC3AA3B465095F318534E11597901E89";
    };
    "nix-public/org/scala-lang/scala-library/2.12.17/scala-library-2.12.17-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.17/scala-library-2.12.17-javadoc.jar";
      sha256 = "5CFB9268718C697E684A002E285CFCE286E7B37E56C024F293074F61BFBC68D8";
    };
    "nix-public/org/scala-lang/scala-library/2.12.17/scala-library-2.12.17-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.17/scala-library-2.12.17-sources.jar";
      sha256 = "5BE32C45CFC1B7A7BBE37FB3D5F018C41F3F09C999C97AEA10E8F18FB4C5D176";
    };
    "nix-public/org/scala-lang/scala-library/2.12.17/scala-library-2.12.17.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.17/scala-library-2.12.17.jar";
      sha256 = "7EEFDE7E3CC1937F78DC13B9E6C00746F602CFF6F5621D62DF2C24D922619FE0";
    };
    "nix-public/org/scala-lang/scala-library/2.12.17/scala-library-2.12.17.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.17/scala-library-2.12.17.pom";
      sha256 = "0DEDE34FD83E05FE15D226000D209D57249BB9D280B00C8735E783FCCEECDBB5";
    };
    "nix-public/org/scala-lang/scala-library/2.12.18/scala-library-2.12.18-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.18/scala-library-2.12.18-javadoc.jar";
      sha256 = "25C4B5570ABAF708989EA41213E5BEEAC53A430299ECA8C3438FCB310D49C629";
    };
    "nix-public/org/scala-lang/scala-library/2.12.18/scala-library-2.12.18-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.18/scala-library-2.12.18-sources.jar";
      sha256 = "A34DB9AB4B38C57F998E8F671B33762E2D6C3E39B8ABF6FB8660A417447FA449";
    };
    "nix-public/org/scala-lang/scala-library/2.12.18/scala-library-2.12.18.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.18/scala-library-2.12.18.jar";
      sha256 = "E51E6636C003359E106BEA4AD99DEF70E613C290190C8C84F10F9560DD5B00AE";
    };
    "nix-public/org/scala-lang/scala-library/2.12.18/scala-library-2.12.18.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.18/scala-library-2.12.18.pom";
      sha256 = "C7BCAE55EB71211DCB3305FD5EAFF1ADD551C53A8B6173C1C02D800C6EACF097";
    };
    "nix-public/org/scala-lang/scala-library/2.12.19/scala-library-2.12.19-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.19/scala-library-2.12.19-javadoc.jar";
      sha256 = "6CF378296217A280C04037CF3AB7634BF7889EB8AC14333F721E7B5A0DA821A3";
    };
    "nix-public/org/scala-lang/scala-library/2.12.19/scala-library-2.12.19-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.19/scala-library-2.12.19-sources.jar";
      sha256 = "8BFC1530510A87686EF1081F60714C594D752FCF025B92ACFD0FF6C09A7EFA76";
    };
    "nix-public/org/scala-lang/scala-library/2.12.19/scala-library-2.12.19.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.19/scala-library-2.12.19.jar";
      sha256 = "81E32F8E31236EF84C21287F1FBAA916FC6525B2E63220D4A0F2396E91871D50";
    };
    "nix-public/org/scala-lang/scala-library/2.12.19/scala-library-2.12.19.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.19/scala-library-2.12.19.pom";
      sha256 = "C5646BBD1A8EE70A49DB017312ECDC1AF2B5602EC0106C43F8B8A9714CFACB54";
    };
    "nix-public/org/scala-lang/scala-library/2.12.20/scala-library-2.12.20-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.20/scala-library-2.12.20-javadoc.jar";
      sha256 = "1A318A6BF41FE3C28BE1C218DEE4371BCABB456AA3433CCC7E26BB3596FE35FD";
    };
    "nix-public/org/scala-lang/scala-library/2.12.20/scala-library-2.12.20-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.20/scala-library-2.12.20-sources.jar";
      sha256 = "C64CC0D241CC7515240D55AAC05213C8C518940A1CCF229C90B8F43BCF3C38EE";
    };
    "nix-public/org/scala-lang/scala-library/2.12.20/scala-library-2.12.20.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.20/scala-library-2.12.20.jar";
      sha256 = "4D8A8F984CCE31A329A24F10B0BF336F042CB62AEB435290A1B20243154CFCCB";
    };
    "nix-public/org/scala-lang/scala-library/2.12.20/scala-library-2.12.20.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.20/scala-library-2.12.20.pom";
      sha256 = "94C315B4C51A4C8D0A33F177E160DDAD63B68595FEB3997FA25791C5A14A03C9";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.17/scala-reflect-2.12.17-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.17/scala-reflect-2.12.17-javadoc.jar";
      sha256 = "BDB27E011213E31F7780564AF381006C1C7EF46FE2DE0E5B47957F739D2ACD80";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.17/scala-reflect-2.12.17-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.17/scala-reflect-2.12.17-sources.jar";
      sha256 = "2920A41E4C421CB93BDD67D7854A29717C1F0AB0C8380A24810F51582172AA3D";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.17/scala-reflect-2.12.17.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.17/scala-reflect-2.12.17.jar";
      sha256 = "000C8142B28FBA079EB1E3C56B7587D73B48F8B23FB22123D8403CA84BFAD7DB";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.17/scala-reflect-2.12.17.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.17/scala-reflect-2.12.17.pom";
      sha256 = "FFBEA439D309E57751D5A59EE38EE9B2B72FE493373C720A5D19631D52B2EDEA";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.20/scala-reflect-2.12.20-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.20/scala-reflect-2.12.20-javadoc.jar";
      sha256 = "8873C5C2B985427F4EA838B52CED831C1BDC819A20863FA5CA2A56580645E108";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.20/scala-reflect-2.12.20-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.20/scala-reflect-2.12.20-sources.jar";
      sha256 = "1ADD39697B43C4E967C79C2DFA5A1ECA493E56DC66FD14D7566F8E2C306C65FA";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.20/scala-reflect-2.12.20.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.20/scala-reflect-2.12.20.jar";
      sha256 = "5F1914CDC7A70580EA6038D929EBB25736ECF2234F677E2D47F8A4B2BC81E1FB";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.20/scala-reflect-2.12.20.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.20/scala-reflect-2.12.20.pom";
      sha256 = "6151C44B5EC49F7E9555450D6ACE47E994129B511119CF364045E18864AF8E96";
    };
    "nix-public/org/scala-sbt/sbt-launch/1.10.7/sbt-launch-1.10.7-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/sbt-launch/1.10.7/sbt-launch-1.10.7-javadoc.jar";
      sha256 = "D653AADE571393B17CF4BF5157A64EBBA0F2D6F2909254CD0E120159E52AECC6";
    };
    "nix-public/org/scala-sbt/sbt-launch/1.10.7/sbt-launch-1.10.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/sbt-launch/1.10.7/sbt-launch-1.10.7-sources.jar";
      sha256 = "9DBAD0C29F46D0EEBA8E67662BDDAACA5A90143B81AC668BC4381A2A2D26B92C";
    };
    "nix-public/org/scala-sbt/sbt-launch/1.10.7/sbt-launch-1.10.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/sbt-launch/1.10.7/sbt-launch-1.10.7.jar";
      sha256 = "3CCA02818047327A83EFDE776103A1EF92F76F72C062BADBBB062499A3270C07";
    };
    "nix-public/org/scala-sbt/sbt-launch/1.10.7/sbt-launch-1.10.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/sbt-launch/1.10.7/sbt-launch-1.10.7.pom";
      sha256 = "803A10C3C4F4EE0D32BCE495742C7E5AAAC7E29657D31B14F4BA32BBC58AEA81";
    };
    "nix-public/org/scala-sbt/sbt/1.10.7/sbt-1.10.7-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.10.7/sbt-1.10.7-javadoc.jar";
      sha256 = "AEE229482E8BC0ACF525AF586B5024B11ED6DAF2F8AC0C8C8B47E8B10AED72FD";
    };
    "nix-public/org/scala-sbt/sbt/1.10.7/sbt-1.10.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.10.7/sbt-1.10.7-sources.jar";
      sha256 = "347D478E1336FBF12435AAFEFB79ACA48570FC4BE5E29E42B2D1B47EABFCE39E";
    };
    "nix-public/org/scala-sbt/sbt/1.10.7/sbt-1.10.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.10.7/sbt-1.10.7.jar";
      sha256 = "DAAE3F9FB7D2C50A08F28FE119CB70E9CAB6E0DDE61575F4233E819D2725B7EE";
    };
    "nix-public/org/scala-sbt/sbt/1.10.7/sbt-1.10.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.10.7/sbt-1.10.7.pom";
      sha256 = "16DCB76F61D297899078B02375A8F1481AF678272D029617F2E535D163F3F5FA";
    };
    "nix-public/org/scala-sbt/scripted-sbt_2.12/1.10.7/scripted-sbt_2.12-1.10.7-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/scripted-sbt_2.12/1.10.7/scripted-sbt_2.12-1.10.7-javadoc.jar";
      sha256 = "B9A367BD50F880C1CAC789D56323B2761CC1C0B6BCD816D8576CB9E8499D82A2";
    };
    "nix-public/org/scala-sbt/scripted-sbt_2.12/1.10.7/scripted-sbt_2.12-1.10.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/scripted-sbt_2.12/1.10.7/scripted-sbt_2.12-1.10.7-sources.jar";
      sha256 = "86CCBB5B1C63CDB16AC40AF0D10085BB433EE40B91E0CB38F63EC9815F916C68";
    };
    "nix-public/org/scala-sbt/scripted-sbt_2.12/1.10.7/scripted-sbt_2.12-1.10.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/scripted-sbt_2.12/1.10.7/scripted-sbt_2.12-1.10.7.jar";
      sha256 = "D9262852BCF29BDEE2F36B8A33B71443F6D0CC14593CC02DA2D13A6E291C8C2E";
    };
    "nix-public/org/scala-sbt/scripted-sbt_2.12/1.10.7/scripted-sbt_2.12-1.10.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/scripted-sbt_2.12/1.10.7/scripted-sbt_2.12-1.10.7.pom";
      sha256 = "1E84F0FC6DBF00FEBDEDBC02E3554D40C05280F4ED3354E221175FB8C405D4CB";
    };
    "nix-public/org/scalactic/scalactic_2.12/3.2.18/scalactic_2.12-3.2.18-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalactic/scalactic_2.12/3.2.18/scalactic_2.12-3.2.18-javadoc.jar";
      sha256 = "AF5280876DBC64D50688DF474D721CA59FC02F18D6CAAE5B88E6CF2B0004CC16";
    };
    "nix-public/org/scalactic/scalactic_2.12/3.2.18/scalactic_2.12-3.2.18-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalactic/scalactic_2.12/3.2.18/scalactic_2.12-3.2.18-sources.jar";
      sha256 = "1AB57B1C633B68A9A14898CCA3C9478723C4951FDF7EB4A10F3214DEA23B8148";
    };
    "nix-public/org/scalactic/scalactic_2.12/3.2.18/scalactic_2.12-3.2.18.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalactic/scalactic_2.12/3.2.18/scalactic_2.12-3.2.18.jar";
      sha256 = "5E520FC51D470D939589380D869E698B83F468B85FD693F7563AA0FB5049B2DF";
    };
    "nix-public/org/scalactic/scalactic_2.12/3.2.18/scalactic_2.12-3.2.18.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalactic/scalactic_2.12/3.2.18/scalactic_2.12-3.2.18.pom";
      sha256 = "3738237BE463F91C3D59EE8E7663124BCEC69FCBA0F975E3145BB1DCC68DA26D";
    };
    "nix-public/org/scalatest/scalatest-compatible/3.2.18/scalatest-compatible-3.2.18-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-compatible/3.2.18/scalatest-compatible-3.2.18-javadoc.jar";
      sha256 = "D99D605195A6BFEBD77D192EF0330D0AB3869845AFFAE7EE88D3411777BA698D";
    };
    "nix-public/org/scalatest/scalatest-compatible/3.2.18/scalatest-compatible-3.2.18-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-compatible/3.2.18/scalatest-compatible-3.2.18-sources.jar";
      sha256 = "CF0EC8C128F36C11B2072AD9A0937950BC60A4EDAD800150A9F865DBCBD047A8";
    };
    "nix-public/org/scalatest/scalatest-compatible/3.2.18/scalatest-compatible-3.2.18.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-compatible/3.2.18/scalatest-compatible-3.2.18.jar";
      sha256 = "243B5C83A083B062C5670391E769A7FF2AF5C3BA093EF9ECF4FF9FE7CFEF248D";
    };
    "nix-public/org/scalatest/scalatest-compatible/3.2.18/scalatest-compatible-3.2.18.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-compatible/3.2.18/scalatest-compatible-3.2.18.pom";
      sha256 = "8D0F211CFBFE65AF71F1E042E3702E4C3BE89F1C54570372432B5A608DFE43E7";
    };
    "nix-public/org/scalatest/scalatest-core_2.12/3.2.18/scalatest-core_2.12-3.2.18-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-core_2.12/3.2.18/scalatest-core_2.12-3.2.18-javadoc.jar";
      sha256 = "ADF0C1749C0B986B999FBFE4CBA649A78920BA4ED471EC9C6E5E4173E181C5C0";
    };
    "nix-public/org/scalatest/scalatest-core_2.12/3.2.18/scalatest-core_2.12-3.2.18-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-core_2.12/3.2.18/scalatest-core_2.12-3.2.18-sources.jar";
      sha256 = "707974AFC9FE3FCCF67AD867DF41ABA37177257304C4F4DD786F7FFF29D53413";
    };
    "nix-public/org/scalatest/scalatest-core_2.12/3.2.18/scalatest-core_2.12-3.2.18.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-core_2.12/3.2.18/scalatest-core_2.12-3.2.18.jar";
      sha256 = "6037A2B88A8BA528CF498197BF917C683282010B74B8634B7388E488FB4E15C0";
    };
    "nix-public/org/scalatest/scalatest-core_2.12/3.2.18/scalatest-core_2.12-3.2.18.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-core_2.12/3.2.18/scalatest-core_2.12-3.2.18.pom";
      sha256 = "BF5AE8C6A3CCCF1458D96A10024B03C4485B3EEBDC823335C4A2505687B03215";
    };
    "nix-public/org/scalatest/scalatest-diagrams_2.12/3.2.18/scalatest-diagrams_2.12-3.2.18-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-diagrams_2.12/3.2.18/scalatest-diagrams_2.12-3.2.18-javadoc.jar";
      sha256 = "60E354326F78228E4BF6CC60CB35CED9ABA0E6EE51518632B46DD0A5950FD173";
    };
    "nix-public/org/scalatest/scalatest-diagrams_2.12/3.2.18/scalatest-diagrams_2.12-3.2.18-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-diagrams_2.12/3.2.18/scalatest-diagrams_2.12-3.2.18-sources.jar";
      sha256 = "18515B66661B4ED7C861A01618F1D92E90CB982AA22863897E90917F6E5595D4";
    };
    "nix-public/org/scalatest/scalatest-diagrams_2.12/3.2.18/scalatest-diagrams_2.12-3.2.18.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-diagrams_2.12/3.2.18/scalatest-diagrams_2.12-3.2.18.jar";
      sha256 = "916AEC4762974286E860FB3D4A7FD8D14926E6CA40B62ECA0889D971B6AD0F2C";
    };
    "nix-public/org/scalatest/scalatest-diagrams_2.12/3.2.18/scalatest-diagrams_2.12-3.2.18.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-diagrams_2.12/3.2.18/scalatest-diagrams_2.12-3.2.18.pom";
      sha256 = "7327AC767B89834713BD4AC8F16825606E3FDB7C02A255DD24E2323D09C79E1F";
    };
    "nix-public/org/scalatest/scalatest-featurespec_2.12/3.2.18/scalatest-featurespec_2.12-3.2.18-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-featurespec_2.12/3.2.18/scalatest-featurespec_2.12-3.2.18-javadoc.jar";
      sha256 = "57B2F1A3F292180E9017387633AF09299EB1175D6D7B01F836F5B994BE588BC9";
    };
    "nix-public/org/scalatest/scalatest-featurespec_2.12/3.2.18/scalatest-featurespec_2.12-3.2.18-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-featurespec_2.12/3.2.18/scalatest-featurespec_2.12-3.2.18-sources.jar";
      sha256 = "98DC2CECECE13375A67879D468127249CD817ADD87712211F3138F586C3FB9EA";
    };
    "nix-public/org/scalatest/scalatest-featurespec_2.12/3.2.18/scalatest-featurespec_2.12-3.2.18.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-featurespec_2.12/3.2.18/scalatest-featurespec_2.12-3.2.18.jar";
      sha256 = "8F64BBB1FA9E806DEB5D897E34F3A106BF4B77B7B4A42D732A63E55E7B03C83E";
    };
    "nix-public/org/scalatest/scalatest-featurespec_2.12/3.2.18/scalatest-featurespec_2.12-3.2.18.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-featurespec_2.12/3.2.18/scalatest-featurespec_2.12-3.2.18.pom";
      sha256 = "F7250F7E3A59656B3B3A92CC404DA5E2F9AC6DCBF8035155690392C3B131613C";
    };
    "nix-public/org/scalatest/scalatest-flatspec_2.12/3.2.18/scalatest-flatspec_2.12-3.2.18-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-flatspec_2.12/3.2.18/scalatest-flatspec_2.12-3.2.18-javadoc.jar";
      sha256 = "0DF9CFBDEB334AED016DBA20E74337BF7CC394B0541F359A6B781F300A2A1C19";
    };
    "nix-public/org/scalatest/scalatest-flatspec_2.12/3.2.18/scalatest-flatspec_2.12-3.2.18-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-flatspec_2.12/3.2.18/scalatest-flatspec_2.12-3.2.18-sources.jar";
      sha256 = "387219B5A77F691E5974324D1FB7F877D230DC3AFCE8B3C2F2FF3C5E1779CBDA";
    };
    "nix-public/org/scalatest/scalatest-flatspec_2.12/3.2.18/scalatest-flatspec_2.12-3.2.18.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-flatspec_2.12/3.2.18/scalatest-flatspec_2.12-3.2.18.jar";
      sha256 = "65337402514DF4A6ED3C792AAB94D0331E2819AA615BDB5AFDAEBA477B259B21";
    };
    "nix-public/org/scalatest/scalatest-flatspec_2.12/3.2.18/scalatest-flatspec_2.12-3.2.18.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-flatspec_2.12/3.2.18/scalatest-flatspec_2.12-3.2.18.pom";
      sha256 = "94A2A330965368796BE8BD3A720F3814A43B80DF4CB11DB10C9F1A92E4173EC4";
    };
    "nix-public/org/scalatest/scalatest-freespec_2.12/3.2.18/scalatest-freespec_2.12-3.2.18-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-freespec_2.12/3.2.18/scalatest-freespec_2.12-3.2.18-javadoc.jar";
      sha256 = "FFD790375937F2873CF73475C0FED7EBFE91FCFDCF096438C5FF554390874B70";
    };
    "nix-public/org/scalatest/scalatest-freespec_2.12/3.2.18/scalatest-freespec_2.12-3.2.18-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-freespec_2.12/3.2.18/scalatest-freespec_2.12-3.2.18-sources.jar";
      sha256 = "3CE16265D060E59A3661D851B26A40DFDB0F4E88EED8774912BB28BA2B376F14";
    };
    "nix-public/org/scalatest/scalatest-freespec_2.12/3.2.18/scalatest-freespec_2.12-3.2.18.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-freespec_2.12/3.2.18/scalatest-freespec_2.12-3.2.18.jar";
      sha256 = "80C52B882DE8DEC2FAAD62D44C50E7F6ADDECC8861E2BD81F3BEDDACDC7945F9";
    };
    "nix-public/org/scalatest/scalatest-freespec_2.12/3.2.18/scalatest-freespec_2.12-3.2.18.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-freespec_2.12/3.2.18/scalatest-freespec_2.12-3.2.18.pom";
      sha256 = "73E43371E9AC0EA7B332AE71B45A9EEB90834B34E1EFE0092533B458C716C636";
    };
    "nix-public/org/scalatest/scalatest-funspec_2.12/3.2.18/scalatest-funspec_2.12-3.2.18-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-funspec_2.12/3.2.18/scalatest-funspec_2.12-3.2.18-javadoc.jar";
      sha256 = "56CCBD2D87E7AB1237677A1FFC241EE618F4DA468790B012A882948ED1DF2532";
    };
    "nix-public/org/scalatest/scalatest-funspec_2.12/3.2.18/scalatest-funspec_2.12-3.2.18-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-funspec_2.12/3.2.18/scalatest-funspec_2.12-3.2.18-sources.jar";
      sha256 = "9F5D5BC2AE73527B84D38609A6DDC0ACACBDADEE2951D75722F979AA59C429C1";
    };
    "nix-public/org/scalatest/scalatest-funspec_2.12/3.2.18/scalatest-funspec_2.12-3.2.18.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-funspec_2.12/3.2.18/scalatest-funspec_2.12-3.2.18.jar";
      sha256 = "68B3BDAD7C3003A3AF8196E4B1EC9DC6DA66422731A03DDA616D35C59547CDC7";
    };
    "nix-public/org/scalatest/scalatest-funspec_2.12/3.2.18/scalatest-funspec_2.12-3.2.18.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-funspec_2.12/3.2.18/scalatest-funspec_2.12-3.2.18.pom";
      sha256 = "3167B0DA382759C3D4168EE516A67D9FB56A320669FA0DCB153A5C86F7C5880E";
    };
    "nix-public/org/scalatest/scalatest-funsuite_2.12/3.2.18/scalatest-funsuite_2.12-3.2.18-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-funsuite_2.12/3.2.18/scalatest-funsuite_2.12-3.2.18-javadoc.jar";
      sha256 = "1E8D182F58379A102D134C5ECA687652682703B4453E16BF6983E006932A56BA";
    };
    "nix-public/org/scalatest/scalatest-funsuite_2.12/3.2.18/scalatest-funsuite_2.12-3.2.18-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-funsuite_2.12/3.2.18/scalatest-funsuite_2.12-3.2.18-sources.jar";
      sha256 = "50BF3BDBA00F7AA74A8718EB3FB28087C3B528BCF7DC381E02DA0B833F890FFC";
    };
    "nix-public/org/scalatest/scalatest-funsuite_2.12/3.2.18/scalatest-funsuite_2.12-3.2.18.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-funsuite_2.12/3.2.18/scalatest-funsuite_2.12-3.2.18.jar";
      sha256 = "C8B978903AE84E4F111DCCC3BBFA073A6C11BC066134FD165D9B8971D1B9927E";
    };
    "nix-public/org/scalatest/scalatest-funsuite_2.12/3.2.18/scalatest-funsuite_2.12-3.2.18.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-funsuite_2.12/3.2.18/scalatest-funsuite_2.12-3.2.18.pom";
      sha256 = "248D0EACC5E6D3D05D8051A799AEC58569C1C610C502DB30D19D6266AC8F10E1";
    };
    "nix-public/org/scalatest/scalatest-matchers-core_2.12/3.2.18/scalatest-matchers-core_2.12-3.2.18-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-matchers-core_2.12/3.2.18/scalatest-matchers-core_2.12-3.2.18-javadoc.jar";
      sha256 = "DF7C82B80D2D7C950CADC9894E9C20CAD8D179FE38DAA94887EAC4E79A6EAB6C";
    };
    "nix-public/org/scalatest/scalatest-matchers-core_2.12/3.2.18/scalatest-matchers-core_2.12-3.2.18-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-matchers-core_2.12/3.2.18/scalatest-matchers-core_2.12-3.2.18-sources.jar";
      sha256 = "69E426D9CBFA4879AF344C654BA89A4ECBCC0B174CCA0842FA27E7DA3E66F55D";
    };
    "nix-public/org/scalatest/scalatest-matchers-core_2.12/3.2.18/scalatest-matchers-core_2.12-3.2.18.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-matchers-core_2.12/3.2.18/scalatest-matchers-core_2.12-3.2.18.jar";
      sha256 = "C3BD6BE0C794D974E18652FA6A24332675CC5C4695F6D02AC6A62B07D3233A76";
    };
    "nix-public/org/scalatest/scalatest-matchers-core_2.12/3.2.18/scalatest-matchers-core_2.12-3.2.18.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-matchers-core_2.12/3.2.18/scalatest-matchers-core_2.12-3.2.18.pom";
      sha256 = "B7FED8A52B2B53086F725788EB28E4D91E8DC4A4F1E019B5CCD10A64254029EA";
    };
    "nix-public/org/scalatest/scalatest-mustmatchers_2.12/3.2.18/scalatest-mustmatchers_2.12-3.2.18-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-mustmatchers_2.12/3.2.18/scalatest-mustmatchers_2.12-3.2.18-javadoc.jar";
      sha256 = "E9DB434C22D8C80DAC92AC61C12636E338B54ED65427CF078A8D2C2D95CBB4E4";
    };
    "nix-public/org/scalatest/scalatest-mustmatchers_2.12/3.2.18/scalatest-mustmatchers_2.12-3.2.18-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-mustmatchers_2.12/3.2.18/scalatest-mustmatchers_2.12-3.2.18-sources.jar";
      sha256 = "62DD6874B7EFA30B853DFEDF5FFF6C4366D0EBE09164CAEEA740C06DD0A96BAE";
    };
    "nix-public/org/scalatest/scalatest-mustmatchers_2.12/3.2.18/scalatest-mustmatchers_2.12-3.2.18.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-mustmatchers_2.12/3.2.18/scalatest-mustmatchers_2.12-3.2.18.jar";
      sha256 = "A5A8FD33C035E84D0679749FED3BA0366D31C7B9A852E0E18CF1F03597CD5E37";
    };
    "nix-public/org/scalatest/scalatest-mustmatchers_2.12/3.2.18/scalatest-mustmatchers_2.12-3.2.18.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-mustmatchers_2.12/3.2.18/scalatest-mustmatchers_2.12-3.2.18.pom";
      sha256 = "0E4D93AB372C770947AFAF1AEC2FABA6358B01C0D5C3DB478252C1E9B65CC209";
    };
    "nix-public/org/scalatest/scalatest-propspec_2.12/3.2.18/scalatest-propspec_2.12-3.2.18-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-propspec_2.12/3.2.18/scalatest-propspec_2.12-3.2.18-javadoc.jar";
      sha256 = "C63A1F72884B131B4D53E7C342F89857C856501D6B88A147E44F270818271A92";
    };
    "nix-public/org/scalatest/scalatest-propspec_2.12/3.2.18/scalatest-propspec_2.12-3.2.18-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-propspec_2.12/3.2.18/scalatest-propspec_2.12-3.2.18-sources.jar";
      sha256 = "D37B64BD086F49A80050A8A913DBD662CA85A46858C95CB95DDAD2D698D8F5E0";
    };
    "nix-public/org/scalatest/scalatest-propspec_2.12/3.2.18/scalatest-propspec_2.12-3.2.18.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-propspec_2.12/3.2.18/scalatest-propspec_2.12-3.2.18.jar";
      sha256 = "AE0E7D56A1E434CAEE4BE9B7D42ADBFAB936B71D766E696E04CB63DEC8819AB6";
    };
    "nix-public/org/scalatest/scalatest-propspec_2.12/3.2.18/scalatest-propspec_2.12-3.2.18.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-propspec_2.12/3.2.18/scalatest-propspec_2.12-3.2.18.pom";
      sha256 = "B61466172A73C0995365D2B0283D95FC7F8E0FBFE211D190DAB407D9E70ABC65";
    };
    "nix-public/org/scalatest/scalatest-refspec_2.12/3.2.18/scalatest-refspec_2.12-3.2.18-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-refspec_2.12/3.2.18/scalatest-refspec_2.12-3.2.18-javadoc.jar";
      sha256 = "FFB160F0EF40746364544A19731EBD3E31D5D4D5C075FDF9AA62F3556B153A61";
    };
    "nix-public/org/scalatest/scalatest-refspec_2.12/3.2.18/scalatest-refspec_2.12-3.2.18-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-refspec_2.12/3.2.18/scalatest-refspec_2.12-3.2.18-sources.jar";
      sha256 = "885661C54731A0DC9931A393DFB7C10014094ADEC26B5C5D59995C40D90C4546";
    };
    "nix-public/org/scalatest/scalatest-refspec_2.12/3.2.18/scalatest-refspec_2.12-3.2.18.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-refspec_2.12/3.2.18/scalatest-refspec_2.12-3.2.18.jar";
      sha256 = "12CAE6A1B51B6D7B23F31FA3185087A4EBF17A995049708C4503B2C5B6370783";
    };
    "nix-public/org/scalatest/scalatest-refspec_2.12/3.2.18/scalatest-refspec_2.12-3.2.18.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-refspec_2.12/3.2.18/scalatest-refspec_2.12-3.2.18.pom";
      sha256 = "49A27D833A2B54FF3C15257D33D062DE09838F57A1C9554844C9D4F16BCA72F2";
    };
    "nix-public/org/scalatest/scalatest-shouldmatchers_2.12/3.2.18/scalatest-shouldmatchers_2.12-3.2.18-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-shouldmatchers_2.12/3.2.18/scalatest-shouldmatchers_2.12-3.2.18-javadoc.jar";
      sha256 = "106BB3A5364101469750FF519DE9AC6A011588DD326910171C7676FB9B771D6D";
    };
    "nix-public/org/scalatest/scalatest-shouldmatchers_2.12/3.2.18/scalatest-shouldmatchers_2.12-3.2.18-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-shouldmatchers_2.12/3.2.18/scalatest-shouldmatchers_2.12-3.2.18-sources.jar";
      sha256 = "D9B1596A87D69A9FA3B592B833BDE4B6985CA18A926F569B469077A262DA5ECF";
    };
    "nix-public/org/scalatest/scalatest-shouldmatchers_2.12/3.2.18/scalatest-shouldmatchers_2.12-3.2.18.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-shouldmatchers_2.12/3.2.18/scalatest-shouldmatchers_2.12-3.2.18.jar";
      sha256 = "D77BAFF0DEAB085D3BFBCFBC40E8478092F8E925782DB38D1906A647104AA195";
    };
    "nix-public/org/scalatest/scalatest-shouldmatchers_2.12/3.2.18/scalatest-shouldmatchers_2.12-3.2.18.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-shouldmatchers_2.12/3.2.18/scalatest-shouldmatchers_2.12-3.2.18.pom";
      sha256 = "CCABEADA444870C42C8C391237EABA60D81BCEC3DF0950B19F74B472DDCADDE3";
    };
    "nix-public/org/scalatest/scalatest-wordspec_2.12/3.2.18/scalatest-wordspec_2.12-3.2.18-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-wordspec_2.12/3.2.18/scalatest-wordspec_2.12-3.2.18-javadoc.jar";
      sha256 = "0767634BF77C27C2F02EA2BA4422DB59160D6EE2AF02B12DDAC13B1D8FB9D432";
    };
    "nix-public/org/scalatest/scalatest-wordspec_2.12/3.2.18/scalatest-wordspec_2.12-3.2.18-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-wordspec_2.12/3.2.18/scalatest-wordspec_2.12-3.2.18-sources.jar";
      sha256 = "E8EE9A91BEA09FC7C16BA3E88F3C9EFC5493323B656C9812FAFEE1D3B5D02410";
    };
    "nix-public/org/scalatest/scalatest-wordspec_2.12/3.2.18/scalatest-wordspec_2.12-3.2.18.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-wordspec_2.12/3.2.18/scalatest-wordspec_2.12-3.2.18.jar";
      sha256 = "46C9D3BCAB39225401F961E20015A0BF585676F322A7DEF2AAC82782F3680586";
    };
    "nix-public/org/scalatest/scalatest-wordspec_2.12/3.2.18/scalatest-wordspec_2.12-3.2.18.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-wordspec_2.12/3.2.18/scalatest-wordspec_2.12-3.2.18.pom";
      sha256 = "910665D6FA827E6A31882BBA279A4294A2A16F08B316C77C4CD9A86610AFF01A";
    };
    "nix-public/org/scalatest/scalatest_2.12/3.2.18/scalatest_2.12-3.2.18-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest_2.12/3.2.18/scalatest_2.12-3.2.18-javadoc.jar";
      sha256 = "D653AADE571393B17CF4BF5157A64EBBA0F2D6F2909254CD0E120159E52AECC6";
    };
    "nix-public/org/scalatest/scalatest_2.12/3.2.18/scalatest_2.12-3.2.18-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest_2.12/3.2.18/scalatest_2.12-3.2.18-sources.jar";
      sha256 = "4D33A5A19B39E91D5AE30D3A812EE150F29961673170D7628B9F418C38DB6870";
    };
    "nix-public/org/scalatest/scalatest_2.12/3.2.18/scalatest_2.12-3.2.18.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest_2.12/3.2.18/scalatest_2.12-3.2.18.jar";
      sha256 = "F2A586ADD47E431D97EF7DC8205A5FC40ACB4F4F926F1613C116D33688A82F02";
    };
    "nix-public/org/scalatest/scalatest_2.12/3.2.18/scalatest_2.12-3.2.18.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest_2.12/3.2.18/scalatest_2.12-3.2.18.pom";
      sha256 = "14BFEC5036A2E2EFFD5E7C1947A0B4F3E7277B294EFE55821CCDD8FEA950CA93";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36-javadoc.jar";
      sha256 = "E0358188A55F7EE483A0B28BD2AAEA5262E0FAF93BB3CDDC13D5494AB383F987";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36-sources.jar";
      sha256 = "15BC04357A3725B7A5153F132DB71379F95E83B7B8590A86CC6D4AD77BFC150A";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36-tests.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36-tests.jar";
      sha256 = "EF8E69388790DE8D61DB8C6283A85A26AB4659BEA608B6AF576EE89F2AF91879";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.jar";
      sha256 = "D3EF575E3E4979678DC01BF1DCCE51021493B4D11FB7F1BE8AD982877C16A1C0";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.pom";
      sha256 = "FB046A9C229437928BB11C2D27C8B5D773EB8A25E60CBD253D985210DEDC2684";
    };
    "nix-public/org/slf4j/slf4j-parent/1.7.36/slf4j-parent-1.7.36.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.7.36/slf4j-parent-1.7.36.pom";
      sha256 = "BB388D37FBCDD3CDE64C3CEDE21838693218DC451F04040C5DF360A78ED7E812";
    };
    "nix-public/org/sonatype/forge/forge-parent/10/forge-parent-10.pom" = {
      url = "https://repo1.maven.org/maven2/org/sonatype/forge/forge-parent/10/forge-parent-10.pom";
      sha256 = "C14FB9C32B59CC03251F609416DB7C0CFF01F811EDCCCB4F6A865D6E7046BD0B";
    };
    "nix-public/org/tukaani/xz/1.9/xz-1.9-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/tukaani/xz/1.9/xz-1.9-javadoc.jar";
      sha256 = "8DF9D9940D4EA2F6F35382C21DD0A36B5F781028B4B9B3785EAFBDE8233B6EF8";
    };
    "nix-public/org/tukaani/xz/1.9/xz-1.9-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/tukaani/xz/1.9/xz-1.9-sources.jar";
      sha256 = "5BEFA47F06B90E752F035191DDE7F2DEB59F36000F1CA6CC77D2362A82B6F462";
    };
    "nix-public/org/tukaani/xz/1.9/xz-1.9.jar" = {
      url = "https://repo1.maven.org/maven2/org/tukaani/xz/1.9/xz-1.9.jar";
      sha256 = "211B306CFC44F8F96DF3A0A3DDAF75BA8C5289EED77D60D72F889BB855F535E5";
    };
    "nix-public/org/tukaani/xz/1.9/xz-1.9.pom" = {
      url = "https://repo1.maven.org/maven2/org/tukaani/xz/1.9/xz-1.9.pom";
      sha256 = "093BE1B03331BCE2932D6825C37E98272D7621E6A9E9FB93289A002518B8DD5A";
    };
    "nix-public/org/virtuslab/scala-cli/config_2.12/1.1.3/config_2.12-1.1.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/virtuslab/scala-cli/config_2.12/1.1.3/config_2.12-1.1.3-javadoc.jar";
      sha256 = "8A903E9E45D18815E5EBA7DEECFFAFA7F90B198ADFEF53E74B1AC84F9DCF44A6";
    };
    "nix-public/org/virtuslab/scala-cli/config_2.12/1.1.3/config_2.12-1.1.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/virtuslab/scala-cli/config_2.12/1.1.3/config_2.12-1.1.3-sources.jar";
      sha256 = "E68CA512545BDC259E2F101E92A65D080C87D99176D0F8A151954A7074BB7E23";
    };
    "nix-public/org/virtuslab/scala-cli/config_2.12/1.1.3/config_2.12-1.1.3.jar" = {
      url = "https://repo1.maven.org/maven2/org/virtuslab/scala-cli/config_2.12/1.1.3/config_2.12-1.1.3.jar";
      sha256 = "D7B41D6AAC1052FF9D7E7F90E756AFB7DD3A562C78C78FAF4BA9D75232DD9454";
    };
    "nix-public/org/virtuslab/scala-cli/config_2.12/1.1.3/config_2.12-1.1.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/virtuslab/scala-cli/config_2.12/1.1.3/config_2.12-1.1.3.pom";
      sha256 = "2521AE10399C0FD88F2467B13E65229AEE8A17AA4AD03B9344CB1608D6680280";
    };
    "nix-public/org/virtuslab/scala-cli/specification-level_2.12/1.1.3/specification-level_2.12-1.1.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/virtuslab/scala-cli/specification-level_2.12/1.1.3/specification-level_2.12-1.1.3-javadoc.jar";
      sha256 = "3DA067F598964D1AB478107ECD0C60E8E647E515AE5CAA2F79C8350518309C33";
    };
    "nix-public/org/virtuslab/scala-cli/specification-level_2.12/1.1.3/specification-level_2.12-1.1.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/virtuslab/scala-cli/specification-level_2.12/1.1.3/specification-level_2.12-1.1.3-sources.jar";
      sha256 = "50138A16137ADD84B1E145E9F89F2BAFE32955DF99A09FD360CA16FC14CA86E1";
    };
    "nix-public/org/virtuslab/scala-cli/specification-level_2.12/1.1.3/specification-level_2.12-1.1.3.jar" = {
      url = "https://repo1.maven.org/maven2/org/virtuslab/scala-cli/specification-level_2.12/1.1.3/specification-level_2.12-1.1.3.jar";
      sha256 = "A4748FE8A15594AACFBDB30F1941A78C56D814B482BBE7ABC49EF4F206E780AD";
    };
    "nix-public/org/virtuslab/scala-cli/specification-level_2.12/1.1.3/specification-level_2.12-1.1.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/virtuslab/scala-cli/specification-level_2.12/1.1.3/specification-level_2.12-1.1.3.pom";
      sha256 = "7CF8FD511D796D5F6E1C398A2E263308A8B09C0B7B641B46E3B8E58F5D9FFA5B";
    };
  };
}